### PR TITLE
fix: Add Volume button on Cloud Manager Linode page causing browser to freeze

### PR DESCRIPTION
**Pull request by coliu-akamai**
## Description 📝
Reverts the changes from [this PR](https://github.com/linode/manager/pull/10970) to remove the useEffect so that the page doesn't crash. Note that this means there will be a console error again - we'll have to look into how to handle that issue differently.

## Changes  🔄
- Reverts change to remove useEffect

## Target release date 🗓️
10/2

## reproduction steps
- On the Linode Storage tab, when clicking 'Add Volume', notice how the page freezes afterwards

## Verification steps
- confirm the page freeze no longer happens

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by abailly-akamai — APPROVED** [review]
Thank you

**Review by cpathipa — APPROVED** [review]

**Review by bnussman-akamai — APPROVED** [review]
Looks good! Thank you.

I know calling `setState` on render is causing us console errors, but the React docs seem to recommend it... I wonder if those docs only apply to certain circumstances or the console warning can just safely be ignored

Screenshot 2024-10-02 at 10 07 34 AM

**Comment by bnussman-akamai** [comment]
I may have answered my own question after reading this:

> React only lets you update the same component’s state during a render. If you update another component’s state during a render, you’ll see an error. A condition like items !== prevItems is necessary to avoid loops. You may adjust state like this, but any other side effects (like changing the DOM or setting timeouts) should stay in event handlers or Effects to [keep components pure.](https://react.dev/learn/keeping-components-pure)

**Comment by coliu-akamai** [comment]
Merging this to staging as all checks have passed! @bnussman-akamai you might need to resolve a small changelog conflict afterwards

**Pull request merged**
