### PR TITLE
small fix for stackscripts e2e

### PR DESCRIPTION
**Pull request by ndukatz**
## Description
This change was needed because of some recent ui changes to this page

**What does this PR do?**
just a small stackscripts e2e test update

## How to test
- `yarn up` in one terminal
- `yarn cy:e2e -s ./cypress/integration/stackscripts/stackscripts.spec.ts` in another
- Result should be `✔  All specs passed!`

## Make sure your .env contains:
```
REACT_APP_LOGIN_ROOT
REACT_APP_API_ROOT
REACT_APP_APP_ROOT
REACT_APP_LAUNCH_DARKLY_ID
REACT_APP_CLIENT_ID
MANAGER_OAUTH
```

### CODE REVIEW

**Review by Jskobos — APPROVED** [review]

**Review by DevDW — COMMENTED** [review]
It's failing for me:

Screen Shot 2021-04-26 at 11 37 25 AM

**Review by johnwcallahan — COMMENTED** [review]
I'm seeing the same failure as @DevDW, though when I run it in non-headless mode I get the error "Unable to find element with text 'Deploy New Linode'" (even though I can see it on the page).

**Comment by ndukatz** [comment]
@DevDW @johnwcallahan which accounts are you using?

**Comment by DevDW** [comment]
> @DevDW @johnwcallahan which accounts are you using?

I observed it when running it under my personal account

**Comment by ndukatz** [comment]
Okay, that should be fixed now. The issue was with accounts with multiple account stackscripts. Even though only one action menu was open, the elements from all of the closed action menus are still visible.

**Review by DevDW — APPROVED** [review]
> Okay, that should be fixed now. The issue was with accounts with multiple account stackscripts. Even though only one action menu was open, the elements from all of the closed action menus are still visible.

Ah okay, thanks for clarifying and fixing. I ran the test again and it is passing now. 🚢

**Pull request merged**
