### PR TITLE
fix disk size label bleed

### LINKED ISSUE #453: Prevent disk size label from bleeding over in disk edit view

### PR DESCRIPTION
**Pull request by na3d**
Closes #453

### CODE REVIEW

**Comment by na3d** [comment]
screen shot 2016-09-14 at 3 22 55 pm

**Comment by na3d** [comment]
Where is says Currently [size], it says in that position, instead of following the little dot.

**Comment by eatonphil** [comment]
Hmm. If the thing next to the resize is the max size, we should say that. Perhaps add a new col/input saying Max size or unallocated space with an input disabled with the max size.

**Comment by na3d** [comment]
What is next to resize is the current size the big circle is at.

**Comment by eatonphil** [comment]
You just used "current" in your comment than what "current" means in the screenshot. I think we should be clearer about what "current" means (by labeling things).

**Comment by na3d** [comment]
That is why I said Currently in the screen, because it is where the disk is actually currently at.  While resize is where it is resized to.  I feel the muted text also makes it more obvious that it goes with the little circle.

When you drag the big circle around, of course the text next to resize changes live.

**Comment by eatonphil** [comment]
Hands down this is not clear enough.

**Comment by na3d** [comment]
Want to design a screen that is?

**Comment by eatonphil** [comment]
@abemassry and I were talking - you will probably honestly want an actual input. Most of the time I think of segregating my disks in exact numbers. We don't want to not have a number input for that.

screen shot 2016-09-14 at 4 33 31 pm

**Comment by abemassry** [comment]
I vote a new issue and PR be created for @eatonphil's comments.  This would be outside the scope of this current issue.

**Comment by na3d** [comment]
Yeah, I have to agree with @abemassry on this one.  This is more than just a minor tweak, and should be discussed more.

Side Note: There is a minimum size as well.

**Comment by eatonphil** [comment]
There is a new issue. Vote to close or slate this PR because it solves the original issue in a completely different way than we are discussing in #467.

**Pull request closed without merging**
