### PR TITLE
Reset root password

### LINKED ISSUE #806: Enter to submit form doesn't work on many forms
Disk edit is one of them. We should find them all and make them all work.

### PR DESCRIPTION
**Pull request by mparke**
Closes #806 

- Updates reset root password to use a form element, enabling enter to submit by default
- Defers form submit to the form ( for reset password )
- Updates ConfirmModal to be shared/accessible ( dedupe )
- Also moves Modal into same component directory
- Uses props.children for submit/cancel so that icons and/or other content can be used ( remembered this suggestion from @eatonphil , fixing while here.
- Fixes/Updates tests where needed

### CODE REVIEW

**Comment by eatonphil** [comment]
We have not before made subfolders in the components or layouts folders so this would be the first. Is that what you're going for?

**Comment by mparke** [comment]
@eatonphil Yes, just looking to organize generic components by type. Open to suggestions.

**Comment by eatonphil** [comment]
Kk, I'd like to talk about it in person before this gets merged.

**Comment by eatonphil** [comment]
No UI changes, correct?

**Comment by mparke** [comment]
@eatonphil Correct, the UI is the same

**Pull request merged**
