### PR TITLE
Dnsmanager select all

### LINKED ISSUE #673: Add select/delete all to dns view

### PR DESCRIPTION
**Pull request by abemassry**
closes #673

### CODE REVIEW

**Comment by mparke** [comment]
looks and is selectable when checkbox not checked. 

allows me to open the modal with no context

page is throwing errors which may be fixed in https://github.com/linode/manager/pull/1237

screen shot 2017-02-16 at 3 28 21 pm

**Comment by mparke** [comment]
sorry should have specified desired: disabled button if nothing checked, should fix weirdness

**Comment by mparke** [comment]
should be hidden in blank slate state:

screen shot 2017-02-16 at 5 32 51 pm

needs `cursor:pointer` on checkbox hover

**Comment by mparke** [comment]
hover added here: https://github.com/linode/manager/pull/1254

**Comment by abemassry** [comment]
thanks!

**Pull request merged**
