### PR TITLE
Switch to rectangular flags

### PR DESCRIPTION
**Pull request by eatonphil**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
I think you need to add `flag-icon-css` to the package.json.

**Comment by eatonphil** [comment]
https://github.com/linode/manager/pull/167/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R90?

**Comment by SirCmpwn** [comment]
Whoops.

**Comment by eatonphil** [comment]
I wasn't sure why the `file!` specification before the import was necessary because it worked in the app. In the tests though it didn't know what to do with it. I'm guessing there's just some missing webpack configs.

Ready for merge.

**Comment by eatonphil** [comment]
Thanks!

**Pull request merged**
