### PR TITLE
M3-4328 Query sorting

### PR DESCRIPTION
**Pull request by Jskobos**
Adjust query sorting

- Save entity table sorting in user preferences
- Since this is dynamic, remove the SortKey type and wing it
- Read query params in OrderBy, and assign the default sort in the
following precedence:
  1. query params
  2. user preferences
  3. component-specific values
  4. default values

## Note to Reviewers

One quirk of this approach is that if the url contains a garbage sort key (e.g. "label" on the Domains table), we revert back to the defaults, since query params are highest priority and the sort keys are unknown (in OrderBy where this is happening). I think this is ok--you can always sort the table yourself after loading, and if you click a bad url it isn't exactly our fault. Open to feedback though.

### CODE REVIEW

**Review by johnwcallahan — COMMENTED** [review]
This approach works well. 

One thing we might want to do is update the query params dynamically when the user clicks on cells to sort them.

**Review by DevDW — APPROVED** [review]
LGTM, nice work 🚢

**Review by johnwcallahan — COMMENTED** [review]
Almost there, but I think this should use `history.replace` instead of push so we avoid creating a bunch of items on the history stack when sorting.

**Review by johnwcallahan — APPROVED** [review]
LGTM. As a low-priority followup, we could "beautify" the some of the query params since this looks a bit awkward: 

Screen Shot 2020-11-17 at 9 17 13 AM

**Pull request merged**
