### PR TITLE
Global Button & Link updates

### PR DESCRIPTION
**Pull request by WilkinsKa1**
## Description

Major changes here, impacting **BOTH** CMR and non-CMR:

• Removal of destruction/cancel styling (no more red- more on this below)
• Adding underline to regular links on hover

There should now be **3 types of buttons**:
• primary (blue bg, white text, rounded corners)
• secondary (bolded, blue text, no border)
• secondary w/ icon
Since we got rid of the red destructive styling, those buttons now inherit as primary buttons, and 'cancel' inherit as secondary buttons.

## Type of Change
- Non breaking change ('change')

## Note to Reviewers

Please comb through the app, both versions, both color themes, for discrepancies. I was pretty thorough but there's so much going on it's likely I missed something. Also let me know if you'd like me to delete the commented out styling in the theme files- I kept it for now in case it was needed but would help with cleaning up the code a bit more.

### CODE REVIEW

**Review by Jskobos — CHANGES_REQUESTED** [review]
Looking good so far. Found a few things, mostly wrapping oddities:

Backups CTA, non-CMR:
Screen Shot 2020-11-23 at 10 07 08 AM

Email bounce: 
Screen Shot 2020-11-23 at 10 08 03 AM

This may be a regression from elsewhere:
Screen Shot 2020-11-23 at 9 57 17 AM

And this is not on develop but I can't see how anything in this PR is causing it: 
Screen Shot 2020-11-23 at 10 11 11 AM

**Comment by WilkinsKa1** [comment]
@Jskobos thanks for the feedback- all has been addressed except for the scrolling table (we changed the max width of the main content section, and this will be updated when we handle the landing adjustments)

**Review by tiffwong — CHANGES_REQUESTED** [review]
Great job! Found a few things:

Is the secondary button supposed to have a border in dark mode?
Also the gravatar is throwing an error in Linode Create (not sure when this happened, it's working fine in develop)
Screen Shot 2020-11-23 at 1 42 54 PM

The "Power Off" button is secondary instead of primary, the same thing with "Confirm Payment"

I think the secondary buttons might be shorter than the primary,
Screen Shot 2020-11-23 at 1 55 23 PM

These links are different colors,
Screen Shot 2020-11-23 at 2 01 17 PM

These links on hover turn white for dark mode,
Screen Shot 2020-11-23 at 2 03 41 PM

**Review by johnwcallahan — COMMENTED** [review]
I looked through most of the app on Safari (CMR and non). 

A few things:

Linode Delete Modal (dark mode):
Screen Shot 2020-11-23 at 4 43 44 PM

Account links:
Screen Shot 2020-11-23 at 4 43 27 PM

**Comment by tiffwong** [comment]
Found another destructive button on Domain Detail,
Screen Shot 2020-11-23 at 5 30 21 PM

**Review by DevDW — COMMENTED** [review]
Great work! I saw a few things:

**Non-CMR**
The background of some dark mode sub-components/component pieces:

Screen Shot 2020-11-23 at 6 46 44 PM

The borders of entity table headers are inconsistent, Linodes landing is one example but I saw on Images and Domains also

Screen Shot 2020-11-23 at 6 45 00 PM

**CMR**
LinodeEntityDetail -- maybe this is a new revision from the past couple of weeks and/or we're waiting on some new pieces to insert, but there's a lot of white space to the right of the actions

Screen Shot 2020-11-23 at 6 30 01 PM

Backgrounds of sub-components/component pieces in the dark mode modals -- all of them I think, but a few examples:
<details>
<summary>Examples</summary>
Screen Shot 2020-11-23 at 6 44 36 PM

Screen Shot 2020-11-23 at 6 44 19 PM

Screen Shot 2020-11-23 at 6 43 58 PM

Screen Shot 2020-11-23 at 6 43 29 PM
</details>

**Comment by WilkinsKa1** [comment]
@DevDW thanks for the feedback on those items! Due to the current size and scope of this PR, I've created 2 new tickets to address the panel backgrounds and border discrepancies.

**Review by tiffwong — APPROVED** [review]

**Review by johnwcallahan — APPROVED** [review]
Love it, looks great.

**Pull request merged**
