### PR TITLE
M3-4744 Filter Linodes (and NodeBalacers) by IP

### PR DESCRIPTION
**Pull request by bnussman**
## Description

When a user has a large linode account with many Linodes, allow search to use the API to filter by IPv4 address. 

## How to test

- Login to the cloud manager
- Have at least 1 Linode
- Enter an IP address of a linode into the search box
- Verify search finds Linodes by IP address while also ensuring you can still search on other properties 

Cloud Manager is aware of whether or not a user has a _large_ Linode account. If an account is large, search will happen at an API level. _Small_  Linode accounts use client side searching therefore can already can search by IP.

To simulate testing on a large paginated amount of Linodes, you can temporarily set `_isLargeAccount` to true here https://github.com/linode/manager/blob/d4578ff3a8b54e84c658ebea50a47c13abb0eee7/packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx#L86

### CODE REVIEW

**Comment by bnussman** [comment]
Also, this PR fixes a minor bug where the search page is missing a NodeBalancer's region. 
Screen Shot 2021-05-18 at 4 41 16 PM

**Review by johnwcallahan — APPROVED** [review]
Great job, this works really well. I tested it with the simulation you provided, my regular (small) test account, and an actual large account and it all works as expected.

Please point this at staging and let's go ahead and release it once fully approved.

**Review by codyfinn — APPROVED** [review]
Works for me. Nice job fixing this!

**Comment by johnwcallahan** [comment]
This was merged as a hotfix: https://github.com/linode/manager/commit/876e528203c24c45e20cfaff24d3f67e1d32a6f1.

**Pull request closed without merging**
