### PR TITLE
Revert "test: [M3-7863] - Use `happy-dom` instead of `jsdom` in unit tests (#11085)"

### PR DESCRIPTION
**Pull request by bnussman-akamai**
## Description 📝
- Reverts #11085 (commit efa85802c21e63e41dbce3517826090c8486e6dd)
- Unfortunately, `happy-dom` **did** end up introducing significant unit test fake for us particularly in our coverage script
- View @abailly-akamai 's internal Slack thread for more details on the findings/impact 🔍 

## How to test 🧪

- Verify GitHub Actions pass (both the unit test job and the overage jobs)
  - I believe the `base_branch` coverage job failure is okay because that is what this PR will fix once it is in develop
- Run some tests locally to check for stability (`yarn test`)
- Run the coverage script locally and verify (`yarn coverage`)

## As an Author I have considered 🤔

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by abailly-akamai — APPROVED** [review]
Thanks @bnussman-akamai - base branch coverage still erroring as expected since still using `happy-dom`, but other checks looking healthy ✅

**Comment by coliu-akamai** [comment]
should we revert #11104 as too?

**Comment by bnussman-akamai** [comment]
We probably could @coliu-akamai  I can do it as a follow up to this PR

**Review by coliu-akamai — APPROVED** [review]
thanks @bnussman-akamai! 🚀

**Pull request merged**
