### PR TITLE
M3-5319: Make sure Bare Metal plans appear for accounts w/ appropriate tag

### PR DESCRIPTION
**Pull request by DevDW**
## Description
When pointed at the prod API, Cloud is not displaying Bare Metal plans, even for accounts properly tagged for Bare Metal. This is occurring because of caching logic in `linodeType.requests.ts`.

This PR removes that caching logic. I think this path is preferable to requesting types upon hitting the Linode Create page because `requestTypes()` only runs once as a secondary request in `AuthenticationWrapper.tsx`.

## How to test
Point at the prod API; accounts not tagged for Bare Metal should not see Bare Metal plans in the "Linode Plan" panel of the Create flow. Accounts tagged for Bare Metal should see the plans.

### CODE REVIEW

**Review by johnwcallahan — COMMENTED** [review]
The changes to `linodeTypes.requests.ts` look good.

We'll also want to remove the linode types endpoint from buildRequests.js and the types.json file (which means we'll have to adjust a few places around the app that use it).

**Review by HanaXu — APPROVED** [review]
LGTM!

**Comment by DevDW** [comment]
@HanaXu that review dismissal was due to an automatic setting for merging into `staging` 😕

**Comment by HanaXu** [comment]
@DevDW Oof, same for my PR. I just re-requested your review on that 👀

**Review by HanaXu — APPROVED** [review]

**Review by tiffwong — APPROVED** [review]
LGTM

**Pull request merged**
