### PR TITLE
feat: [UIE-8194] - DBaaS Upgrades and Maintenance 4

### PR DESCRIPTION
**Pull request by corya-akamai**
## Description 📝
DBaaS Upgrades and Maintenance 4 of 4

## Changes  🔄
- Integration of components into settings, create, resize, landing, summary

## Target release date 🗓️
11/12/24

## Preview 📷
integration

### Prerequisites
- Managed Databases
- dbaasV2 feature flag set for GA
- Default DB created e.g. postgresql 13

### Verification steps
- Verify you can upgrade to postgresql 14, 15, 16
- View maintenance

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [x] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by cpathipa — COMMENTED** [review]
Conflicts should be resolved updated with latest from develop.

**Comment by corya-akamai** [comment]
> Conflicts should be resolved updated with latest from develop.

@cpathipa resolved conflicts and added changeset. Thanks

**Review by cpathipa — COMMENTED** [review]
@corya-akamai There is build failure on this. I think this has dependency on this PR https://github.com/linode/manager/pull/11197/files#diff-c7bc9409300f0b29def80919b42bc636ac185fa1f8a2ea216947337a97b01577. I think #11197 merging first should solve the issue. Lets rebase #11197 and aim to merge, this should solve the issue. 

image

**Comment by corya-akamai** [comment]
> @corya-akamai There is build failure on this. I think this has dependency on this PR https://github.com/linode/manager/pull/11197/files#diff-c7bc9409300f0b29def80919b42bc636ac185fa1f8a2ea216947337a97b01577. I think #11197 merging first should solve the issue. Lets rebase #11197 and aim to merge, this should solve the issue.
> 
> image

Thanks @cpathipa I've rebased and fixed the build. https://github.com/linode/manager/pull/11197/files can be closed, since https://github.com/linode/manager/pull/11198 contained 11197 too.

**Comment by cpathipa** [comment]
@corya-akamai There is an unit test failure in DatabaseSetting component. 

image

**Review by cpathipa — APPROVED** [review]
Functionality LGTM! conforming on creating database cluster, able to upgrade to 14,15 and 16.

**Review by bnussman-akamai — APPROVED** [review]

**Pull request merged**
