### PR TITLE
Logout & revoke tokens properly in other environments

### PR DESCRIPTION
**Pull request by johnwcallahan**
## Description

This addresses a few issues:

**Logout not working when using env switcher**
The Logout component uses the `CLIENT_ID` and `LOGIN_ROOT` constants instead of (potentially) the local storage overrides. This meant if you had a custom environment loaded, you couldn't logout correctly.

**Tokens not revoked in non-prod environments**
Turns out our logic to switch the URL for Login doesn't work (and maybe never did?) for non-prod environments. Our interceptor checks the Axios baseURL to determine if it's a Login endpoint. 

Thing is, in `packages/api-v4` the baseURL is `https://api.linode.com/v4` in all cases and `packages/manager` doesn't change it.

To fix this, I added a new generator function, `setBaseURL` which is used by the one Login endpoint (/oauth/revoke). 

This is a bit strange.... we don't really use Axios's `baseURL` the way it's intended (since we set the absolute API_ROOT on every endpoint). You could make a case for removing this Login endpoint from the `@linode-apiv4` package altogether, since it's not actually APIv4! **Feedback welcome.**

### Testing
⚠️  To be able to revoke tokens, **you must use a public OAuth Client** when running Cloud locally. ⚠️

To test, please check logout functionality in multiple environments, with and without the dev tools env switcher. Please check that you're redirected to the correct Login site, and that **your token is actually revoked** (check Chrome Dev Tools network tab, look for the POST to /oauth/revoke).

### CODE REVIEW

**Review by Jskobos — COMMENTED** [review]
This is working well so far, I need to do more testing though. Question in the meantime: why were we looking at the baseURL in the first place, if it's never used? I logged it and `url` from `request.tsx` and the url always seems to contain login when we're going to login. Maybe a better matching pattern (`/login(.*)linode\.com/` or something off the top of my head) would solve the problem without tinkering with the base url.

otoh, there's a case to be made for using the base url in the JS client properly, and overriding it for api4beta endpoints.

**Review by tiffwong — APPROVED** [review]
Great job! Everything works as expected now

**Comment by johnwcallahan** [comment]
> Question in the meantime: why were we looking at the baseURL in the first place, if it's never used?

It might have just been a misunderstanding of how the baseURL Axios config field works. The same problem existed when we first started looking for baseURL: https://github.com/linode/manager/pull/5455/files#diff-9e52115cf57e56f99c2232146944e3778469ddddeab9c0ecb1ba039f08dcd696R100

You're probably right that looking for `/login(.*)linode\.com/` in the URL would be more appropriate. 

If we go that route, we can clean up the baseURL business in the JS Client as a separate effort.

**Review by DevDW — APPROVED** [review]
Being redirected to the correct login site and the tokens are being revoked successfully

**Review by Jskobos — APPROVED** [review]
OK, I vote for removing this method from the JS client for the next release. This is good to go for the current release.

**Comment by johnwcallahan** [comment]
@Jskobos made this change; let me know what you think.

**Review by Jskobos — APPROVED** [review]
Seeing how much cleaner this makes things makes me feel more confident that we're doing the right thing.

**Pull request merged**
