### PR TITLE
Cleanup defaults focusing on font sizes

### LINKED ISSUE #989: Investigate component padding/margin to px values
We have some components using padding/margins defined in rem. Investigate applying px values, and looking for anything that might be getting computed in subpixels.

### LINKED ISSUE #1123: Review font-size and check sub-pixel rendering
Want to make sure that existing usage of `rem` and sub-pixel results will not cause issues in any font's we use. 

Compare to whole pixel values.

### PR DESCRIPTION
**Pull request by mparke**
pre-req to sizing (width, padding, font-size) for #1024 

closes #1123 
closes #1101 
closes #989 

- sets `html` font size to `10px`, so that other px/rem values can be defined based in `10` (for example `font-size(1.4)`

- new body default is `14px`, `1.4 rem`, @eatonphil take a look at this and let me know if you're still liking it from the other day. If not I'll just keep at `16px`.

- all font sizes should now render in whole pixel values ( as opposed to many sub-pixel results we have in master )

- redefines base font vars as classes which use a mixin.

applying a default font class:

```
@extends .font-normal;
```

applying a custom font using the mixin:

```
@include font-size(1.5);
```

- redefines (and fixes problems) where padding/margin were defined using `rem` values
- fixes `h4`, `h5`, `h6` heading tags, updates others with whole pixel values as compared to master
- creates new `scss` files:
  - `defaults.scss` ( our defaults for base elements )
  - `utilities.scss` ( shared classes )
  - `layout.scss` ( layout specific things that were in `manager.scss` )

### CODE REVIEW

**Comment by mparke** [comment]
Fixes based on feedback:

- [ ] sidebar list item padding reduction
- [ ] linode dashboard input width + button reflow
- [ ] tab > sub tab padding + alignment slightly off
- [ ] header padding slightly off ( too large )
- [ ] dashboard TODO (stats) top margin too large
- [ ] advanced tab missing padding
- [ ] top level tab padding too large, s/b 5px 15px 15px 15px
- [ ] move layout styles to scss/layout/Layout.scss

**Comment by mparke** [comment]
@eatonphil screen shot 2017-02-01 at 4 50 08 pm

**Comment by mparke** [comment]
@eatonphil  tell me if this alignment looks right to you screen shot 2017-02-01 at 5 27 16 pm

**Comment by mparke** [comment]
Just a heads up, since several of these margins were going slightly smaller ( 15px ), I updated `$grid-gutter-width-base: 30px;` (was previously `40px`).

There are places where this var is divided, and may result in sub-pixel values, but I think it's a trade off for now, and can be addressed later.

**Comment by eatonphil** [comment]
I think you missed legends in a label-col change:

screen shot 2017-02-02 at 11 42 32 am

See initrd, virtualization mode, run level vs every other label.

**Comment by eatonphil** [comment]
Missing padding below subtab in edit config page?

screen shot 2017-02-02 at 11 44 41 am

**Comment by mparke** [comment]
Fixed issues and rebased

**Pull request merged**
