### PR TITLE
Remove test/contexts

### PR DESCRIPTION
**Pull request by eatonphil**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Are the stubs valid between test runs when the sandbox is destroyed and recreated? And are they reset?

**Comment by eatonphil** [comment]
> Are the stubs valid between test runs when the sandbox is destroyed and recreated?

I don't follow.

> And are they reset?

Yes. Though it's reasonable I missed something.

**Comment by eatonphil** [comment]
Missed a line in the linter.

**Comment by SirCmpwn** [comment]
I guess it's not destroyed, but we create a new sandbox in beforeTest every time.

**Comment by eatonphil** [comment]
Is that an issue?

**Comment by SirCmpwn** [comment]
Yes. I'd rather not make new sandboxes that aren't used for every test. Just making one in the describe block and resetting it in the afterEach block would be cleaner.

**Comment by eatonphil** [comment]
Is this fine or do you want it to only be created once (so no `beforeEach` block)?

**Comment by SirCmpwn** [comment]
>only be created once (so no beforeEach block)?

This

**Comment by eatonphil** [comment]
Tests passing. How does it look?

**Comment by SirCmpwn** [comment]
I like it. Nice work. Mergable?

**Comment by eatonphil** [comment]
Yep.

**Comment by eatonphil** [comment]
ty

**Pull request merged**
