### PR TITLE
Create DocsSidebar component with state management.

### PR DESCRIPTION
**Pull request by rjstires**

### CODE REVIEW

**Comment by alioso** [comment]
This is a rather involving structural refactor. Needs thorough testing through the app at all breakpoints.

**Comment by rjstires** [comment]
I've thoroughly kicked the tires at mobile breakpoints both horizontal and portrait. Would defer to @asauber and @patthiel.

**Comment by patthiel** [comment]
These issues on small screens are  happening everywhere actually: 
screen shot 2018-04-23 at 2 46 51 pm

**Comment by patthiel** [comment]
aside from those issues, everything else looks good.

**Comment by alioso** [comment]
@patthiel good catch! pushed some fixes that address the issue (the tabs were overflowing the content of the page)

**Comment by patthiel** [comment]
@alioso lookin good now!  👍 ⚡️

**Comment by asauber** [comment]
nice technique, LGTM

**Pull request merged**
