### PR TITLE
Add Heebo and clean up header styles

### PR DESCRIPTION
**Pull request by eatonphil**
Following up on #72

### CODE REVIEW

**Comment by eatonphil** [comment]
Changing the font-size to rems breaks the dropdown it seems. I'm letting that go for now because it the Dropdown component needs to be rewritten to use Bootstrap.
screen shot 2016-06-14 at 4 19 04 pm

**Comment by eatonphil** [comment]
screen shot 2016-06-14 at 6 15 14 pm

**Comment by SirCmpwn** [comment]
We should self-host the font.

**Comment by eatonphil** [comment]
Do you want that to happen in this PR?

**Comment by eatonphil** [comment]
Self-hosting the fonts now.

**Comment by SirCmpwn** [comment]
Ready to merge (when build passes)?

**Comment by eatonphil** [comment]
Yes

**Comment by SirCmpwn** [comment]
Cool, sounds good.

**Comment by eatonphil** [comment]
Thank you!

**Pull request merged**
