### PR TITLE
Make casing slightly more consistent and fix typo in config helper label for automount devtmpfs

### PR DESCRIPTION
**Pull request by rmcintosh**
Trying to make casing a little more consistent here - fixed a typo while I was at it

### CODE REVIEW

**Review by Jskobos — APPROVED** [review]
Guess there's a reason we can't capitalize automount too? Sticks out a bit now. And if we really wanted to be consistent, we could do something like "Enable modules.dep helper."

None of this is blocking tho

**Review by tiffwong — APPROVED** [review]
I agree with @Jskobos's suggestions and if we do change it to "Enable modules.dep Helper", we should probably change "Enable Distro Helper" as well

**Comment by rmcintosh** [comment]
I was initially thinking that "automount" was a specific reference to the Linux utility but I think it's actually not and thus it should be capitalized and hyphenated like Auto-configure Networking

Agreed RE: the feedback on the other options - I can update

**Comment by rmcintosh** [comment]
thanks for finishing this one up, folks!

**Pull request merged**
