### PR TITLE
Implement 2016-05-24 API changes

### PR DESCRIPTION
**Pull request by SirCmpwn**

### CODE REVIEW

**Comment by eatonphil** [comment]
Have the API changes not been deployed yet? Everything you added breaks for me. The linode is still created but there is no `linode` attribute in the JSON response. Am I missing some other change?

**Comment by SirCmpwn** [comment]
They have been deployed, and it Works For Me(tm).

**Comment by eatonphil** [comment]
This is the response I get from the POST to /linodes:

    {"id": "linode_473", "datacenter": {"id": "datacenter_6", "label": "Newark, NJ"}, "alerts": {"cpu": {"enabled": true, "threshold": 90}, "transfer_quota": {"enabled": true, "threshold": 80}, "transfer_out": {"enabled": true, "threshold": 5}, "transfer_in": {"enabled": true, "threshold": 5}, "io": {"enabled": true, "threshold": 5000}}, "state": "provisioning", "total_transfer": 2000, "services": {"linode": "Linode 1024"}, "created": "2016-05-25T13:19:48", "updated": "2016-05-25T13:19:48", "label": "linode473", "group": "", "ip_addresses": {"public": {"ipv6": "2600:3c03::f03c:91ff:fe96:434c", "ipv4": ["97.107.143.82"], "failover": []}, "private": {"link_local": "fe80::f03c:91ff:fe96:434c", "ipv4": []}}, "distribution": {"id": "distro_142", "recommended": true, "vendor": "Arch", "x64": true, "label": "Arch Linux 2015.08", "experimental": false, "created": "2015-08-24T11:17:18", "minimum_image_size": 800}}

Why are our responses different?

**Comment by eatonphil** [comment]
Ok jeez I'm an idiot. Just a second.

**Comment by eatonphil** [comment]
Looks good. Ready for merge?

**Comment by SirCmpwn** [comment]
Yes.

**Comment by eatonphil** [comment]
:+1:

**Pull request merged**
