### PR TITLE
change: [M3-8530] - Allow quoted strings in Search v2 and improve StackScript searching on Linode Create v2 

### PR DESCRIPTION
**Pull request by bnussman-akamai**
## Description 📝

- Fixes https://github.com/linode/manager/issues/10869

### Allow spaces in search
- Allows users to use quoted strings (therefore spaces) when searching using Search v2 🔍 
  - For example, if you want to search for a StackScript with the label `My StackScript`, with this PR, you can search using a quoted string: `label: "My StackScript"`
    - ⚠️  Ideally, the user would be able to do `label: My StackScript` instead of `label: "My StackScript"`, but I couldn't quite get that working. I think it would require a significant rework of our search parser. I think a quoted string is probably a good step forward for now, but let me know if you disagree!
    
### Fix searching with `and` on StackScript tab of Linode Create
- Makes the user's search to have priority over the default StackScript filter 💪 
  - This fixes an issue where and queries would not work because they were overwritten by the default filter

## Preview 📷

|   | Before  | After   |
| -------| ------- | ------- |
| Search with string | Screenshot 2024-09-05 at 12 02 09 PM | Screenshot 2024-09-05 at 12 02 17 PM |
| Fix `and` queries | Screenshot 2024-09-05 at 12 03 25 PM | Screenshot 2024-09-05 at 12 03 15 PM |

## How to test 🧪

- Test the Search 🔍  functionality on http://localhost:3000/linodes/create?type=StackScripts&subtype=Community
  - Verify you can use spaces by using a quoted string
  - Verify you can use `and` in your search

## As an Author I have considered 🤔

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [x] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by dwiley-akamai — APPROVED** [review]
Can use spaces by using a quoted string ✅
Can use `and` in the search ✅

How are users informed of the rules governing the search functionality?

**Review by abailly-akamai — APPROVED** [review]
Confirmed both cases now work as expected. 

FWIW, it would be nice for the tooltip to show an actual example because it's confusing with the quotes in there. 

we could change:

```
Hint: try searching for a specific item by prepending your search term with "username:", "label:", or "description:"
```

to 
```
Hint: try searching for a specific item by prepending your search term with `username:`, `label:`, or `description:`. example: `label: "my label"`
```

**Comment by bnussman-akamai** [comment]
Good call @abailly-akamai 

I'll update the tooltip to include that example

**Comment by bnussman-akamai** [comment]
Thoughts? @abailly-akamai @dwiley-akamai 

This might be a bit much

Screenshot 2024-09-06 at 12 28 16 PM

**Comment by abailly-akamai** [comment]
@bnussman-akamai i think that's great! it's a bit intense but it's very clear 👍

**Comment by dwiley-akamai** [comment]
That looks good to me as well 🚀

**Pull request merged**
