### PR TITLE
Use smaller font for linode title

### LINKED ISSUE #829: Make Linode titles smaller

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #829

screen shot 2017-01-05 at 11 18 19 am
screen shot 2017-01-05 at 11 18 27 am

### CODE REVIEW

**Comment by na3d** [comment]
It looks like the text in the list view is a tiny bit lower than the card view.

**Comment by eatonphil** [comment]
The current font size has a similar issue. It's probably more a matter of how the line height takes into account taller letters. For instance I imagine it wouldn't seem off if you used all caps labels.

**Comment by eatonphil** [comment]
screen shot 2017-01-05 at 11 31 44 am

**Comment by eatonphil** [comment]
thank you!

**Pull request merged**
