### PR TITLE
M3-5427: Vertically center icons and texts in dropdown

### PR DESCRIPTION
**Pull request by tiffwong**
## Description

Remove spacing related styles that were throwing off the vertical alignment

## How to test

Check dropdown components throughout the app

### CODE REVIEW

**Review by HanaXu — APPROVED** [review]

**Comment by codyfinn** [comment]
I can't seem to remember how to get the exact measurements but here is what I am seeing on my end.
Screen Shot 2021-08-30 at 12 11 18 PM
I think the spacing difference between the top and the bottom of the flag icon is pretty noticeable.

**Review by DevDW — COMMENTED** [review]
I'm observing the same thing as Cody–probably has something to do with the specific styling on the flags? The Images dropdown for choosing a distribution, which is similar in terms of the icon + text pairing, looks good to me

**Comment by tiffwong** [comment]
@codyfinn @DevDW the recent changes should fix the spacing in Firefox, lmk if it looks good to you

**Review by DevDW — APPROVED** [review]
Looks good! 🚢

**Pull request merged**
