### PR TITLE
Landing pages tables loading

### PR DESCRIPTION
**Pull request by alioso**
The pattern used with the skeleton screen for loading table data was a bit problematic. 

Problem being that skeleton screens are used when markup is in place and data is loading. in our case we don’t know how many table rows we gonna get so we get jumpy UX once things get loaded.

I reverted to a mini loader and added col widths as well as a fade in class on the rows to give these a more natural loading feel.

### CODE REVIEW

**Comment by rjstires** [comment]
The transition when the data resolves looks great, subtle. I really don't know what the path forward is here other than going back to fully resolving the state before displaying anything at all.

**Comment by patthiel** [comment]
Noticed this style seems to be missing from linodes landing > List view

**Comment by patthiel** [comment]
Same note for stackscripts landing

**Comment by patthiel** [comment]
And images landing

**Pull request merged**
