### PR TITLE
fix: [UIE-6977] - Remove sort on region column on DBaaS landing page

### PR DESCRIPTION
**Pull request by corya-akamai**
## Description 📝
Temporarily remove sorting on "Region" column due to API error 400 Bad request. Once the backend is fixed we can add back sorting on "Region" column. All other columns can be sorted without API error.

## Changes  🔄
List any change relevant to the reviewer.
- Change TableSortCell to TableCell on Region column

### Reproduction steps
- Navigate to https://cloud.linode.com/databases and click on the "Region" column to sort.
- To unblock go to https://cloud.linode.com/profile/settings?preferenceEditor=true
and remove "databases-order" from sort keys

### Verification steps 
- Navigate to https://cloud.linode.com/databases the "Region" column is no longer sortable.

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [x] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by coliu-akamai — APPROVED** [review]
Looks good! Confirmed region column no longer sortable. 🎉 

+1 to Alban's suggestion for a `// TODO ....` comment!

**Comment by corya-akamai** [comment]
> Looks good - @corya-akamai I assume you'll keep track of re-adding this later on. A TODO may help.
Added a TODO

**Comment by bnussman-akamai** [comment]
Is the plan to hot fix this? Include in our next release (11/13/2023)? What's the status of the API fix, if any?

**Comment by corya-akamai** [comment]
> Is the plan to hotfix this? Include in our next release (11/13/2023)? What's the status of the API fix, if any?

It can go in the next release 11/13/2023. There's not ETA on API yet. DBaaS team is going to discuss with Carissa on the fix.

**Comment by bnussman-akamai** [comment]
Thank you! @corya-akamai

**Pull request merged**
