### PR TITLE
M3-444 Show progress bar for Linode Snapshots

### PR DESCRIPTION
**Pull request by asauber**
- Make Linode progress bar visible on every tab on the details page
- Show progress bar based on "transition actions" as well as "transition statuses"
- Make snapshotting a "transition action"

### CODE REVIEW

**Comment by martinmckenna** [comment]
2 things that I thought I would mention, but I'm not sure if this is preventing this from getting merged

1. Do we want to display the Linode's status as 'Busy' during a snapshot being taken?
2. When the snapshot gets to 100%, it technically isn't done until a few moments after (making a request `/backups` will still show the backup under `in_progress`, so the user cannot make snapshots back-to-back. Is this something we want to convey once the snapshot reaches 100%?

**Comment by asauber** [comment]
@martinmckenna 

1. We should. Power actions aren't possible while snapshotting.
2. I don't think it's good UX to show a progress bar stuck at 100% for potentially hours (for large backups that need post processing), but we should surface this state somehow. I'm going to add an annotation to the backup label in the table: snaplabel (in post processing).

**Comment by asauber** [comment]
@martinmckenna I addressed #1, as for #2 I addressed it in the below commit, but then reverted, because there's nothing that would trigger it to update, simply confusing the user.

https://github.com/linode/manager/pull/3471/commits/508adf3863b97d1ed2c338925c8ca980a0522c57

**Comment by rjstires** [comment]
This works about as far as we can get it without API intervention. The user is left in a state where the backup has been created, but is in post-processing. Since we receive no events to indicate work is being done, we cannot convey that to the user.

@jamesottinger @Dorthu

**Comment by asauber** [comment]
@rjstires updated

**Comment by rjstires** [comment]
LGTM, just needs to be brought up to date.

**Pull request merged**
