### PR TITLE
[CMR] M3-4520: Linode status details

### PR DESCRIPTION
**Pull request by tiffwong**
## Description
If the Linode status is not "Running" or "Offline", it will open the `NotificationDrawer` when a user clicks on the status. I also fixed the message that shows up as "Shutting_down" at the end of the powering off action 

## Type of Change
- Non breaking change ('update', 'change')

## Note to Reviewers
Added a mock linode with an event to make it easier to trigger the `NotificationDrawer`

### CODE REVIEW

**Review by johnwcallahan — CHANGES_REQUESTED** [review]
Great work, this does what we want.

One change requested: you have a NotificationDrawer rendered for every row here, which could be costly performance wise if there are a lot of Linode rows. Better to hoist a single drawer up to a higher component and pass the handlers down to the rows so they can open the drawer.

**Review by WilkinsKa1 — APPROVED** [review]
Looks good! For the grid/details view, wondering if the status pill should trigger the drawer opening same as the link in the table?

**Review by johnwcallahan — APPROVED** [review]
Adjustments look much better 👍 

The status changes don't carry over for grid view or the details view, but that can be addressed separately: 

Screen Shot 2020-09-14 at 4 03 55 PM

**Comment by tiffwong** [comment]
@WilkinsKa1 @johnwcallahan thanks for your feedback! I'll open a separate ticket to apply the changes to the grid/card view

**Pull request merged**
