### PR TITLE
test: [M3-7123] - Cypress integration test for edit subnet flow

### PR DESCRIPTION
**Pull request by coliu-akamai**
## Description 📝
- added a test for the edit subnet flow

## How to test 🧪
Verify that tests pass: `yarn cy:run -s "cypress/e2e/core/vpc/vpc-details-page.spec.ts"`

### CODE REVIEW

**Comment by carrillo-erik** [comment]
I was able to verify that all 4 e2e test passed on my machine after running your PR locally  ✅

Screenshot 2023-09-28 at 7 33 45 AM

**Review by carrillo-erik — APPROVED** [review]

**Comment by carrillo-erik** [comment]
Do we need to include a changeset for this?

**Review by jdamore-linode — APPROVED** [review]
This is excellent, great work @coliu-akamai!

**Comment by coliu-akamai** [comment]
Thanks Erik and Joe!

@carrillo-erik - I looked at other prs for tests, and they don't seem to include changesets for the tests themselves, so I didn't include one here. Will double check though!

**Pull request merged**
