### PR TITLE
Fix sandbox usage

### PR DESCRIPTION
**Pull request by eatonphil**

### CODE REVIEW

**Comment by eatonphil** [comment]
Actually there are a few more places using sinon directly. I only grepped for `sinon.stub`. There are 3 more files grepping for `sinon.spy`, so just a second.

**Comment by eatonphil** [comment]
:(

**Comment by SirCmpwn** [comment]
:<

**Comment by eatonphil** [comment]
Just a second then. I'll put up another with the last two files.

**Pull request merged**
