### PR TITLE
Release v1.84.0

### PR DESCRIPTION
**Pull request by cpathipa**
### Added:
- Jan 2023 Marketplace Apps
- Type-to-confirm to more destructive actions

### Changed:
- Standardized usage of dismissible banners and notices
- Aligned left modal title
- Standardized `Disk IO` -> `Disk I/O` formatting across app

### Fixed:
- Linodes Landing Extra Padding
- Broken URL for Peppermint Marketplace App

## How to test 🧪

- Test Banners and notices
- Test all core functionalities

**How do I run relevant unit or e2e tests?**

- yarn cy:run

### CODE REVIEW

**Review by bnussman-akamai — COMMENTED** [review]
I think the all white logo for Apache Airflow is not named correctly, maybe the capitalization in the file name is throwing it off? 

Screen Shot 2023-01-23 at 10 10 49 AM

**Comment by bnussman-akamai** [comment]
@hana-linode Oh interesting. Running locally it does not 404, but using our internal preview link, the image 404s. I'm not sure how this will translate to `staging`

**Comment by dwiley-akamai** [comment]
I'm still testing the app but the Apache Airflow logo looks fine on my end also:

Screen Shot 2023-01-23 at 10 32 05 AM

**Comment by cpathipa** [comment]
Apache Airflow log is working for my end as well..
image

**Review by bnussman-akamai — APPROVED** [review]

**Review by jdamore-linode — APPROVED** [review]
Looks good, also confirmed e2e tests pass

**Review by hana-linode — APPROVED** [review]

**Pull request merged**
