### PR TITLE
Updated linode card and row views

### LINKED ISSUE #153: Increase font size?

### LINKED ISSUE #587: Make cards a little more responsive

### LINKED ISSUE #597: Get rid of commas in ips list on card, row, and linode dashboard views

### LINKED ISSUE #598: Put flag first before datacenter name

### LINKED ISSUE #635: Implement updated card/row view

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #587, closes #598, closes #635, closes #597, closes #153

screen shot 2016-11-03 at 5 54 32 pm
screen shot 2016-11-03 at 5 54 46 pm

### CODE REVIEW

**Comment by eatonphil** [comment]
Colors aside, thoughts on these?

screen shot 2016-11-04 at 2 39 27 pm
screen shot 2016-11-04 at 2 39 45 pm

**Comment by eatonphil** [comment]
screen shot 2016-11-04 at 2 51 26 pm

**Comment by eatonphil** [comment]
And using the ellipsis icon:

screen shot 2016-11-04 at 2 55 05 pm

**Comment by eatonphil** [comment]
Final update:

screen shot 2016-11-04 at 3 16 00 pm

**Comment by briansteffens** [comment]
I prefer the arrow over the ellipsis. Maybe if the ellipsis was rotated 90 degrees or if the dots were wider like a hamburger icon it would work better.

**Comment by briansteffens** [comment]
+1 to new header on the cards, much cleaner looking imo (even with the extra information about uptime)

**Comment by eatonphil** [comment]
@briansteffens for your viewing pleasure:

screen shot 2016-11-04 at 3 49 16 pm

**Pull request merged**
