### PR TITLE
fix: [M3-8773] - Duplicate punctuation on `image_upload` event message

### PR DESCRIPTION
**Pull request by bnussman-akamai**
## Description 📝

- Removes the `.` we add after the API event message for Image Upload events to fix duplicate punctuation 🔧 

## Preview 📷

| Before  | After   |
| ------- | ------- |
| Screenshot 2024-10-23 at 8 20 43 AM  | Screenshot 2024-10-23 at 8 31 28 AM |

## How to test 🧪

- Begin uploading an image
- Cancel the upload
- Delete the Image related to the canceled upload
- Observe the toast notification 👁️

https://github.com/user-attachments/assets/ef0b0237-129a-46ce-9ef1-db484caae589

## As an Author I have considered 🤔

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by abailly-akamai — APPROVED** [review]
Thanks @bnussman-akamai 

The faux bold on your screenshot is indicating the global CSS isn't picked up by the `<strong />` tag in safari? Are you seeing this consistently?

Private User Image

**Comment by bnussman-akamai** [comment]
Yeah, the Safari bolding issue still exists when using `<strong />` and I think also `<b />` too 🥲  @abailly-akamai

**Comment by bnussman-akamai** [comment]
That would be great, thank you @abailly-akamai

**Review by mjac0bs — APPROVED** [review]
Thanks for fixing! Confirmed the rest of the `image` messages in this file look good as well.

**Pull request merged**
