### PR TITLE
add / change array types to be more specific

### LINKED ISSUE #2014: docs array types should denote what type array elements are
for example

`array` > `[Filter]` or something along those lines

see jsdoc syntax for ideas

### PR DESCRIPTION
**Pull request by abemassry**
closes #2014

### CODE REVIEW

**Comment by eatonphil** [comment]
Capitalizing array but not capitalizing the rest of the types? (Personally I'd prefer the types to be capitalized). Also, we should put 'object' anywhere...

**Comment by eatonphil** [comment]
Also, we can probably calculate that a type is an array type because it has nested things to show? Then we could say something like `Array[${child.type}]`, no?

**Comment by eatonphil** [comment]
Oh nevermind, that's only sometimes the case.

**Comment by mparke** [comment]
saw abe fix, just needs to be committed and pushed

**Comment by eatonphil** [comment]
LGTM but next time please just use `_.capitalize` instead of upper-casing these all by hand.

**Pull request merged**
