### PR TITLE
add info block to intro page for PAT generation

### LINKED ISSUE #1868: review docs getting started copy
Getting Started sections need copy review

### LINKED ISSUE #2063: Rewrite docs intro

### PR DESCRIPTION
**Pull request by abemassry**
closes #1868 
closes #2063 

image

### CODE REVIEW

**Comment by mparke** [comment]
Tested and looks good, minor adjustments made for manager info alerts: https://github.com/abemassry/manager/pull/24

@abemassry

**Comment by eatonphil** [comment]
Personally, I'd really prefer we left these alert changes alone (both color and size).

**Comment by mparke** [comment]
@eatonphil are we introducing a change that has a negative impact in some way? re: color, blue is pretty common for non-warning, non-error states. We could maybe improve the text contrast

**Comment by eatonphil** [comment]
I'm just saying I would personally prefer we not make the color / size change. I put some work into how they were before because I did not feel the Bootstrap default fit our L/F.

**Pull request merged**
