### PR TITLE
Upgrade to Cypress 12

### PR DESCRIPTION
**Pull request by jdamore-linode**
## Description 📝

**What does this PR do?**
Upgrades Cypress and related dependencies for Cypress 12. For more information about what's new in Cypress 12, check out the [Cypress changelog page](https://docs.cypress.io/guides/references/changelog).

This also makes some changes to our tests:

- Fixes some issues where multiple elements were being selected when Cypress expected one; this used to be acceptable with previous versions of Cypress but causes an error in Cypress 12
- Changes some interactions around action menus, primarily to address potential flakiness
- Changes to element selection for the security questions test, also to reduce flakiness

## How to test 🧪

**How do I run relevant unit or e2e tests?**
Run `yarn dev`, then separately run the E2E tests:

```bash
yarn cy:run
```

### CODE REVIEW

**Review by bnussman-akamai — APPROVED** [review]
I did not run the entire suite of tests, but saw ✅ on all of the ones I ran! Nice job staying on top of the latest versions!

**Review by hana-linode — COMMENTED** [review]
All E2E tests passed for me except "creates a volume from an existing Linode" in `volumes/create-volume.spec.ts`. However, on the develop branch that test is passing 🤔

**Comment by jdamore-linode** [comment]
> All E2E tests passed for me except "creates a volume from an existing Linode" in `volumes/create-volume.spec.ts`. However, on the develop branch that test is passing 🤔

Hey @hana-linode, sorry for the slow follow up! Do you remember if this test was failing consistently for you? I haven't been able to reproduce any failure in `create-volume.spec.ts` yet so I'm wondering if the failure you observed may have been some kind of fluke

**Review by hana-linode — APPROVED** [review]
@jdamore-linode It was failing consistently before but I just ran the E2E tests again and this time it passed. Something unrelated to this upgrade must have been causing the failure. A different E2E test is failing now that wasn't before (`resize-linode.spec.ts`) but it's probably just a fluke so going to approve ✅

**Pull request merged**
