### PR TITLE
feat: [M3-8837] - Add LKE-E feature flag

### PR DESCRIPTION
**Pull request by mjac0bs**
## Description 📝

We will need a feature flag in Launch Darkly to gate access to the UI changes for LKE-Enterprise. 

## Changes  🔄

- The `lkeEnterprise` flag exists in Launch Darkly.
   - The flag is EVERYTHING OFF in staging and prod environments and Feature ON, LA ON, GA OFF in the dev environment.
- The flag is added to the dev tools feature flag list.
- An account preset is added to the MSW to mock the capability.
- `useIsLkeEnterpriseEnabled` hook handles the enablement of the feature.
   - Since there is an account capability to enable the feature, the necessary account beta endpoint updates are included.
   - Test coverage was added for this hook.

### Prerequisites

(How to setup test environment)

- Have the LKE-E customer tag on your account (prod account is fine). See the internal LKE-Enterprise project tracker to find this.
OR
- Do not add the LKE-E customer tag on your account and use the MSW preset instead. (Thanks Joe)
Screenshot 2024-11-18 at 12 44 47 PM

### Verification steps

(How to verify changes)

- [ ] Read the diff since there are no UI changes yet.
- [ ] Ensure that unit test coverage passes:
```
yarn test kubeUtils
```
- [ ] Confirm that the LKE-E feature flag is present in dev tools.
- [ ] If you want to test the hook in code, manually add the hook to a page like `KubernetesLanding.tsx`, console.log the return value, and confirm you see a v4beta/account network request.
```
  const { isLkeEnterpriseLAEnabled } = useIsLkeEnterpriseEnabled();
  console.log({ isLkeEnterpriseLAEnabled });
```

## As an Author, I have considered 🤔

- 👀 Doing a self review
- ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- 🤏 Splitting feature into small PRs
- ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- 🧪 Providing/improving test coverage
- 🔐 Removing all sensitive information from the code and PR description
- 🚩 Using a feature flag to protect the release
- 👣 Providing comprehensive reproduction steps
- 📑 Providing or updating our documentation
- 🕛 Scheduling a pair reviewing session
- 📱 Providing mobile support
- ♿  Providing accessibility support

<br/>

- [x] I have read and considered all applicable items listed above.

## As an Author, before moving this PR from Draft to Open, I confirmed ✅

- [x] All unit tests are passing
- [x] TypeScript compilation succeeded without errors
- [x] Code passes all linting rules

### CODE REVIEW

**Comment by jdamore-linode** [comment]
> Have the LKE-E customer tag on your account (prod account is fine). See the internal LKE-Enterprise project tracker to find this.

Any thoughts about adding a Mock Service Worker preset for this? Doesn't help too much now since there aren't any UI changes, but might be handy once development ramps up a bit more.

I took a quick stab at a preset (that does the absolute bare minimum, there's probably a lot of room for improvement):

```typescript
// New file at `src/mocks/presets/extra/account/lkeEnterpriseEnabled.ts` or similar

import { http } from 'msw';
import {
  accountFactory,
} from 'src/factories';
import { makeResponse } from 'src/mocks/utilities/response';

import type { MockPresetExtra } from 'src/mocks/types';

const mockLkeEnabledCapability = () => {
  return [
    http.get('*/v4*/account', async ({ request }) => {
      return makeResponse(
        accountFactory.build({
          capabilities: [
            // Other account capabilities might be necessary here, too...
            // TODO Make a `defaultAccountCapabilities` factory.
            'Kubernetes',
            'Kubernetes Enterprise',
          ],
        })
      );
    }),
  ]
};

export const lkeEnterpriseEnabledPreset: MockPresetExtra = {
  desc: 'Mock account with LKE Enterprise capability',
  group: { id: 'Account', type: 'select' },
  handlers: [mockLkeEnabledCapability],
  id: 'account:lke-enterprise-enabled',
  label: 'LKE Enterprise Enabled',
};

```
(And then there are some accompanying changes required to the `MockPresetExtraId` type in `src/mocks/types.ts`, and the preset needs to be added to the `extraMockPresets` array in `src/mocks/presets/index.ts` to get it to show up in the dev tools)

**Review by jdamore-linode — APPROVED** [review]
Thanks @mjac0bs!

**Comment by mjac0bs** [comment]
I'm going to stick this back in Draft for now after talking about RQ and cache management with Banks. (relevant comments [here](https://github.com/linode/manager/pull/11207#issuecomment-2457467693) and [here](https://github.com/linode/manager/pull/10968#discussion_r1805015842)

(Thanks for your comments, Joe. MSW preset is a good idea.)

**Comment by mjac0bs** [comment]
Putting this back up for review with some updates:
- The LKE-E API folks report that they used `v4beta/account` to be cautious; after discussion, it seems more likely this will become `v4/account`
- Until then, we are opting to use a separate beta query and query key *because* regular and beta endpoint caches don't really need to be in sync. The purpose of the cached beta endpoint is to read the `capabilities` only. While not very DRY, beta-specific query and cache seems less risky than [updating the cache logic](https://github.com/linode/manager/pull/11207/files#diff-9fe16b4e86dc963b779071391448b45668e789b1bdf3a38d3d1e97448d8e9940R150-R158) for the existing query, as we needed to with `/clusters`.
- @jdamore-linode Added a preset for LKE-Enterprise Enabled! I think this, and the ability to dynamically mock capabilities in general, could be useful to improve in the future, for sure. Some of the devs have discussed this in office hours before. Let's work with what you suggested for now.

**Review by bnussman-akamai — APPROVED** [review]

**Review by jdamore-linode — APPROVED** [review]
Thanks @mjac0bs!

**Pull request merged**
