### PR TITLE
changed: [M3-7663] - Remove unified migrations feature flag

### PR DESCRIPTION
**Pull request by jaalah-akamai**
## Description 📝
Removed the Unified Migrations feature flag since the feature has been released.

## Changes  🔄
- Removed feature flag in E2E and Linode Resize
- Added loading state to submit button

### Verification steps 
(How to verify changes)
- Attempt to resize a linode
- Observe resize panel is still showing
- Observe warm resizes still work

### CODE REVIEW

**Review by bnussman-akamai — APPROVED** [review]
Nice clean up 🧼

I didn't notice that the `Auto Resize Disk` has some weird behavior when re-opening the Dialog. Should I create a ticket for that?


https://github.com/linode/manager/assets/115251059/0afaf5d8-8d3f-4cae-b717-3606dba36e1f

**Comment by bnussman-akamai** [comment]
Also, noticed that the `Resize Linode` button at the bottom of the Dialog does not have a loading state.

**Comment by jaalah-akamai** [comment]
> Also, noticed that the Resize Linode button at the bottom of the Dialog does not have a loading state.

Thanks, fixed this... not sure why we had the code written the way it was. 👍

**Comment by jaalah-akamai** [comment]
> I didn't notice that the Auto Resize Disk has some weird behavior when re-opening the Dialog. Should I create a ticket for that?

Let's create a separate ticket - thanks for noticing

**Comment by bnussman-akamai** [comment]
Created M3-7669

**Review by mjac0bs — APPROVED** [review]
Thanks for the feature flag clean up! Our list has gotten lengthy again.
✅ Warm migrations still work
✅ Flag is gone from devtools list
✅ e2es still pass

This copy is coming from API, isn't it? There's a typo. ☹️ Should be `its previous state` not `it's` (it is).
Screenshot 2024-01-18 at 2 17 22 PM

**Comment by jaalah-akamai** [comment]
> This copy is coming from API, isn't it? There's a typo. ☹️ Should be its previous state not it's (it is).

I will forward to API 🦅 👁️ 🔍

**Pull request merged**
