### PR TITLE
Feedback extractor

### LINKED ISSUE #570: Feedback extractor

### LINKED ISSUE #601: Drop "Hide  >" text from notifications sidebar

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #570 

Also includes some cleanup of the notifications sidebar as I saw better ways to do that. Closes #601 

screen shot 2016-10-28 at 4 56 02 pm

### CODE REVIEW

**Comment by eatonphil** [comment]
Tests to come.

**Comment by eatonphil** [comment]
Tests passing, feedback test to come.

**Comment by na3d** [comment]
You know that the API will ignore the email address, right?  So that field might need to be disabled, so that people don't try to edit it.

**Comment by eatonphil** [comment]
thanks! If we change our minds about requiring email then fine. For now I'd prefer it to be user-discretion.

**Pull request merged**
