### PR TITLE
M3-5071: Drag & Drop Image uploads

### PR DESCRIPTION
**Pull request by DevDW**
## Description
Implement functionality to allow users to drag and drop Images to upload from the "Upload Images" tab.

Display the (feature flagged) copy regarding Images pricing on the "Capture Image" and "Upload Image" tabs.

## Note to Reviewers
If you need files to use for testing, reach out and I will provide a link.

Things to test here would include:
- enabled/disabled states 
- successful and unsuccessful drops
- attempting to navigate away from the page mid-upload and ensuring the expected behavior happens when you choose to stay on the page or navigate away from the page
- confirming that you are not redirected to login due to authentication expiration while an upload is in progress
- ...and the overall flow and experience as a user related to all of the above.

### CODE REVIEW

**Comment by bnussman** [comment]
Looks like the copyable text here needs to be styles for dark mode

**Comment by bnussman** [comment]
In dark mode, the `Browse Files` button appears active even though the required fields have not been filled in. 

Screen Shot 2021-06-07 at 1 20 28 PM

**Review by tiffwong — COMMENTED** [review]
Functionality works great!

A couple things I noticed:

There's some extra margin on the left and right of the dropzone when the viewport width is < 900px

Screen Shot 2021-06-08 at 2 54 08 PM

The "Browse Files" button disappears after a failed upload

Screen Shot 2021-06-08 at 11 24 43 AM

**Review by bnussman — APPROVED** [review]
Looks good to me after changes from the review 🚢

**Review by tiffwong — APPROVED** [review]
Looks great!

Not a blocker but there's some extra padding below the dropzone when an image is uploading
Screen Shot 2021-06-14 at 3 01 49 PM
Screen Shot 2021-06-14 at 3 01 42 PM

**Review by HanaXu — APPROVED** [review]
LGTM! Just one comment.

This is a non-blocker, but idk how I feel about the dark mode loading bar color. It doesn't really match the rest of the app, which uses lighter blue colors.

Screen Shot 2021-06-14 at 2 24 15 PM

**Pull request merged**
