### PR TITLE
M3-5358: Allow more room for image names

### PR DESCRIPTION
**Pull request by bcmertz**
## Description

This PR increases the width of the linode image name width

## How to test

Clone branch and view images under /images

N/A No relevant unit tests - small styling change only

## Notes

ImagesLanding.tsx: "widthPercent" before only added up to 100 in the case of tableType=='automatic' and flagEnabled==true headers being passed in. 

This PR has the side effect of making the width percents not add up to 100 in this case but the way components/EntityTable/EntityTableHeaders.tsx presents the width to the TableCell doesn't seem to have a 100% sum requirement. Perhaps it's OK to ignore this since we do in most other instances, and making the ratios change to sum to 100% is kinda unwieldily?

### CODE REVIEW

**Review by DevDW — COMMENTED** [review]
Nice, this works but I think we can do a bit more to tighten things up in this file and simplify the styling logic.

Machine Images is now in General Availability (GA), so we can address those `@todo`'s in the file and remove the second parameter from `getHeaders`.

Because the action menu column is always collapsed with no inline action outside of one case (if I'm not mistaken), we don't need it taking up 35% of the total row width; decreasing it to maybe 15% seems fine. And then maybe 20% each for "Created" and "Expires".

**Review by tiffwong — APPROVED** [review]
Looks good! Approving based on the changes Dajahi recommended

**Comment by bcmertz** [comment]
Thanks for the feedback @tiffwong  and @DevDW ! I made the changes, apologies for the delay :)

**Review by DevDW — APPROVED** [review]
🎉  🚀

**Pull request merged**
