### PR TITLE
Add linode filtering

### LINKED ISSUE #2260: Add filtering to Linodes list

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #2260

### CODE REVIEW

**Comment by mparke** [comment]
is the checked state fix-able?

screen shot 2017-07-13 at 4 06 33 pm

**Comment by eatonphil** [comment]
@mparke that's being fixed in the nodebalancer filtering PR.

**Comment by na3d** [comment]
Looks good.

**Comment by eatonphil** [comment]
thank you!

**Pull request merged**
