### PR TITLE
M3-1910 MUI regression from Update

### PR DESCRIPTION
**Pull request by alioso**
This PR fixes regression with few components since the MUI update. It gets rid of console warnings for future deprecations and safer update process going forwards:
- Fix buttons variants
- Fix tabs variants 
- Summary panel markup (typography was wrapping divs rendering improper markup hierarchy)
- Tooltip styles have been re-applied

### CODE REVIEW

**Comment by Jskobos** [comment]
Getting this on /account: W`arning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by SummaryPanel)`

**Comment by Jskobos** [comment]
Not sure if it's related to this PR, but this looks pretty tiny

screen shot 2018-11-28 at 2 36 23 pm

**Comment by nwisnewski** [comment]
I encountered the console warning Jared mentioned as well. Along with the safari kabob issue i sent to you. Other than those 2 issues things look good on all supported browsers, taking a quick pass at some mobile visual regression now.

**Comment by alioso** [comment]
@nwisnewski @Jskobos addressed both issues - thanks for the eagle eyes!

**Pull request merged**
