### PR TITLE
M3-4566 CMR Action menu refinements

### PR DESCRIPTION
**Pull request by WilkinsKa1**
## Description

More action menu refinements from Jay: 
• Updating styles for focus/hover states on the inline actions on details landing/details
• Removing 'View Backups' and 'Settings' actions from all Linode action menu variants
• Making 'Reboot' second action (after power on/off, before launch console for all variants)- when reviewing please note we only display 'Reboot' on powered on Linodes.

## Type of Change
- Non breaking change ('update')

### CODE REVIEW

**Review by DevDW — APPROVED** [review]

**Review by johnwcallahan — APPROVED** [review]
Looks good. Related, there's still something strange with the "Reboot" icon in the Details Header. Seems like there's a quick animation after hover (when leaving the element). Reproduced on Chrome and FF.

**Comment by tiffwong** [comment]
> Looks good. Related, there's still something strange with the "Reboot" icon in the Details Header. Seems like there's a quick animation after hover (when leaving the element). Reproduced on Chrome and FF.

I fixed that in [https://github.com/linode/manager/pull/6912](https://github.com/linode/manager/pull/6912)

**Review by tiffwong — APPROVED** [review]
Everything looks good other than the quick animation on reboot that John mentioned!

**Comment by WilkinsKa1** [comment]
Good find, @johnwcallahan ! I removed the transitions.

**Pull request merged**
