### PR TITLE
M3-5714: Generate Jest coverage report via GitHub Actions

### PR DESCRIPTION
**Pull request by DevDW**
## Description
Generate a Jest coverage report when running the CI workflow via GitHub Actions and save it as an artifact.

### CODE REVIEW

**Comment by bnussman** [comment]
Really neat! I noticed that it seemed to add 15 min to the `test-manager` stage of CI which is a bit unfortunate, but not a big deal for now imo

**Comment by DevDW** [comment]
> Really neat! I noticed that it seemed to add 15 min to the `test-manager` stage of CI which is a bit unfortunate, but not a big deal for now imo

I'll look into seeing if we can shorten that time, but one big issue with the initial attempt was the size of the artifact (70+ MB) because it took all the contents of `packages/manager` and spit it out in the artifact. Going to see if the previous commit makes any difference on that front, but once that's sorted I'll circle back to the time considerations

**Comment by DevDW** [comment]
Looks like this adds anywhere from 6-9 minutes to how long the checks take to complete. The artifact also comes in at just under 8 MB.

**Comment by jdamore-linode** [comment]
I think this is a valid tradeoff -- there aren't a lot of cases where we're anxiously waiting for GHA to finish, and if it does end up becoming a burden we can reevaluate.

**Review by bnussman — COMMENTED** [review]
Nice job! I see the coverage artifact! Is there an easy way to consume and view the json? Did we explore outputting html?

**Comment by DevDW** [comment]
> Nice job! I see the coverage artifact! Is there an easy way to consume and view the json? Did we explore outputting html?

Thanks! I could be wrong, but I don't think we can get HTML output easily -- I don't see a flag for it in https://jestjs.io/docs/cli. I tried it manually just in case it was valid but undocumented and the command (`yarn workspace linode-manager run test --coverage --outputFile=coverage_report.html --html`) failed

**Comment by jdamore-linode** [comment]
> > Nice job! I see the coverage artifact! Is there an easy way to consume and view the json? Did we explore outputting html?
> 
> Thanks! I could be wrong, but I don't think we can get HTML output easily -- I don't see a flag for it in https://jestjs.io/docs/cli. I tried it manually just in case it was valid but undocumented and the command (`yarn workspace linode-manager run test --coverage --outputFile=coverage_report.html --html`) failed

There is an HTML report which is pretty nice, but it includes hundreds (thousands?) of small files and stacks up to around 30MB. It gets generated at `packages/manager/coverage/lcov-report` if you run `yarn test --coverage`, but I don't know how to generate _only_ the HTML report.

**Review by bnussman — APPROVED** [review]
Approving because it works, but I'd like to know how we're gonna utilize this data!

**Comment by jdamore-linode** [comment]
Perhaps we can export it as JUnit XML and use something like [JUnit Report Action](https://github.com/marketplace/actions/junit-report-action)?

**Comment by DevDW** [comment]
I was initially thinking the "Resource not accessible by integration" error was related to the `lcov.info` file being in a directory ignored by git, but the error looks to be permissions-related at the GHA integration level: https://www.google.com/search?q=%22Resource+not+accessible+by+integration%22+jest+site%3Agithub.com

Going to continue investigating but this may present a problem:

> Pull requests from public forks are still considered a special case and will receive a read token regardless of these settings.
(from https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/)

**Pull request closed without merging**
