### PR TITLE
Visual bug with Object Storage Browse Files button (dark theme)

### PR DESCRIPTION
**Pull request by WilkinsKa1**
## Description

Adjustments to some dark theme colors for the 'browse' button on OBJ Details and some of the file icons- also added some fixes to appease the a11y linter. 

## Type of Change
- Bug fix ('fix')

### CODE REVIEW

**Review by Jskobos — COMMENTED** [review]
This fixes the bug. On my monitor the button overflows the footer a bit, not sure if that's a thing universally.

Screen Shot 2020-11-04 at 8 21 46 AM

**Comment by tiffwong** [comment]
> This fixes the bug. On my monitor the button overflows the footer a bit, not sure if that's a thing universally.
> 
> Screen Shot 2020-11-04 at 8 21 46 AM

This is happening universally for desktops since it's subtracting the same amount from 100% of the viewport height, decreasing the height of the container (aka increasing the amount we subtract from the viewport) should solve it though

**Review by tiffwong — APPROVED** [review]
Other than the button overlapping with the footer that Jared mentioned which actually exists on develop, everything else looks good!

**Review by DevDW — APPROVED** [review]
The overlap issue appears to be solved and the rest looks good as well 🚢

**Pull request merged**
