### PR TITLE
refactor: [M3-8080] - Linode Create Refactor - Add API/CLI Modal

### PR DESCRIPTION
**Pull request by bnussman-akamai**
## Description 📝

- Adds the "Create using Command Line" button to the new Linode Create flow 🎉 

## Preview 📷

Screenshot 2024-05-06 at 4 15 35 PM

### Prerequisites
- Enable the `Linode Create v2` feature flag using local dev tools

### Verification steps
- Verify you see the `Create Using Command Line` button at the bottom of the new Linode Create flow
- Verify the create using command line works as expected and opens the dialog with the correct information 📄

## As an Author I have considered 🤔

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by jaalah-akamai — APPROVED** [review]
✅ CLI works - was able to create a linode with both curl and linode cli

**Comment by hana-linode** [comment]
It looks like VPC isn't supported 🤔 

| This branch  | Prod  |
| ------- | ------- |
| image | image |
| image | image |

**Comment by bnussman-akamai** [comment]
VPC issue is fixed ✅  @hana-linode

**Comment by hana-linode** [comment]
@bnussman looks like something is off with the metadata encoding

https://www.base64decode.org/

| This branch  | Prod  |
| ------- | ------- |
| image | image |

**Comment by bnussman-akamai** [comment]
@hana-linode  should be fixed by c4c52fe

**Review by hana-linode — APPROVED** [review]

**Pull request merged**
