### PR TITLE
test: [M3-8434] - Cypress integration test for Object Storage Gen2: E2 Endpoint

### PR DESCRIPTION
**Pull request by jaalah-akamai**
## Changes  🔄
- New Integration Test for Object Storage Gen2: E2 Endpoint - Bucket Creation

## Target release date 🗓️
N/A

## How to test 🧪
- `yarn cy:run -s "cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts"`

## As an Author I have considered 🤔
*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [x] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Comment by jaalah-akamai** [comment]
@linode/frontend-sdet QQ: Should this be called a smoke test since we're using mock data?

**Comment by jdamore-linode** [comment]
> @linode/frontend-sdet QQ: Should this be called a smoke test since we're using mock data?

Nah -- despite all the files prefixed with `smoke-`, we really don't have proper smoke tests and I'd rename the specs if there wasn't a risk of it screwing up our Cypress Cloud metrics. These are full blown integration tests 👍.

**Review by AzureLatte — APPROVED** [review]
Test passed

**Review by coliu-akamai — APPROVED** [review]
✅ confirmed test passed! 🎉 

don't forget the changeset

**Pull request merged**
