### PR TITLE
M3-434 Glish

### PR DESCRIPTION
**Pull request by asauber**
- Rename and refactor Weblish component to "Lish" component
- Refactor Weblish route to `/lish/weblish` and add Glish route `/lish/glish`
- Add tabs to Lish component, driven by the active route
- Render Weblish CSS only within the Weblish container
- Dynamically change window size for Weblish and Glish
- Add Glish and Glish types
- Add Error State to Glish when Linode is Powered Off
- Automatically reconnect when linode is Powered-On

Instructions for testing graphical environment:

1. Create a Linode in a region close to you using Debian as the base image
2. Log in to the Linode using this Glish interface
3. `apt-get update`
4. `apt-get install -y gnome` (this will take a while)
5. `adduser <username>` (follow the prompts to add a non-privileged user)
6. Reboot the Linode
7. Visit this Glish interface again
8. You should be presented with the Gnome login interface
9. Log-in, right click on the desktop, choose "Display Settings", click the default display, and increase the resolution to 1920x1080

Please test powering on/off the Linode while using Glish, as those cases should be handled.

Error State:
screen shot 2018-07-06 at 5 44 14 pm

1024x768 Terminal on Glish:
screen shot 2018-07-06 at 12 05 08 pm

Gnome running on Debian:
screen shot 2018-07-06 at 5 42 53 pm

XFCE running on Arch at 1920x1080:
screen shot 2018-07-06 at 5 37 19 pm

### CODE REVIEW

**Comment by rjstires** [comment]
@asauber might be worth your while to just recreate https://github.com/mozilla-frontend-infra/react-vnc-display/blob/master/src/components/VncDisplay.js in `src/` rather than dealing the minification issues.

**Comment by asauber** [comment]
@rjstires That's the plan

**Comment by Jskobos** [comment]
I get some console errors if I leave the connection open for a few minutes without doing anything. Once or twice in this case I also ended up with an endless loading spinner, but can't reliably reproduce. 

Reloading the page sometimes results in the "Warning: Can't call setState (or forceUpdate) on an unmounted component" message (coming from Weblish, but not clear exactly where).

screen shot 2018-07-09 at 4 33 21 pm

**Comment by asauber** [comment]
@Jskobos thanks for the review, with the above updates this shouldn't happen anymore

**Pull request merged**
