### PR TITLE
feat: [M3-7252] - Only show regions that support VPCs in VPC Create page

### PR DESCRIPTION
**Pull request by coliu-akamai**
## Description 📝
- For the VPC Create page, rather than showing all regions, we only show the regions that support VPCs in the region select
- NOTE: Hiding the disabled Tokyo region from this page as well, since 1) Tokyo doesn't support VPCs yet, and 2)  the tooltip for disabled Tokyo region mentions using the Osaka region instead, but Osaka also doesn't support VPCs and doesn't show up

## Preview 📷

| Before  | After   |
| ------- | ------- |
|image |image |

### Prerequisites
- Using the dev environment, with vpc admin tags, navigate to the VPC Create page

### Verification steps 
- Verify that the region select on the VPC Create page only contains the following regions (these are the ones that have the VPC capability, based on the API return object)
  - Mumbai, India
  - Toronto, Ontario, CAN
  - Sydney, NSW, Australia
  - Newark, NJ, USA
  - London, England, UK

### Tests
- Verify that the vpc-create-spec tests pass:
yarn cy:run -s "cypress/e2e/core/vpc/vpc-create.spec.ts"

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a changeset
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [x] 👣 Providing comprehensive reproduction steps
- [x] 📑 Providing or updating our documentation
- [x] 🕛 Scheduling a pair reviewing session
- [x] 📱 Providing mobile support
- [x] ♿  Providing accessibility support

### CODE REVIEW

**Comment by jdamore-linode** [comment]
Hey Connie!

The only relevant test failure here is `vpc-create.spec.ts`. I didn't look too closely, but I'm guessing judging by the changes that the tests are tripping up since they [choose a region](https://github.com/linode/manager/blob/develop/packages/manager/cypress/e2e/core/vpc/vpc-create.spec.ts#L47) at random (also line 275), and are probably trying to create VPCs using regions that aren't in the select now.

Couple ways to fix:

- Just hardcode the region using [`getRegionById(<ID of a region we know has VPC>)`](https://github.com/linode/manager/blob/develop/packages/manager/cypress/support/util/regions.ts#L51)`
- Mock the regions request so they all contain the VPC capability

I have no real preference. To run the test locally:

`yarn && yarn build && yarn start:manager:ci`, and then
```bash
yarn cy:run -s "cypress/e2e/core/vpc/vpc-create.spec.ts"
```
(Bear in mind that it _might_ still pass as-is, if the test chooses a region that happens to have the VPC capability!)

**Review by dwiley-akamai — APPROVED** [review]
E2E test passes ✅
Only the expected regions show up as options ✅
Code LGTM ✅

**Review by hana-linode — APPROVED** [review]
Verified that only the expected regions show up and that the E2E test passed 🧹

**Review by jdamore-linode — APPROVED** [review]
Thanks for the test fix @coliu-akamai! Looks good!

**Pull request merged**
