### PR TITLE
M3-2642: Update linode graphs to respect user timezone

### PR DESCRIPTION
**Pull request by ajdeleon**
## Description

https://jira.linode.com/browse/M3-2642

Uses moment to adjust timestamps for the data that is passed into graphs. The user timezone is pulled from redux store, with a fallback to "UTC". I modeled this after how the store is accessed in formatDate.tsx which also uses the timezone, but maybe it would be better actually `connect` the component? I'm not sure.

## Type of Change
- Non breaking change ('update')

## Applicable E2E Tests

To run relevant E2E tests, run these commands in 3 separate terminals:

1. `yarn && yarn start`
2. `yarn selenium`
3. `yarn e2e --spec=COMMA_SEPARATED_LIST_OF_SPECS_HERE --browser=headlessChrome`

## Note to Reviewers

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

### CODE REVIEW

**Comment by martinmckenna** [comment]
I would also keep the LineGraph component dumb and consume the user timezone (with the connect component) in the parent and pass down the timezone as a prop to LineGraph.

**Comment by ajdeleon** [comment]
> To answer your question, usually when accessing the store from a component we connect it. The accessing logic you have works fine, though.
> 
> For me, the processed value is the same as in production no matter what I do with my timezone, and the graphs appear the same. You can try `moment.utc(point[0]).tz(userTimezone)`, or you might have to work with the underlying graphing library to get the intended result

@Jskobos Nice thanks for the info. So I took another look at this and it does work to change the dates when you hover over the graph, but the tick marks on the x axis do not change as expected. After some investigation it looks like this may be a known limitation of chartjs, but I'll keep looking into it. If that's a no go what do y'all think about adding d3 as a dependency? I'd be happy to make a more custom line graph component.

**Comment by ajdeleon** [comment]
> I would also keep the LineGraph component dumb and consume the user timezone (with the connect component) in the parent and pass down the timezone as a prop to LineGraph.

@martinmckenna Cool cool done. I had to fight a bit with typescript but the struggle at least let me know that nodebalancer charts will need to be updated as well. Should I add that in this PR or make it separate?

**Comment by martinmckenna** [comment]
@ajdeleon I would just add it in this PR

**Comment by alioso** [comment]
closed in favor of https://github.com/linode/manager/pull/4797

**Pull request closed without merging**
