### PR TITLE
fix: [M3-6931] - Fixed top spacing for NodeBalancer empty state

### PR DESCRIPTION
**Pull request by tyler-akamai**
## Description 📝
Fixed the top spacing for the NodeBalancer empty state

## Major Changes 🔄
- Added top padding to NodeBalancer empty state

## Preview 📷
</details>

<details>
<summary>Before</summary>

| Domains  | NodeBalancer   |
| ------- | ------- |
| Screenshot 2023-10-02 at 3 21 57 PM | Screenshot 2023-10-02 at 3 22 22 PM |

</details>

<details>
<summary>After</summary>

| Domains  | NodeBalancer   |
| ------- | ------- |
| Screenshot 2023-10-02 at 3 20 07 PM | Screenshot 2023-10-02 at 3 20 30 PM |

</details>

## How to test 🧪
1. Turn on MSW and ensure there are 0 active NodeBalancers
2. Navigate to http://localhost:3000/nodebalancers
3. Ensure the spacing is consistent with the other empty state pages (ex. Volumes, Domains, Kubernetes, etc.)

### CODE REVIEW

**Review by jdamore-linode — APPROVED** [review]
Looks good, thanks @tyler-akamai!

Not to suggest increasing the scope of this work, but is there a technical reason why this is the only empty landing page that doesn't use the `<ResourcesSection />` component?

**Comment by tyler-akamai** [comment]
> Looks good, thanks @tyler-akamai!
> 
> Not to suggest increasing the scope of this work, but is there a technical reason why this is the only empty landing page that doesn't use the `<ResourcesSection />` component?

Yeah I started to look into it but found that I needed to collect the different links from the documentation and ui team, and it seemed outside of the scope for this ticket. But I can create a new ticket to migrate the NodeBalancer empty state to <ResourceSection>

**Comment by jdamore-linode** [comment]
> Yeah I started to look into it but found that I needed to collect the different links from the documentation and ui team, and it seemed outside of the scope for this ticket. But I can create a new ticket to migrate the NodeBalancer empty state to `<ResourceSection /> `

Makes sense! A separate ticket sounds good to me. Thanks again @tyler-akamai!

**Comment by mjac0bs** [comment]
> is there a technical reason why this is the only empty landing page that doesn't use the `<ResourcesSection />` component?

@jdamore-linode I _think_ this is because the `<ResourcesSection/>` component was [added back in May](https://github.com/linode/manager/pull/9078), amidst a series of updates to landing pages that didn't already have resource links on them. ([List of PRs here](https://github.com/linode/manager/pulls?q=is%3Apr+update+empty+state+is%3Aclosed+label%3A%22Update+empty+landing+states%22)). NodeBalancer landing links look like they were last updated 3 years ago, so they already existed at that time and therefore the empty state landing page probably wasn't considered as part of those updates.

++ to @tyler-akamai for a separate ticket.

**Review by cpathipa — APPROVED** [review]
LGTM! confirming NodeBalancer top spacing is consistent with other landing pages Volumes, kubernetes  and Domains

**Comment by bnussman-akamai** [comment]
Looks better but I wonder if it makes sense to go ahead and refactor this to use `<ResourcesSection />` like all of our other Empty states?

**Pull request merged**
