### PR TITLE
creating support ticket e2e

### PR DESCRIPTION
**Pull request by ndukatz**
**How to verify that that the test works:**
- yarn up
- yarn cy:debug
- Choose open-support-ticket.spec.ts in the cypress test runner
- Test should pass

**Extra check (runs headless):**
- yarn cy:e2e -s ./cypress/integration/help & support/open-support-ticket.spec.ts
- Result should be "✔  All specs passed!"

Make sure your .env contains:
REACT_APP_LOGIN_ROOT='https://login.linode.com'
REACT_APP_API_ROOT='https://api.linode.com/v4'
REACT_APP_APP_ROOT='http://localhost:3000'
REACT_APP_LAUNCH_DARKLY_ID='*************************' (CMR flag)
REACT_APP_CLIENT_ID='********************' (https://cloud.linode.com/profile/clients, copy ID)
MANAGER_OAUTH='**************************************************************************' 
(create in https://cloud.linode.com/profile/tokens > "Add a Person Access Token", Save the token that appears in the modal, you will only see it once)

### CODE REVIEW

**Comment by ndukatz** [comment]
Tickets don't get cleaned up currently. There was no way to do that. but support did say they are fine just closing out tickets that are named cy-test ticket. Not sure if that's the way we want to go or not though

**Review by acourdavault — APPROVED** [review]
lgtm

**Review by johnwcallahan — CHANGES_REQUESTED** [review]
The tests look good, but IMO it's not acceptable that they result in open support tickets. Let's talk offline to find a solution; otherwise we'll need to wait on this one.

**Comment by johnwcallahan** [comment]
Closing this out in favor of https://github.com/linode/manager/pull/6976.

**Pull request closed without merging**
