### PR TITLE
change from module-eval-source-map to source-map

### PR DESCRIPTION
**Pull request by abemassry**

### CODE REVIEW

**Comment by eatonphil** [comment]
Could you explain why?

**Comment by eatonphil** [comment]
@mparke indecisive much? https://github.com/linode/manager/pull/1126

**Comment by mparke** [comment]
yes

**Comment by eatonphil** [comment]
This is needed so we can generate source maps?

**Comment by mparke** [comment]
yes, it is slower, but I believe it provides more accurate line numbers and more detailed stack trace when debugging. 

@abemassry ?

**Comment by eatonphil** [comment]
You're right. It actually doesn't even seem to be working at all right now. 'source-map' works well.

**Pull request merged**
