### PR TITLE
Upgrade Cypress to v9.5.1

### PR DESCRIPTION
**Pull request by jdamore-linode**
## Description

**What does this PR do?**
This upgrades Cypress from 8.6.x to 9.5.1, and updates related dependencies as well.

I was hoping this might be low hanging fruit to improve the performance of our tests, but sadly performance seems to be about the same with these changes in place.

## How to test

**What are the steps to reproduce the issue or verify the changes?**
Run `yarn up` to ensure that packages are upgraded, and in a separate console run `yarn cy:run` and confirm that no failures occur. This takes between 20-25 minutes on my machine.

### CODE REVIEW

**Review by bnussman — APPROVED** [review]

**Review by DevDW — COMMENTED** [review]
I had two failures, `longview/longview.spec.ts` (timed out retrying after 300000ms) and `images/machine-image-upload.spec.ts` 🧐

**Comment by jdamore-linode** [comment]
> I had two failures, `longview/longview.spec.ts` (timed out retrying after 300000ms) and `images/machine-image-upload.spec.ts` 🧐

I'll take a look! I think we had issues with `images/machine-image-upload.spec.ts` a few weeks ago when we were having the HTTP 408 API issues... the longview one is new to me though!

**Comment by jdamore-linode** [comment]
@DevDW I ran the tests again with Cypress 9.5.x and everything passed. I'm thinking the failures you saw may have been a fluke or were related to some prod issue. Do you think you'd have a chance to re-run them some time in the next day or two?

**Review by DevDW — APPROVED** [review]
All tests passed for me when I ran it just now 👍

**Pull request merged**
