### PR TITLE
fix: [UIE-7601] - disable smaller plans

### PR DESCRIPTION
**Pull request by mpolotsk-akamai**
## Description 📝

Fixing issue with clickable disabled smaller plans in Resizing Tab

## Target release date 🗓️
Release date: 04/29/2024

## How to test 🧪

Open application, navigate to /databases, select the database cluster. Go to Resize tab, and click on one of the disabled plan. Summary section remains unchanged. 'Resize Database Cluster' button is disabled.

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Comment by carrillo-erik** [comment]
Changes look good and I was able to verify that other plans were not able to be selected as presented in the images below:
### Before
Screenshot 2024-04-17 at 10 16 32 AM
### After
Screenshot 2024-04-17 at 10 17 16 AM

Only ask if you could please include a unit test for the changes and to meet the Base Coverage criteria. Good Job.

**Review by bnussman-akamai — APPROVED** [review]

**Comment by bnussman-akamai** [comment]
Changes look good. The e2e failures in `linode-config.spec.ts` are unrelated and nothing to worry about. Merging develop in / rebasing will resolve them

**Comment by mpolotsk-akamai** [comment]
Thank you @bnussman-akamai

**Review by carrillo-erik — APPROVED** [review]
Thanks for making the changes and we appreciate your contributions ✅

**Comment by mpolotsk-akamai** [comment]
Thank you @carrillo-erik

**Pull request merged**
