### PR TITLE
Release v1.100.2 - staging → master

### PR DESCRIPTION
**Pull request by bnussman-akamai**
### Fixed:

- Extra API calls for Linode Configs ([#9609](https://github.com/linode/manager/pull/9609))

### CODE REVIEW

**Review by dwiley-akamai — APPROVED** [review]
🚀

**Review by coliu-akamai — APPROVED** [review]
Thank you!

**Review by abailly-akamai — APPROVED** [review]
No more calls 👍

**Review by jdamore-linode — APPROVED** [review]
Staging looks good! Thanks @bnussman-akamai !

**Pull request merged**
