### PR TITLE
upcoming: [DI-20555] - Added Alert tab and General Information components for Create Alert Definition form

### PR DESCRIPTION
**Pull request by santoshp210**
## Description 📝
Added Alert tab under Monitor for the alerting services features. Added General Information components for Create Alert Definition flow

## Changes  🔄
List any change relevant to the reviewer.
- Added Alerts tab under Monitor which is visible when at least one flag of the sub-tabs is accessible(via feature flag)
- Added Recent activity, Alert Definitions, Notification channels tabs under Alert and the tabs visible only when they're accessible through feature flags
- Added a Create button for the Create Alert Definition form under Alert Definitions
- Added the General Information components under the create alert definition flow

## Target release date 🗓️
Please specify a release date to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| Screenshot 2024-09-04 at 14 47 05 | Screenshot 2024-09-04 at 14 41 17 Screenshot 2024-09-04 at 14 42 18 |

## How to test 🧪
- Switch to mock user as APIs are not live and for the feature flags(Legacy MSW handlers)
- The Create Alert definition form is rendered after clicking on the Create button under Alert definition

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [x] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Comment by mjac0bs** [comment]
@santoshp210 This PR is very large with a diff of over 1200 lines. It includes multiple new components, new queries and types, and validation changes. Can you please break this down before we give it a more thorough review?

**Comment by santoshp210** [comment]
@mjac0bs Understood, but this is already a divided portion of the feature. Can I get an idea of how smaller to split this part ? Should we handle validation, types and requests, components separately or logical chunks of the code with few components and their relevant types, requests and validation.

**Comment by mjac0bs** [comment]
> Can I get an idea of how smaller to split this part ? Should we handle validation, types and requests, components separately or logical chunks of the code with few components and their relevant types, requests and validation.

@santoshp210 Sure - either are reasonable approaches, but the second option, breaking things down into logical chunks, tends to provide more context surrounding the changes. In turn, this makes it easier to test and review. A reasonable-sized diff is a [max of about 500 lines](https://linode.github.io/manager/CONTRIBUTING.html#sizing-a-pull-request).

**Comment by santoshp210** [comment]
Okay sure, I will discuss this with the team and will take action at the earliest. Thank you!

**Comment by santoshp210** [comment]
@mjac0bs , Yeah we will split it into two. So we'll raise a new pr with the appropriate changes . This pr then will be closed ?

**Comment by mjac0bs** [comment]
@santoshp210 We can close this one since it doesn't have any in progress reviews. 👍🏼 Thanks for breaking the changes down.

**Pull request closed without merging**
