### PR TITLE
Fix #12

### LINKED ISSUE #12: Username is not stored in localStorage alongside OAuth token
* [ ] Username for linode/layouts/LinodeGeneral

### PR DESCRIPTION
**Pull request by SirCmpwn**
This persists your username and email to localstorage along with your
OAuth token.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
:shipit:

**Comment by eatonphil** [comment]
Cool. ready for merge?

**Comment by SirCmpwn** [comment]
Yes. That is what :shipit: means.

**Comment by eatonphil** [comment]
Ah.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
