### PR TITLE
Misc css fixes

### LINKED ISSUE #1513: Hook up images in support ticket views

### LINKED ISSUE #1533: Fix card heights to make them equal

### LINKED ISSUE #1862: Support Page load bar disappears/reapears
When I click on the Support link, the green horizontal page load indicator starts, gets about 30% across the page, then completely disappears to reappear a second or two later from the beginning. At that point the page successfully loads.

### LINKED ISSUE #1912: Slave SOA should show all master and transfer ips not just first

### PR DESCRIPTION
**Pull request by eatonphil**
* Remove [title] attribute underline and special cursor
* Replace Linode dropdown arrow with a cog
* Make text-muted lighter (in particular for increased contrast between ipv4 and ipv6)
* Make Linode dashboard Summary and Access sections same height, closes #1533  
* Make Rescue page Rescue and Reset root password sections same height
* Replace card margin-bottom with section margin-bottom so more pages and gave footer padding-top so more pages automatically get padding above footer
* Increase modal and card L/R padding
* Increase modal width to 600px standardizing with login's modals
* Make PreloadIndicator last up to 30 seconds instead of 4 seconds to bear with longer page loads, closes #1862
* Add ' Zone' prefix to zone type column in Domains list to make it clearer what "Slave" and "Master" mean
* Shows all master and transfer ips instead of just one, closes #1912  
* Add ' Ticket' prefix to ticket id column in Support ticket list to make it clearer what the number is
* Hide first support ticket card if description is empty
* Added page source and title to ticket page
* Rename 'Source' link in footer to 'Page Source' for clarity and link to source including current version for more accuracy, closes https://github.com/linode/manager/issues/1921
* Increases contrast between group and label on main pages
* Adds support ticket user image, closes #1513

TODO:
* [x] Final check of all pages for no extra footer padding
* [x] Fix tests

### CODE REVIEW

**Comment by mparke** [comment]
> Add ' Ticket' prefix to ticket id column in Support ticket list to make it clearer what the number is

We should add the column headers here yes?

**Comment by mparke** [comment]
> Replace Linode dropdown arrow with a cog

I thought the desired result would be that the whole dropdown be clickable should it remain a dropdown of actions, otherwise icons for actions is okay, yea?

**Comment by na3d** [comment]
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `TableCell`. It was passed a child from SlaveZone.

**Comment by eatonphil** [comment]
Ah, that's fair. Thanks @na3d will add that to my slave zone rendering change.

**Comment by eatonphil** [comment]
Done, @na3d

**Comment by eatonphil** [comment]
screen shot 2017-05-31 at 10 42 02 am

**Comment by eatonphil** [comment]
thanks!

**Pull request merged**
