### PR TITLE
Label lengths and tooltips

### LINKED ISSUE #1830: Ticket overflow on Domains on SOA record
screen shot 2017-05-19 at 3 33 09 pm

### LINKED ISSUE #1873: elipsis on really long text in table cells
check `th` widths first, consider a default max length for all label cells
alternative: also check word-break

this addresses already known issues with cutoff text

### PR DESCRIPTION
**Pull request by mparke**
closes #1830 
closes #1873 

Image examples:

screen shot 2017-06-12 at 2 40 18 pm
screen shot 2017-06-12 at 2 40 23 pm
screen shot 2017-06-12 at 2 40 28 pm
screen shot 2017-06-12 at 2 40 31 pm
screen shot 2017-06-12 at 2 40 37 pm
screen shot 2017-06-12 at 2 40 40 pm
screen shot 2017-06-12 at 2 40 49 pm
screen shot 2017-06-12 at 2 40 53 pm
screen shot 2017-06-12 at 2 40 57 pm

### CODE REVIEW

**Comment by mparke** [comment]
delay added to show ( so there is no flicker when moving cursor across page )

**Comment by mparke** [comment]
delay on hide ( so that you can hover tooltip itself and it will stick while you double click text or id )

**Comment by abemassry** [comment]
found this on Domain zones page
image

**Comment by mparke** [comment]
@abemassry domains issue should be fixed. 

the horizontal scroll and header text (also an issue in master) is set to be handled outside of this PR: https://github.com/linode/manager/issues/1993

**Comment by eatonphil** [comment]
Card Header titles also need to be addressed. But it's fine to handle that separately if you'd like.

**Comment by mparke** [comment]
@eatonphil support tickets updated to allow for summary lengths, can add tooltips as needed at a later time.

screen shot 2017-06-13 at 1 49 32 pm

Page headers and card headers, as mentioned above, can be addressed after this. #1993

**Pull request merged**
