### PR TITLE
Update Linode Index page with Labels

### LINKED ISSUE #327: Adjust the layout of the linode card
phil insert screenshot here

### PR DESCRIPTION
**Pull request by na3d**
Closes #327
screen shot 2016-08-10 at 11 01 46 am

### CODE REVIEW

**Comment by na3d** [comment]
Lighter grey text:
screen shot 2016-08-10 at 11 26 15 am

**Comment by na3d** [comment]
Other affected pages by text color change:
screen shot 2016-08-10 at 11 30 42 am
screen shot 2016-08-10 at 11 31 12 am
screen shot 2016-08-10 at 11 31 26 am

**Comment by eatonphil** [comment]
👍

**Comment by eatonphil** [comment]
👍

**Pull request merged**
