### PR TITLE
Add help text to boot helpers in add/edit config

### LINKED ISSUE #836: Add help text to boot helpers in add/edit config

### PR DESCRIPTION
**Pull request by na3d**
Closes #836

### CODE REVIEW

**Comment by eatonphil** [comment]
Screenshot?

**Comment by na3d** [comment]
Followed the look of the alerts page, looks to be the best solution.
screen shot 2017-01-09 at 1 49 53 pm

**Comment by eatonphil** [comment]
Perfect -- except for the more info link. But fine for now.

**Comment by na3d** [comment]
Yeah, I felt it left more to be desired as well, but since we use this tactic in multiple places, I figure it will probably be redone and these turned into components.

**Pull request merged**
