### PR TITLE
Adds changelog for release and link to mailing list

### PR DESCRIPTION
**Pull request by Dorthu**

### CODE REVIEW

**Comment by Dorthu** [comment]
This is what the mailing list link looks like: 

screen shot 2017-12-07 at 11 04 42 am

**Comment by howdiz** [comment]
This is good but maybe we could reword it along the lines of

> 
Please review the changelogs and subscribe to the mailing list for updates on changes and releases

**Comment by Dorthu** [comment]
Updated text:

screen shot 2017-12-07 at 11 22 19 am

**Comment by rjstires** [comment]
@Dorthu is this waiting on approval from someone?

**Pull request merged**
