### PR TITLE
DBAAS1-76: Add Databases icon to primary nav

### PR DESCRIPTION
**Pull request by bcmertz**
## Description

- Adds Databases icon to the Primary nav and updates the icon
- Updates Databases icon

## How to test

This is hidden behind a feature flag

### CODE REVIEW

**Comment by bnussman** [comment]
The icon looks a bit too dark when its grey and it does not turn green when it is active 🥺😰

https://user-images.githubusercontent.com/6440455/147135363-5bad5da6-393a-4ada-a27e-4be8787e1112.mov

**Comment by bcmertz** [comment]
> 



> The icon looks a bit too dark when it's grey and it does not turn green when it is active 🥺😰
> 
>  Screen.Recording.2021-12-22.at.12.57.02.PM.mov

Fixed! Just some messed up svg coloring

**Review by bnussman — APPROVED** [review]
Nice job fixing up the colors! Looks great!

This may be out of the scope of this PR but we should look into making the background of the landing icon an actual circle
Screen Shot 2021-12-23 at 11 13 01 AM

**Review by HanaXu — COMMENTED** [review]
Looks like there's extra top margin making the circle an oval

image

**Comment by bcmertz** [comment]
Removed!

**Review by HanaXu — APPROVED** [review]

**Pull request merged**
