### PR TITLE
show current plan on resize page

### PR DESCRIPTION
**Pull request by TheSchwa**
First time working with React, so no idea if I kept everything sane within that framework, but it works! Let me know what doesn't make sense or if I'm going about this the wrong way.

### CODE REVIEW

**Comment by eatonphil** [comment]
Hmm. This should already be indicated by the fact that it is the selected plan when you visit this page.

**Comment by TheSchwa** [comment]
Currently, once the user selects a different plant, there's nothing to indicate what the original plan was. If they change selection, go do something else, and come back I think it's good to have an indicator for it.

**Comment by eatonphil** [comment]
The future of this page as it is is sketchy. So I'd prefer a more future-proof way of demonstrating the current plan along the lines of this mockup from a while ago: https://github.com/linode/manager/issues/608. I'd add a FormGroup above the plan display that indicates the current plan with text or a disabled input field (like we do on Edit Disk modal).

**Comment by mparke** [comment]
while future may include changes to this layout, this is a nice improvement until we redesign and make those changes.

Also, denoting current in the head is practical for the user, where placing this separately above requires the user to read what is current, and then go look for the matching plan.

+1 to this change with minor changes to active state

**Comment by eatonphil** [comment]
> Also, denoting current in the head is practical for the user, where placing this separately above requires the user to read what is current, and then go look for the matching plan.

Having one place to look at to figure out what your current plan seems a whole lot easier to find than having to scan through all of them just to find a one-word change.

**Comment by mparke** [comment]
@TheSchwa: @eatonphil and me were just discussing, and up top in one place may actually make more sense, as shown in #608. Do you mind updating?

**Comment by TheSchwa** [comment]
Sounds fine to me, although I'm inclined to leave the current plan header bolded (along with removing " - Current" and adding a blurb at the top ala #608). I'll probably have to poke around React briefly so probably get to it this afternoon.

**Comment by TheSchwa** [comment]
Ah meant to include a screenshot

screen shot 2017-06-08 at 9 26 37 am

**Comment by TheSchwa** [comment]
Waiting for #2423 to merge then will close this, as that PR includes these changes.

**Comment by TheSchwa** [comment]
#2423 merged, closing

**Comment by eatonphil** [comment]
Thank you!

**Pull request closed without merging**
