### PR TITLE
M3-5505: [DOCS] Automate developers site changlog PR

### PR DESCRIPTION
**Pull request by CodyFinn-Akamai**
## Description 📝

Automates the creation of PRs against linode developers repo for package changelogs.

## How to test 🧪

1. Open a terminal to the root of the project repo
2. run `scripts/publish_changelog.sh <PACKAGE_NAME>`
replace `<PACKAGE_NAME>` with `manager`, `api-v4`, or `validation` 
3. Check the success message for the location of the generated file
4. Ensure generated file is properly formatted and has the correct content.

### CODE REVIEW

**Review by mjac0bs — COMMENTED** [review]
This is cool! The script worked for me -- I generated all 3 changelogs. The one thing that confused me slightly (but maybe it's plenty intuitive to others) was that the file name for the `api-v4` package changelog didn't start with/include "api-v4" and so I overlooked it when searching the `/tmp` dir. Eventually realized it was `js-client-version-v0-81-0.md`.

**Comment by CodyFinn-Akamai** [comment]
> This is cool! The script worked for me -- I generated all 3 changelogs. The one thing that confused me slightly (but maybe it's plenty intuitive to others) was that the file name for the `api-v4` package changelog didn't start with/include "api-v4" and so I overlooked it when searching the `/tmp` dir. Eventually realized it was `js-client-version-v0-81-0.md`.

The naming scheme is taken from previous changelog entries already in the repo. Also the script now prompts the user for the location of the developers repo and puts the files in there for them. Removing the friction of trying to find the files in the tmp dir

**Comment by mjac0bs** [comment]
> The naming scheme is taken from previous changelog entries already in the repo. 

Makes sense.

> Also the script now prompts the user for the location of the developers repo and puts the files in there for them. Removing the friction of trying to find the files in the tmp dir

I like the ease of finding things in the `changelog` dir of the developer's repo. When running the script now, though, I ended up with the error output `scripts/publish_changelog.sh:136: no such file or directory: The upstream repo is not git@github.com:linode/developers/src/content/changelog/validation-changelog-0-16-0.md`. This happened after I put in the path to my cloned repo (which I just copied from `pwd`, since I was already at the base of the repo to run the script). Are my git settings just unexpectedly weird?

**Comment by mjac0bs** [comment]
With the correct repo set up, this now works for me. 👍  From a user experience perspective, it might be nice to have a success message once the script has generated the file, as simple as `Changelog generated successfully at: [path to the output in the developers repo]`.

**Review by dwiley-akamai — APPROVED** [review]

**Pull request merged**
