### PR TITLE
Fixed styles for the Markdown Accordion of the Ticket modal

### PR DESCRIPTION
**Pull request by bnussman**
## Description

I think #7765 caused a minor regression (shown in screenshot). 

Screen Shot 2021-07-23 at 11 42 06 AM

## How to test

- Go to `/support/tickets` 
- Click **Open New Ticket**
- Check styles of the `Formatting Tips` accordion

### CODE REVIEW

**Review by HanaXu — COMMENTED** [review]
This is what it looks like on prod right now; personally I prefer this bg over the other two (the #444 in this modal is used for inputs, but the formatting tips isn't really an input):

image

We may also want to point this to staging as well so that this will be fixed along with https://github.com/linode/manager/pull/7781

**Review by tiffwong — COMMENTED** [review]
Thanks for catching this! Regarding the bg color, I also agree with Hana. Could you also add a bit more spacing between the accordion header and the content? 

Screen Shot 2021-07-23 at 2 00 50 PM

**Review by tiffwong — DISMISSED** [review]
Great job!

**Review by codyfinn — DISMISSED** [review]

**Review by HanaXu — COMMENTED** [review]
Can we make the background for the example boxes the same as prod as well?

image

**Review by HanaXu — COMMENTED** [review]
Ack, the styles are off in a lot of other places in the app now :pensive: 

image

**Comment by bnussman** [comment]
Ok, maybe fixed that now @HanaXu

**Review by HanaXu — APPROVED** [review]
LGTM! 🎉 🎉 🎉

**Review by tiffwong — APPROVED** [review]

**Pull request merged**
