### PR TITLE
refactor: [M3-6268] - MUI migrate Help

### PR DESCRIPTION
**Pull request by carrillo-erik**
## Description 📝
MUI v5 for features -> `Help`

## Major Changes 🔄
- Ran `tss-react` codemod on `Help`
- Replaced `default export`s with `named export`s.

## How to test 🧪
1. **How to setup test environment?**
2. **How to reproduce the issue (if applicable)?**
3. **How to verify changes?**
4. **How to run Unit or E2E tests?**

### CODE REVIEW

**Comment by bnussman** [comment]
Please add a chageset to your PR 🥺🚨

**Comment by abailly-akamai** [comment]
@carrillo-erik we mentioned wanting to hold on on features. I have a PR that probably will conflict with this one

**Comment by carrillo-erik** [comment]
@abailly-akamai There's also some issues with some of the tests which I believe are tied to the PR that Joe will merge once he returns to the office. And then I wanted to get some eyes on this to get some feedback since I refactored some Class-based components to Function-based components.

I'm open to discussing any conflicts between our work before advancing with any additional development on this PR.

**Comment by abailly-akamai** [comment]
@carrillo-erik Sounds good - I'd recommend wither putting this in draft or starting over when we move to the last portion or MUI refactors (features). As you see now there are lots of conflicts already

**Pull request closed without merging**
