### PR TITLE
upcoming: [M3-7602] -  Improve AGLB Configuration - Add Certificate Drawer (revision 2)

### PR DESCRIPTION
**Pull request by bnussman-akamai**
## Description 📝
- Updates the AGLB "Add Certificate Drawer" based on alpha tester feedback and collaboration with UX

## Changes  🔄
- Main Changes
  - Changes wording of _Apply_ to _Add_ when referring to adding a certificate to a HTTPS configuration ✏️
  - Removes the ability to add many certificates at once to a Configuration at once. The drawer now just allows you to add one certificate at a time ❌
  - Allows user to `Add Existing Certificate` or `Add New Certificate` on the configurations tab for HTTPS configurations 🆕
- Extra Bonus Changes
  - Adds missing loading state to the create certificate drawer 🔄
  - Adds cancel button to create certificate drawer for completeness and consistency 

## Preview 📷

| Before  | After   |
| ------- | ------- |
| Screenshot 2024-01-16 at 11 09 53 AM | Screenshot 2024-01-16 at 11 09 36 AM |

### Prerequisites
- Use the dev environment
- Login to the `dev-test-aglb` account

### Verification steps 
- Go to http://localhost:3000/loadbalancers/13/configurations
- On any HTTPS configuration, test the new drawer by clicking `Add Certificate`
  - Verify you can add an existing certificate
  - Verify you can remove a cert from a configuration
  - Verify you can create a new certificate from within the "Add Certificate" drawer
  - If you need a TLS Certificate to test with, ask me in Slack!

## As an Author I have considered 🤔

- [ ] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [x] 👣 Providing comprehensive reproduction steps
- [x] 📑 Providing or updating our documentation
- [x] 🕛 Scheduling a pair reviewing session
- [x] 📱 Providing mobile support
- [x] ♿  Providing accessibility support

### CODE REVIEW

**Comment by bnussman-akamai** [comment]
> can we extend the tooltip width so we don't wrap the sentence so much?

To do this properly, I think it would require some changes in our TextField. Going to leave as is for now until we can improve this globally. 

> I would put this in a separate component

Because these components are closely knit, simple, and won't be reused, I think they can remain in the same file.

> For the sake of differentiating this mode from the many other Mode types, can we name it according to what it refers to?

Because this type isn't exported and has clear context does it need to be more specific than `Mode`?

> Are staying away from the "required" word in labels

I think in cases where all fields are required, the actual `Required` label isn't recommended to be used by UX

> Do we want to validate other things than required? the cert and key formats?

I think we could do this later. There are lots of unknowns and I think it's best to trust the API's validation for now

**Comment by abailly-akamai** [comment]
That's a lot of punting - would be nice to get code comments & TODOs about those decisions so you or (more importantly) someone else can get back to them when needed.

> Because these components are closely knit, simple, and won't be reused, I think they can remain in the same file
This is about readability. Take it or leave it I guess.

> I think in cases where all fields are required, the actual Required label isn't recommended to be used by UX
we should not assume. maybe that's a good cafe topic cause i think we're pretty inconsistent

**Comment by bnussman-akamai** [comment]
> we should not assume. maybe that's a good cafe topic cause i think we're pretty inconsistent

Sorry, I should rephrase. I know that UX has told us that we don't need to stick "(Required)" to every TextField in a from if all the fields are required.

**Review by abailly-akamai — APPROVED** [review]

**Review by cpathipa — APPROVED** [review]
LGTM!

**Pull request merged**
