### PR TITLE
Linode List Landing Adjustments

### PR DESCRIPTION
**Pull request by WilkinsKa1**
## Description

Removing tags column from Linode list (table) landing view and removing status filter functionality (the status counters will be static now)

## Type of Change
- Non breaking change ('update')

### CODE REVIEW

**Review by Jskobos — APPROVED** [review]
Parting is such sweet sorrow.

Is there a reason you're leaving all the plumbing in place (commented out)? I'd say delete it all unless there's a concrete plan to add tags back in somewhere else.

**Review by johnwcallahan — COMMENTED** [review]
Looks pretty clean. 

Is mobile view in scope of this PR? Looks a little funky right now:
Screen Shot 2020-11-24 at 1 29 33 PM

**Comment by WilkinsKa1** [comment]
Removed the commented code @Jskobos ! @johnwcallahan I made some minor modifications so it doesn't look as wonky- cc @tiffwong I made changes to entity header here, I know you're working through details variant and these inform each other, so noting this will also need to be checked when our work merges.

**Review by tiffwong — APPROVED** [review]
YASSSSSSSSSSS 🎉

**Pull request merged**
