### PR TITLE
change th to cubes for icon to more accurately reflect text

### PR DESCRIPTION
**Pull request by abemassry**
Before:
screen shot 2016-08-23 at 4 20 25 pm

After:
screen shot 2016-08-23 at 4 20 32 pm

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Can we get this to use a Linode L instead?

**Comment by eatonphil** [comment]
The cubes are cuter.

**Comment by SirCmpwn** [comment]
That's not the Linode L :/

**Comment by eatonphil** [comment]
I'm not a graphic designer :/

**Comment by eatonphil** [comment]
+1 for the cubes

**Comment by SirCmpwn** [comment]
I meant literally using a greyscale version of our logo. There's an SVG around somewhere

**Comment by eatonphil** [comment]
If someone stumbles on it, sure. In the meantime, this cleans up that icon so we can reuse it in login instead.

**Comment by SirCmpwn** [comment]
[Stumbled upon](https://github.com/linode/manager/blob/master/assets/linode-logo.svg)

**Comment by eatonphil** [comment]
Can you rip off the linode title and replace the green with white?

**Comment by SirCmpwn** [comment]
Tomorrow, sure.

**Comment by eatonphil** [comment]
nice

**Comment by na3d** [comment]
Yeah, I am sure Rob has an EPS file we can use.

**Comment by SirCmpwn** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/9806

**Pull request merged**
