### PR TITLE
fix: [M3-7521 & M3-7556 & M3-7581] - Update AGLB Service Target Validation & Fix Route Rules being cleared

### PR DESCRIPTION
**Pull request by bnussman-akamai**
## Description 📝

Makes three major changes
- M3-7521
  - Make our client side validation for Service Targets match the API's validation
- M3-7556
  - Fixes Route rules being cleared
- M3-7581
  - Removes ability to toggle Service Target health checks based on discussion with Mark and Daniel
- Other
  - Removes `host` option from a Rule `match_type`

## Changes  🔄
- Fixes route rules bring cleared when trying to update a route
- Make Service Target forms hide errors unless the field is touched
- Updates Service Target validation to match 
```
healthcheck.host is a mandatory parameter when using http protocol for service-target health-check.

Both healthcheck.host and healthcheck.path are not required when TCP health-check is used.
```

## Preview 📷

| Before  | After   |
| ------- | ------- |
| Screenshot 2023-12-21 at 10 11 52 AM |  Screenshot 2023-12-21 at 10 28 16 AM  |

### Prerequisites
- Login to `dev-test-aglb` in the dev environment

#### Service Target Validation
- Go to http://localhost:3000/loadbalancers/21/service-targets
- Verify you can create a Service Target and that the validation explained above holds true
  - ⚠️ There is an API bug causing Service Targets with a TCP Health Check Protocol to not be creatable
- Verify can you edit a service target and that the validation explained above holds true

#### Rules getting cleared bug
- Go to http://localhost:3000/loadbalancers/21/routes
- Create a route
- Add some rules
- Change the label of the route
- Refresh the page (required because we optimistic update here)
- Verify the rules you added were not deleted

## As an Author I have considered 🤔

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a changeset
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [x] 👣 Providing comprehensive reproduction steps
- [x] 📑 Providing or updating our documentation
- [x] 🕛 Scheduling a pair reviewing session
- [x] 📱 Providing mobile support
- [x] ♿  Providing accessibility support

### CODE REVIEW

**Comment by jdamore-linode** [comment]
I'm seeing a couple issues but one may be related to that API bug involving TCP host checks you mentioned in your description, and the other may have already existed:

- When creating/editing a service target and checking "TCP" under "Health Checks", nothing happens when clicking "Create Service Target". I believe this is a validation issue because no API request is being made, and if you then check the "HTTP" radio, you'll see the host field validation error is present.
  - Similarly, if you then enter a hostname, switch back to "TCP", and then submit the form, the service target gets created.
  - If you then edit the new service target, you'll see that "TCP" is correctly selected for the health check, but the hostname does persist if you click the "HTTPS" radio button -- kind of unexpected behavior from a UX standpoint (and probably caused/handled by the API rather than us)

- If you delete a service target, and then click "Create Service Target", the drawer title/submit button are displayed as if you're editing the service target that was just deleted (i.e. the title is "Edit <deleted target label>", the submit button is "Save Service Target"). I know this one may not be caused by this PR but just wanted to point it out

**Comment by bnussman-akamai** [comment]
@jdamore-linode 

> When creating/editing a service target and checking "TCP" under "Health Checks", nothing happens when clicking "Create Service Target"

This is caused by an API bug and will be resolved by API PR #5930! An API request should occur. An API error is not being surfaced in the UI because the API error `field` is not correct.

> If you delete a service target, and then click "Create Service Target", the drawer title/submit button are displayed as if you're editing

Fixed in 561d8f8

I will re-assess the other things you mentioned when we get this PR and the API PR merged!

**Comment by jdamore-linode** [comment]
> I will re-assess the other things you mentioned when we get this PR and the API PR merged!

Thanks Banks!

> An API request should occur. An API error is not being surfaced in the UI because the API error field is not correct.

I may be misunderstanding, but just to clarify, when I attempted to create a TCP host check, Cloud did _not_ make an API request -- it wasn't that the API responded with an error that wasn't surfaced, there was no request/response at all.

https://github.com/linode/manager/assets/97627410/50f94129-f288-4bd6-b57b-7a2afecfb461

On second look, it appears each submit click triggered a console error:

Screenshot 2024-01-02 at 4 43 50 PM

Screenshot 2024-01-02 at 4 44 07 PM

**Review by mjac0bs — COMMENTED** [review]
Couple things I found that feel probably outside the scope of this PR but open to however (whenever) you'd like to address:
1. `Host` doesn't look like it should be an option here any more. When I tried to create a rule using that option, I received the following error from API.
Screenshot 2024-01-02 at 1 38 20 PM
Screenshot 2024-01-02 at 1 39 01 PM
3.  When I tried to create a route routing to the *same* service target multiple times, I saw some weird behavior. The request seemed to fail and I saw the API error notice in the drawer, but the rule still appeared in the table. 
Req and response:
Screenshot 2024-01-02 at 1 35 54 PM
Screenshot 2024-01-02 at 1 36 03 PM
Viewing and editing my new rule that supposedly errored, but is visible with just one service target routed at 50%:
Screenshot 2024-01-02 at 1 36 15 PM

> M3-xxxx
Removes ability to toggle Service Target health checks based on discussion with Mark and Daniel

I use x's as placeholders too, ha. Did a ticket for this get created? Can we update the PR title and description for completeness?

Confirmed:
- I can add/edit a service target and see the health check host is a required field for HTTP protocol; validation reflects this.
- I confirmed the fix to the behavior Joe mentioned - after deleting a service target, the drawer is no longer in edit mode of the deleted service target; it's in add mode. 
- Route rules are no longer getting cleared when updating a route. 
- Health checks for service targets are now mandatory; the toggle has been removed. 

image

**Comment by bnussman-akamai** [comment]
@jdamore-linode  Should be "fixed" now. Meaning you should see the following:

https://github.com/linode/manager/assets/115251059/f485f3cb-1c23-421e-96c8-e57838ac7460

**Comment by mjac0bs** [comment]
I meant to mention this, then forgot, and want to do so before I forget again: the help tooltip on the health check Protocol field looks slightly off center (too low) vertically, if that's an easy fix. 😅 

image

**Comment by jaalah-akamai** [comment]
> the help tooltip on the health check Protocol field looks slightly off center (too low) vertically, if that's an easy fix.

I have a PR that will go up once this is merged that fixes the tooltip experience for our Textfield component. Currently focusing the icon using a keyboard causes the focus state to appear distorted/elongated.

**Review by jaalah-akamai — APPROVED** [review]
After the fixes, I created service targets, rules, and renamed the service target. Validation is working as intended for me and the rules are in place upon renaming. ✅ 

Screenshot 2024-01-03 at 9 39 18 AM

**Review by mjac0bs — APPROVED** [review]

**Pull request merged**
