### PR TITLE
M3-4799 create cluster button flickering fix

### PR DESCRIPTION
**Pull request by codyfinn**
## Description

This PR fixes the rendering issues on the Kubernetes create cluster screen for chromium based browsers. This is accomplished by removing an unused radio button that was `visually-hidden` which interacted strangely with the `EnhancedNumberInput` component.

## How to test

Open the manager in a chromium based browser and navigate to the create Kubernetes cluster screen. Shrink the browser window height enough so that the linode plan quantity selection table is just out of view. Refresh the page. Scroll down to the plan quantity selection table. All the quantity selectors should be visible and hovering over any of the fields or buttons should not cause any other field/button to disappear.

### CODE REVIEW

**Review by tiffwong — APPROVED** [review]
Woah, this is awesome! Thanks for solving the mystery of the disappearing buttons! 🕵️‍♂️ 🔍 🎉

**Review by bnussman — APPROVED** [review]
No more flickering on the create cluster page! 🎉

**Review by johnwcallahan — COMMENTED** [review]
Getting rid of the visually hidden element likely has an impact on accessibility.

**Review by tiffwong — APPROVED** [review]
I ran lighthouse and the score is the same for this branch and develop. I also checked keyboard accessibility using VoiceOver, JAWSs and NVDA which all work as expected so I don't think there should be an issue with removing the radio button

Can you remove the `role="radiogroup"` from [line 249](https://github.com/linode/manager/pull/7657/files#diff-ef9d119d258fb518fe9efe9a6e7201fdfefbde4694efb635e2fa99a174102e7bR249) though? We're not using radio buttons inside that section so I don't think we need that and it's actually lowering our score on lighthouse

**Review by johnwcallahan — APPROVED** [review]

**Pull request merged**
