### PR TITLE
fix: [M3-8748] - Markdown cheatsheet link in Support ticket interface has an expired domain

### PR DESCRIPTION
**Pull request by mjac0bs**
## Description 📝
When opening or replying to a Support ticket in Cloud Manager, the Formatting Tips expansion section currently has the following text:

You can use Markdown to format your reply. For more examples see this [Markdown cheatsheet](http://demo.showdownjs.com/)

The domain demo.showdownjs.com has expired, currently showing:
Este domínio expirou.
which [translates to](https://translate.google.com/?sl=auto&tl=en&text=Este%20dom%C3%ADnio%20expirou.&op=translate):
This domain has expired.

We should link customers to a well-reputed, valid domain. 

> [!NOTE]
> Support has suggested https://daringfireball.net/projects/markdown/syntax because this is the website of [John Gruber,](https://en.wikipedia.org/wiki/John_Gruber) the creator of Markdown. Support also noted that the presentation of information wasn't the best. I considered linking to the [CommonMark help](https://commonmark.org/help/) instead and am open to team's feedback and preference.

## Changes  🔄
- Swaps the expired domain docs link for the Markdown cheatsheet with a valid domain
- Fixed a couple linter warnings

## Target release date 🗓️
10/28

## Preview 📷

| Before  | After   |
| ------- | ------- |
|Screenshot 2024-10-15 at 9 38 53 AM | Screenshot 2024-10-15 at 9 38 28 AM |
| Screenshot 2024-10-15 at 9 39 24 AM | Screenshot 2024-10-15 at 9 39 46 AM

### Reproduction steps
(How to reproduce the issue, if applicable)
1. browse to https://cloud.linode.com/support/tickets
2. click Open New Ticket or click on an existing ticket
3. click Formatting Tips below the description box
4. click Markdown cheatsheet link

### Verification steps
1. browse to http://localhost:3000/support/tickets
2. click Open New Ticket or click on an existing ticket
3. click Formatting Tips below the description box
4. click Markdown cheatsheet link

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [x] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by hana-akamai — COMMENTED** [review]
Huh, seems like the showdown domain is back up again 🤔 
image

I like https://commonmark.org/help/ better since it feels more like a cheat sheet than https://daringfireball.net/projects/markdown/syntax

**Review by cpathipa — COMMENTED** [review]
Looks like `CommonMark` is widely used in projects like GitHub and Reddit etc, I don't have strong opinion as longs as we have a reliable Markdown tool.

**Review by cpathipa — APPROVED** [review]

**Comment by mjac0bs** [comment]
> Huh, seems like the showdown domain is back up again 🤔

😅  So it is! 

It sounds like we've got consensus that CommonMark is a good link. I'm going to go ahead and swap showdown out with CommonMark in this PR. I think [one person](https://github.com/tivie) maintains showdown and could let the domain expire again a year from now. CommonMark, as a project maintained by multiple people to implement Markdown standards, seems less likely to leave us with an expired domain.

**Review by hana-akamai — APPROVED** [review]
🧹

**Pull request merged**
