### PR TITLE
Update MaterialUI to latest release

### PR DESCRIPTION
**Pull request by rjstires**
# DELETE YOUR NODE_MODULES AND FRESH INSTALL

## Status
- [x] Runs.
- [x] Unit tests pass.
- [X] Passes type checking.
- [x] E2E tests pass.
- [x] No console trash.
- [ ] Thoroughly vetted for bugs.

## Notes
- I've excluded tests/specs/stories from TSConfig which saves sometime on compile/recompile. IDE is still showing errors if we're violating a rule, but won't prevent the build.
- E2E tests are on fire.
- I had to remove two instances of `!important` and marked them with @todo items (search and you shall see).
- This includes an update to React and React DOM.

@alioso can you look at the following;
- [x] Expansion Panels; Headers and icons are offset on hover.
- [x] Circular Loading; There's some random circle, in the circle.

@asauber @martinmckenna @Jskobos @patthiel please jump on this and vigorously test for bugs, quirks, unexpected side effects. Any issues that are HTML/CSS specific should be added to the list above for Alban to review. Other small/simple fixes should be applied to this branch. Otherwise please make note of issues in these comments so I can fix ASAP.

### CODE REVIEW

**Comment by martinmckenna** [comment]
Gonna just dump what I find in a comment here for now.

### Console errors/warnings
* Upon going to create Linode flow
```
Warning: Material-UI: you are trying to override a style that does not exist.
Fix the `textColorPrimarySelected` key of `theme.overrides.MuiTab`.
```
* When navigating to LinodeDetail (Settings view for instance)
```
Warning: Material-UI: you are trying to override a style that does not exist.
Fix the `expandIconExpanded` key of `theme.overrides.MuiExpansionPanelSummary`.
```
```
Warning: Material-UI: you are trying to override a style that does not exist.
Fix the `textColorPrimarySelected` key of `theme.overrides.MuiTab`.
```
* Upon navigating to Create NodeBalancer
```
Warning: Material-UI: you are trying to override a style that does not exist.
Fix the `textColorPrimarySelected` key of `theme.overrides.MuiTab`.
```

### Markup/Styling Weirdness
* Checkout bar on create Linode/NodeBalancer flow out of place on mobile screen sizes
* Radio buttons turning red onClick (example: Add a new Personal Access token in the profile view)
* Kebab menu three dots onHover overlay now is a grey oval (in Profile view for example)
* Action buttons inside the Confirmation Modals need margins
* Action buttons inside Delete OAuth Client Token are in the wrong order and wrong color. The confirm button is on the right side and red.
* Expansion Panel onClick causes the icon to jump around

### Functionality Quirks
* Typing into the Token Label Drawer is SLOW (possibly not related to this update)

**Comment by asauber** [comment]
Can confirm prior comments. Here are my notes so far

- [ ] Checkboxes turn red after being checked and not being hovered upon
- [ ] Field label active style is blue, e.g. TextField label. We want black according to the comps
- [ ] ExpansionPanel header has a bunch of extra padding when expanded
- [ ] Warning: Material-UI: you are trying to override a style that does not exist. Fix the `contentExpanded` key of `theme.overrides.MuiExpansionPanelSummary`.

**Comment by asauber** [comment]
@martinmckenna This is actually how some of the ActionsPanels appear in production. This one is the confirmation dialog for deleting an OAuth Client.

screen shot 2018-06-20 at 10 28 45 am

**Comment by alioso** [comment]
@asauber @martinmckenna this specific instance was missing the actionPanel. fixed now. this is not a regression from this update

**Comment by alioso** [comment]
- [ ] MuiTabs override theme error and selected style

**Comment by alioso** [comment]
So we have some compiling warnings related to src/utilities/cssTypes.ts. All these errors are actually coming from modules in node_modules.

It is possible that the compiler is looking into these now because when of augmenting the cssType module. Seems like we could prevent the compiler from sniffing into node_modules all together?

**Comment by asauber** [comment]
Manually re-tested every feature in the app and every storybook story. This looks good to merge.

**Comment by rjstires** [comment]
`node_modules` is already ignored in tsconfig, but the definition off Properties was incorrect causing the issue. I had to install the csstypes lib (already a secondary dependency) to correctly override the type.

@asauber @alioso @Jskobos @martinmckenna @patthiel  lets get this merged today!

**Comment by patthiel** [comment]
great work everyone  👏 👏

**Pull request merged**
