### PR TITLE
Feedback: Remove redundant title from Linode Details Analytics tab

### PR DESCRIPTION
**Pull request by tiffwong**
Will address the different units for the IPv4 and IPv6 graphs in a separate PR

### CODE REVIEW

**Comment by HanaXu** [comment]
On second thought, can we move the dropdown back to the right?

**Comment by tiffwong** [comment]
@HanaXu I can but is there a specific reason why? 🤔

**Comment by HanaXu** [comment]
I feel like left alignment looks a bit more awkward than right alignment, and it seems that right alignment is the norm (in general, and also in various other places in the cloud manager)

**Review by DevDW — APPROVED** [review]
I'm fine with either placement (left or right) but I'd still vote the same way as I did in prep for the placement on the right

**Comment by tiffwong** [comment]
@HanaXu @DevDW I'll bring it up in the channel again 😂

**Comment by HanaXu** [comment]
LGTM 🎉

**Review by Jskobos — APPROVED** [review]

**Pull request merged**
