### PR TITLE
Wire backups list to the API

### LINKED ISSUE #172: Wire backups listing to the API

### PR DESCRIPTION
**Pull request by SirCmpwn**
Fixes #172

### CODE REVIEW

**Comment by SirCmpwn** [comment]
This also fixes some isues with @na3d's work from before he went on vacation.

**Comment by eatonphil** [comment]
Nice and simple. Love it.

**Comment by eatonphil** [comment]
Should I let the -.4% go here?

**Comment by SirCmpwn** [comment]
I personally don't really care but I could write tests if you ask me nicely

**Comment by SirCmpwn** [comment]
Thanks

**Pull request merged**
