### PR TITLE
Handle errors returned during the OAuth flow

### LINKED ISSUE #422: OAuth callback errors are not handled
i.e. invalid redirect URI

### PR DESCRIPTION
**Pull request by SirCmpwn**
Fixes #422

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Tests to come

**Comment by eatonphil** [comment]
Why can't this use the same 40x or 50x style we already have?

**Comment by SirCmpwn** [comment]
We don't have a status code like 40x or 50x to display on that page. I could refactor it to not show that sometimes but it seems silly. These are also developer-facing errors: they only occur if you misconfigure the OAuth client. So who cares?

**Comment by eatonphil** [comment]
From the server's perspective, this is a 40x error. The user/developer sent bad oauth info. I think we should use that and there is space there to return the real error. In general, I don't really like the idea of not caring because no one _should_ see it.

**Comment by SirCmpwn** [comment]
There's not an HTTP error, though. The server isn't returning one. We shouldn't just make one up on the client, because there isn't one. The error is provided in the query string of the URL login.linode.com redirects you to.

**Comment by SirCmpwn** [comment]
>The user/developer sent bad oauth info

No, the developer did.

**Comment by eatonphil** [comment]
Idk, I don't see the problem with conveying the idea that this is a 400 error. Even if the actual status code was a 302.

**Comment by SirCmpwn** [comment]
HTTP is not the transport for this error. I am not going to make up a 400 status code out of the blue.

**Comment by SirCmpwn** [comment]
We might as well call it a 1337 error or a 666 error or a 8008135 error.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
