### PR TITLE
test: Increase machine image upload timeout from 2 minutes to 4 minutes

### PR DESCRIPTION
**Pull request by jdamore-linode**
## Description 📝
This increases the timeout in `machine-image-upload.spec.ts` when uploading a machine image and waiting for the success toast notification. We've been seeing a lot of flake (currently our flakiest test) because it's taking longer than 2 minutes for the uploaded images to become available.

## How to test 🧪
`yarn && yarn build && yarn start:manager:ci`, and then:

```bash
yarn cy:run -s "cypress/e2e/images/machine-image-upload.spec.ts"
```

### CODE REVIEW

**Review by abailly-akamai — COMMENTED** [review]
I would argue that cypress's role here should be to test the UI, not if the request succeeded or failed. Therefore I wonder if we would be better off mocking the response and avoid adding time to our suite?

**Comment by jdamore-linode** [comment]
> I would argue that cypress's role here should be to test the UI, not if the request succeeded or failed. Therefore I wonder if we would be better off mocking the response and avoid adding time to our suite?

@abailly-akamai I was debating the same thing myself; it is a goal of ours to include end-to-end coverage when it's viable (and in some cases our e2e tests have led us to discover issues not specific to Cloud that otherwise may have -- or already had -- slipped through the cracks) but as you mention our core concern is confirming the Cloud Manager UI behaves as expected regardless of the state of the API/other services.

In some cases e2e tests really aren't viable or useful so we lean on integration tests that use mocked data (and we even have some flows that are covered by tests that use real data and other tests that use mocked data).

But I'm leaning towards using a mocked response here as well. Our 2 minute timeout has been sufficient up until now (and I'm not sure what has changed that's led to this no longer being enough), but I'm not sure I'm willing to increase the timeout to 4 minutes and beyond, since even that doesn't appear to be adequate judging by the run above.

**Comment by abailly-akamai** [comment]
@jdamore-linode mocking has my vote for this one, though I understand the role of a true e2e as you describe it. I'd be curious to discuss further the idea of also separating API testing for specific endpoints such as this one, tho I imagine the API team is already covering it? New Relic has a pretty decent tool to do that: https://newrelic.com/lp/api-testing-tools (which we may already have setup?)

**Comment by jdamore-linode** [comment]
@abailly-akamai Just tweaked this a bit by removing the e2e image upload operations and modified the portion containing the update/delete assertions to use mocked data.

I've also been looking a bit closer to image upload timeouts; I think I may have narrowed it down to a handful of regions where this is an issue and images seem to become available quickly and consistently in other regions.

I'm going to spend more time tomorrow looking into this in case it's just a fluke or my imagination, but if this is limited to a handful of regions, then A) I'll reach out to the team involved with images to let them know in case this is something that can be fixed for each affected region, and B) we may be able to bring back the e2e tests as long as we don't upload images using any of the affected regions (previously, the test chose any region at random).

**Review by abailly-akamai — APPROVED** [review]
Not sure if you're still working on this, but thanks for updating with mocks! As far as I can see this could be merged - or do you need to narrow to a region?

**Comment by jdamore-linode** [comment]
> Not sure if you're still working on this, but thanks for updating with mocks! As far as I can see this could be merged - or do you need to narrow to a region?

Sorry @abailly-akamai ! Still monitoring this issue/debating whether to merge this. This did end up being an issue specific to a couple regions which has been fixed so I'm hoping to see if the flakiness issues are resolved (it seems a lot better, but I'm not sure it's quite good enough, so I may still end up merging this 🤷‍♂️). As always, open to your thoughts on the issue!

**Pull request merged**
