### PR TITLE
M3-382 - Select Component Tests

### PR DESCRIPTION
**Pull request by patthiel**
* Adds tests for the select components
* Fixed a spelling error in the story
* Added a `data-qa` attribute for testing

### CODE REVIEW

**Comment by rjstires** [comment]
Ran it twice and failed both times.

```
╰─ yarn e2e --file src/components/Select/Select.spec.js                            ✘
yarn run v1.3.2
$ ./node_modules/.bin/wdio ./e2e/config/wdio.conf.js --file src/components/Select/Select.spec.js

FFFFFFF

0 passing (6.10s)
7 failing

1) Select Suitesuite1 should display two select boxes with labels, action text and chevron:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17

2) Select Suitesuite1 should display one enabled select:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17

3) Select Suitesuite1 should display one disabled select:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17

4) Select Suitesuite1 should display placeholder text in disabled select:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17

5) Select Suitesuite1 should display options on click:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17

6) Select Suitesuite1 should update select value on selection:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17

7) Select Suitesuite1 should not display options on click of disabled select:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by patthiel** [comment]
@rjstires  i think you ran the wrong command, try running: 

`yarn storybook:e2e --file src/components/Select/Select.spec.js`

**Comment by rjstires** [comment]
```
╰─ yarn storybook:e2e --file src/components/Select/Select.spec.js
yarn run v1.3.2
$ ./node_modules/.bin/wdio ./e2e/config/wdio.storybook.conf.js --file src/components/Select/Select.spec.js

FFFFFFF

0 passing (3.00s)
7 failing

1) Select Suitesuite1 should display two select boxes with labels, action text and chevron:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17

2) Select Suitesuite1 should display one enabled select:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17

3) Select Suitesuite1 should display one disabled select:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17

4) Select Suitesuite1 should display placeholder text in disabled select:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17

5) Select Suitesuite1 should display options on click:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17

6) Select Suitesuite1 should update select value on selection:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17

7) Select Suitesuite1 should not display options on click of disabled select:
Failed: An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at click("[data-name="Select"]") - at element("[data-name="Select"]") - click.js:12:17



error Command failed with exit code 1.
```

image

With testing `.env`.

**Comment by rjstires** [comment]
Once again, a Docker container running in the background....

```
╰─ yarn storybook:e2e --file src/components/Select/Select.spec.js       ✘
yarn run v1.3.2
$ ./node_modules/.bin/wdio ./e2e/config/wdio.storybook.conf.js --file src/components/Select/Select.spec.js

․․․․․․․

7 passing (5.90s)


✨  Done in 6.83s.
```

**Pull request merged**
