### PR TITLE
Graphs start Y at Zero

### LINKED ISSUE #1467: Make sure y-axis of graphs doesn't go below zero

### PR DESCRIPTION
**Pull request by na3d**
Closes #1467

### CODE REVIEW

**Comment by eatonphil** [comment]
Wow, that's handy...

**Comment by na3d** [comment]
That is a lot easier of a fix than the last one I found, haha.

**Comment by na3d** [comment]
Here is the code for beginAtZero:
https://github.com/chartjs/Chart.js/blob/254bd4bf86ab8dc9801c61844cd3e668e3e2090f/src/scales/scale.linearbase.js#L17-L28

**Comment by eatonphil** [comment]
Tested. Looks good.

**Pull request merged**
