### PR TITLE
Add fetch tests

### PR DESCRIPTION
**Pull request by eatonphil**
This is going to need to be rebased once #20  is merged.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Weird that coveralls thinks coverage decreased on this. Would like to see how it shakes out post-rebase.

**Comment by eatonphil** [comment]
It's because I forgot the actual spec in the first commit.

**Comment by SirCmpwn** [comment]
:+1: Ready for merge?

**Comment by SirCmpwn** [comment]
Bah will have to wait for new build first

**Comment by eatonphil** [comment]
One last refactor. I don't like _fetch.

**Comment by eatonphil** [comment]
Ready to merge.

**Comment by SirCmpwn** [comment]
Woot woot coverage

**Comment by eatonphil** [comment]
Thank you!

**Pull request merged**
