### PR TITLE
M3-179 Scroll to Top on Linode Landing

### PR DESCRIPTION
**Pull request by martinmckenna**
### Purpose

Scroll to top of page when the user switches pages on the Linode landing view

### CODE REVIEW

**Comment by asauber** [comment]
Probably not, but I have a rule to never merge code that I haven't witnessed executing.

**Comment by martinmckenna** [comment]
@everyone I'm going to fix the pagination ticket in this PR.

Please don't merge

**Comment by martinmckenna** [comment]
@rjstires @asauber @Jskobos 

Please re-review. I fixed pagination controls to compliment the `scrollToTop()`.

Feel free to login to the alpha env with user `dev-test-003`

**Comment by Jskobos** [comment]
Pagination + scrolling are working well now. But if there are more than 2 pages, when on the second page or higher the button for page 1 is not shown. (so if you're on page 2, the only way to get back to page 1 is with the back arrow. You can go directly from 1 to 3, but not directly from 3 to 1.)

**Comment by rjstires** [comment]
@Jskobos there's a ticket for that already, does not need to be addressed here.

**Pull request merged**
