### PR TITLE
upcoming: [M3-8083] - Linode Create v2 - Disk Encryption

### PR DESCRIPTION
**Pull request by bnussman-akamai**
## Description 📝

- Adds Disk Encryption to the **new** Linode Create Flow 💾 
  - Basically implements the same stuff that https://github.com/linode/manager/pull/10462 implements

## Preview 📷

Screenshot 2024-05-31 at 1 02 00 PM

### Prerequisites
- Make sure you are testing with the `Linode Create v2` feature flag **on** 🏴 
- Use dev environment

### Verification steps
- Verify Disk Encryption shows when you have the the `linode_disk_encryption` tag on your account **and** the flag is enabled
- Verify toggling the checkbox works
- Verify the checkbox is disabled if the region does not support disk encryption
- Verify you see a warning for backups when you enable both disk encryption and backups
- Verify these changes are in parity with what was done in https://github.com/linode/manager/pull/10462

### Known issues
- Disk encryption stays checked when region is changed
  - This functionality has not been implemented for Linode Create v2, it will come later 

## As an Author I have considered 🤔

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a changeset
- [x] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by dwiley-akamai — COMMENTED** [review]
Going to test a bit more on Monday, but I noticed these (I believe they stem from the known issue you listed in the description):

- the Backups notice remains when you change the region (if you previously had "Encrypt Disk" checked)
- when you change the region from one that supports LDE to one that doesn't, the payload will still have `disk_encryption: "enabled"`
- when you change the region from one that supports LDE to one that doesn't, "Encrypted" remains in the summary at the bottom of the page

**Review by abailly-akamai — COMMENTED** [review]
Code looks good!

Not sure if my comments will be pertinent to this PR, the v1 flow or both, but i noticed a some potential improvements to make to the UI/UX

The tooltip mentions the feature not being available in the selected region, but I have not selected a region yet.
Screenshot 2024-06-03 at 10 20 57

related to the first point:
Screenshot 2024-06-03 at 10 21 27

the way we treat the lack of selected region and unavailability is quite inconsistent with the way it was just done for placement groups. I wonder if it'd be a good time to reel the UX team and confirm the overall messaging. @dwiley-akamai any thoughts?

**Comment by bnussman-akamai** [comment]
I agree with all of that and noticed the same things @abailly-akamai.

I was thinking: Once we get Linode Create v2 "done", we can sync up with UX to establish consistency on those items on the new create flow.

**Comment by dwiley-akamai** [comment]
> the way we treat the lack of selected region and unavailability is quite inconsistent with the way it was just done for placement groups. I wonder if it'd be a good time to reel the UX team and confirm the overall messaging. @dwiley-akamai any thoughts?

I'd also be in favor of having UX review things comprehensively once the v2 Create flow is done. There are additional inconsistencies across the sections when an unsupported region is selected.

**Review by dwiley-akamai — APPROVED** [review]
Aside from the issues related to disk encryption staying toggled on when you change the region, things looked good from my additional testing.

Where exactly are we with the error scrolling again? This didn't scroll into view for me:

Screenshot 2024-06-03 at 11 01 22 AM

**Comment by bnussman-akamai** [comment]
@dwiley-akamai I merged develop in. Scroll into view should work now.

**Comment by abailly-akamai** [comment]
Sounds good - we should make sure to remember to update both flows when UX changes happen. thanks folks!

**Review by abailly-akamai — APPROVED** [review]

**Comment by bnussman-akamai** [comment]
I think the goal would to be only update v2 and launch it with the new UX @abailly-akamai

**Pull request merged**
