### PR TITLE
change: [M3-8384] - Update storybook to fix dependency vulnerabilities

### PR DESCRIPTION
**Pull request by abailly-akamai**
## Description 📝
Small PR to update storybook to get rid of a high severity [dependabot alert](https://github.com/linode/manager/security/dependabot/101)

This update seems to be actually pretty major for storybook authors trying to clean up dependencies, which has been an ongoing problem. Hopefully this will help in the future.

## Changes  🔄
- Update storybook and related packages to `8.2.9`

### Verification steps
- Run/build storybook locally to confirm no regression was introduced with this update

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by bnussman-akamai — APPROVED** [review]
Nice! That diff in the lockfile is very pleasant to see 🎉 


Storybook worked as expected locally ✅

**Review by jaalah-akamai — APPROVED** [review]

**Comment by jaalah-akamai** [comment]
You win for today 😆 
Screenshot 2024-08-23 at 1 35 13 PM

**Review by hana-linode — APPROVED** [review]
LGTM other than this known [storybook warning issue
](https://github.com/storybookjs/storybook/issues/28567)

Screenshot 2024-08-23 at 3 56 17 PM

**Comment by abailly-akamai** [comment]
@hana-linode yeah one fix could be to turn off the source map generation for storybook - not sure if it's that helpful. Def an issue with vite + storybook

**Comment by abailly-akamai** [comment]
fixed! https://github.com/linode/manager/security/dependabot/101

**Pull request merged**
