### PR TITLE
Resign Backups: Add sub nav and summary

### PR DESCRIPTION
**Pull request by na3d**
Closes: #489 

screen shot 2016-10-07 at 10 17 18 am
screen shot 2016-10-07 at 10 17 34 am
screen shot 2016-10-07 at 10 17 41 am

### CODE REVIEW

**Comment by eatonphil** [comment]
This view you're showing here is not the summary page though, correct? The view you are showing is a backup detail view. The summary page has four boxes to represent the four backup slots. You click on one to get to the backup detail view.

**Comment by na3d** [comment]
It is the summary page that doesn't have a snapshot yet, as that data isn't in the Linode API endpoint yet, and I want this out so more than one person can work on backups.

**Comment by na3d** [comment]
There is no backup details page, as per your design.  It is only Summary, History, and Settings pages.  I am not sure it would make sense to have both a summary and a details page, given how similar the terms are.

**Comment by na3d** [comment]
Oh, I see what you mean, um, there isn't a design for the details panel for the summary page.

**Comment by eatonphil** [comment]
Just to reiterate, this is what we've talked about as the primary Summary view.

screen shot 2016-10-10 at 10 55 16 am

Clicking on one of them (when you can click on one of them because they exist takes you to one of these pages depending on whether or not the backup is a snapshot or auto):

screen shot 2016-10-10 at 10 56 14 am
screen shot 2016-10-10 at 10 56 23 am

Sidenote: This is one of those scary views @briansteffens has mentioned where you don't know where you are because there's no breadcrumb. Maybe this should be made into a two-part modal (a first in the Linode redesign but not something new to the web). This sidenote shouldn't be a stopper for now, but just bringing it up for the sake of it not being awesome rn.

**Comment by abemassry** [comment]
More changes to be done in future PRs. 👍

**Comment by na3d** [comment]
Thank you!

**Pull request merged**
