### PR TITLE
[DO NOT MERGE] Add glish

### LINKED ISSUE #1405: Investigate / Implement glish window/UI

### PR DESCRIPTION
**Pull request by abemassry**
closes #1405 

image

### CODE REVIEW

**Comment by eatonphil** [comment]
Are there missing devServer.js changes not shown here?

**Comment by eatonphil** [comment]
Made a PR against your branch. Tested and works locally. Once you merge my PR, please rebase. No need to have these +9000 -9000 changes in the repo.

**Comment by abemassry** [comment]
@eatonphil 
> Are there missing devServer.js changes not shown here?

No

**Comment by eatonphil** [comment]
Setting DO NOT MERGE until @mparke gets a chance to look at the shrinkwrap breakage that will occur here.

**Comment by mparke** [comment]
Followup:

https://github.com/linode/manager/issues/1578

**Comment by mparke** [comment]
this is now quite behind, closing until addressed later.

**Pull request closed without merging**
