### PR TITLE
add docs linting, cleanup where needed

### LINKED ISSUE #1699: Review linter, add to components & docs

### PR DESCRIPTION
**Pull request by mparke**
closes #1699

### CODE REVIEW

**Comment by eatonphil** [comment]
This only closes the docs part of that issue though, no?

**Comment by eatonphil** [comment]
I was thinking we'd just add this directory to the list of directories we lint against in the top-level lint settings. If we're not doing that, could you add a line to the .travis.rc to run linter for docs too? `cd docs && npm run lint`

**Comment by mparke** [comment]
oops yeah, let me address /components too

**Comment by mparke** [comment]
will do re: travis.rc, kept it separate since it's treated as a separate package

**Comment by eatonphil** [comment]
Aside from missing whitespace before links in the intro sections this looks good.

**Pull request merged**
