### PR TITLE
M3-6064: Deploying a Linode Backup to a new Linode forces a different plan size to be chosen

### PR DESCRIPTION
**Pull request by cpathipa**
## Description 📝
Fixes deploying Linode from backup

## Preview 📷

https://user-images.githubusercontent.com/119517080/212214390-79e8ba56-6fbe-47f8-b4a8-b9fd5f43bdcf.mov

## How to test 🧪

- Navigate to Create Linode page
- Click backup tab
- Select Linode
- Select backup
- Click Create Linode button

**What are the steps to reproduce the issue or verify the changes?**
- Checkout to develop branch
- Navigate to Create Linode page
- Click backup tab
- Select Linode
- Select backup
- Click Create Linode button

Navigate to Create Linode page
Click backup tab
Select Linode

**How do I run relevant unit or e2e tests?**
yarn test

### CODE REVIEW

**Review by jcallahan-akamai — CHANGES_REQUESTED** [review]
This sort of fixes the issue, but the problem now is that if I select another plan type, I can't click back to the original plan type (since th
Screen Shot 2023-01-12 at 10 03 52 PM
e row is disabled).

**Comment by cpathipa** [comment]
> This sort of fixes the issue, but the problem now is that if I select another plan type, I can't click back to the original plan type (since the row is disabled). Screen Shot 2023-01-12 at 10 03 52 PM

Addressed the above use-case by  enabling the current plan row for deploying Linode from backups and clone. 

https://user-images.githubusercontent.com/119517080/212335146-f8b03e89-5a54-4073-b1e6-c6b81394c122.mov

**Review by bnussman-akamai — APPROVED** [review]
This is working as i'd expect now

**Review by CodyFinn-Akamai — DISMISSED** [review]
Works for me

**Review by jcallahan-akamai — APPROVED** [review]

**Review by CodyFinn-Akamai — APPROVED** [review]

**Pull request merged**
