### PR TITLE
refactor: [M3-8641] - Move Box component to ui package (Part 2)

### PR DESCRIPTION
**Pull request by coliu-akamai**
## Description 📝
Part 2 of moving `Box` to the `ui` package. (Since this was branched off of m3-8641, it also includes those changes - the diff will get smaller once part 1 is merged. However, if it's easier to just check for everything on this PR, rather than splitting up the PRs, I can close part 1!)

will resolve merge conflicts + clean this up after part 1 is merged in

## Changes  🔄
- Move Box to ui package
- update rest of imports
- consolidate double imports to @linode/ui to just one import, if some files were already importing from the ui package

## How to test 🧪
Make sure there's no regressions in overall styling/layout in these specific areas:
- Notification Center
- Object storage
- Placement Groups
- Profile
- Stackscripts
- Support
- Top Menu
- Users
- Volumes
- VPCs
- double check the flows mentioned in part 1 throughout rest of CM 

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by harsh-akamai — APPROVED** [review]
Code ✅ 
Box in Cloud ✅ 

Thank you for the changes!

**Review by pmakode-akamai — APPROVED** [review]
Thanks for this massive refactor @coliu-akamai 🎉 ✅

❗️Merge conflicts need to be addressed after Part 1 is merged

Apart from that, I’m thinking if we could be more organized and consistent with our components in `ui/src/components`. Instead of having the component, tests, and Storybook files dispersed throughout the /components folder, we could consolidate them within a single folder for each component unless there is only single component file. For instance, similar to the `BetaChip` structure, where the component file and its corresponding test file are kept together (although no storybook file is there). This way, it will be more organized and easier to locate related files.

**Comment by coliu-akamai** [comment]
thanks @harsh-akamai and @pmakode-akamai! just merged in part 1, so will be working on all those conflicts (so many conflicts 🥲)  and cleanup

> we could consolidate them within a single folder for each component

Agreed! I added that to [part 1](https://github.com/linode/manager/pull/11163#discussion_r1819421134), but it isn't showing up here because I didn't merge part 1 into this branch 😅 - will work on getting this branch up to date now!

**Comment by coliu-akamai** [comment]
merging - test failure is unrelated

**Pull request merged**
