### PR TITLE
Add test stubs for IndexPage

### PR DESCRIPTION
**Pull request by SirCmpwn**
Also implements one of the tests

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Working on some changes to this, do not merge

**Comment by eatonphil** [comment]
Do we just merge this or should I base off this branch?

**Comment by eatonphil** [comment]
s/merge this/merge this when you're ready/

**Comment by SirCmpwn** [comment]
Will be done shortly, just sit tight

**Comment by SirCmpwn** [comment]
Pushed refactoring, ready for merge

**Comment by eatonphil** [comment]
Kk. Waiting for tests I guess?

**Comment by SirCmpwn** [comment]
Yep

**Comment by eatonphil** [comment]
Have you thought about pro plans for speeding these tests up?

**Comment by SirCmpwn** [comment]
I don't think that the current speed is an issue, but I'm sure we could get a Pro plan.

**Comment by SirCmpwn** [comment]
Nothing like the API tests on Jenkins after all :smile:

**Comment by eatonphil** [comment]
We are also not even on demand. It picks up our tests as it has the time.

**Comment by eatonphil** [comment]
Needs a rebase.

**Comment by SirCmpwn** [comment]
Rebased. Awaiting test results.

**Comment by SirCmpwn** [comment]
tyvm

**Pull request merged**
