### PR TITLE
M3-5512: Add Monthly Network Transfer Pool to select empty state landing pages

### PR DESCRIPTION
**Pull request by dwiley-akamai**
## Description 📝
- Add `Monthly Network Transfer Pool` to empty state landing pages for Linodes, LKE, NodeBalancers, and OBJ
  - The original ask was for it to be added to the Linodes empty state landing page, but because the MNTP is present when LKE, NB, and OBJ instances exist, the MNTP has been added to the empty state landing pages for those products as well for the sake of consistency (and the ticket updated accordingly).
- Adjustments in `Placeholder.tsx` to accommodate layout changes

## Preview 📷
<details>
  <summary>Screenshots</summary>

Screen Shot 2023-01-25 at 1 02 49 PM

Screen Shot 2023-01-25 at 1 03 04 PM

Screen Shot 2023-01-25 at 1 03 10 PM

Screen Shot 2023-01-25 at 1 08 35 PM
</details>

## How to test 🧪
Ensure the landing pages (empty state and otherwise) match the specs and there have been no adverse impacts from the changes in `Placeholder.tsx`.

### CODE REVIEW

**Review by hkhalil-akamai — APPROVED** [review]
Code and UX changes all LGTM.

I like Dajahi's suggestion from the ticket:

> Possibly consider a tab on the Account page to house this data as well

Another potential place to put this info is in the account dropdown:
Screen Shot 2023-01-25 at 5 13 46 PM


For future consideration.

**Review by mjac0bs — APPROVED** [review]
For the smallest of screens (`xs` breakpoint, but < ~400px w), the end of the sentence is slightly cut off and it looks a little tight on spacing. But the close button on the modal gets misaligned too, so it seems that the very small phones  are edge cases. Layout generally looks consistent across the pages and matches the mocks. 

Screen Shot 2023-01-
25 at 2 45 57 PM

Screen Shot 2023-01-25 at 2 46 06 PM

**Comment by dwiley-akamai** [comment]
@mjac0bs I pushed up a change that prevents the weird line break of the period (except for a small range when the width is ~439px to 444px or so) and the text being flush with the edges.

The modal piece will have to be addressed at the `<Dialog />` level. I'll create a ticket to investigate that if there isn't one already

**Comment by mjac0bs** [comment]
@dwiley-akamai Looking good now, thanks! 🚀  Follow up ticket to fix the modal close button alignment sounds good -- just did a quick skim through existing tickets and didn't see anything for it.

**Comment by dwiley-akamai** [comment]
> @dwiley-akamai Looking good now, thanks! 🚀 Follow up ticket to fix the modal close button alignment sounds good -- just did a quick skim through existing tickets and didn't see anything for it.

Sure thing! I created M3-6141.

**Review by bnussman-akamai — APPROVED** [review]

**Pull request merged**
