### PR TITLE
upcoming: [M3-8145] – Update LDE copy in Linode Create flow when Distributed region is selected

### PR DESCRIPTION
**Pull request by dwiley-akamai**
## Description 📝
Update LDE copy in Linode Create flow when Distributed region is selected

## Changes  🔄
- Copy changes for Linode Create and Linode Create v2
- Docs link added in `DISK_ENCRYPTION_GENERAL_DESCRIPTION`

## Target release date 🗓️
6/24

### Prerequisites
1. Have the linode_disk_encryption tag on your account
2. Point at the alpha/dev environment
3. Have the Linode Disk Encryption (LDE) flag in our dev tool toggled on

### Verification steps
Without the tag and/or with the LDE flag in our dev tool toggled off, you should not see any LDE-related things in the UI. Otherwise,

1. The "Encrypt Disk" checkbox should be disabled if you selected a Distributed region
 - Disk Encryption help text should read: “Distributed Compute Instances are secured using disk encryption. Encryption and decryption are automatically managed for you.”
 -  Tooltip should read: "Distributed instances are encrypted by default and the setting cannot be changed."
2. For other regions, the description help text should have a "Learn more" that points at a reserved doc URL

## As an Author I have considered 🤔
- [X] 👀 Doing a self review
- [X] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [X] 🤏 Splitting feature into small PRs
- [X] ➕ Adding a changeset
- [X] 🧪 Providing/Improving test coverage
- [X] 🔐 Removing all sensitive information from the code and PR description
- [X] 🚩 Using a feature flag to protect the release
- [X] 👣 Providing comprehensive reproduction steps
- [X] 📑 Providing or updating our documentation
- [X] 🕛 Scheduling a pair reviewing session
- [X] 📱 Providing mobile support
- [X] ♿  Providing accessibility support

### CODE REVIEW

**Review by mjac0bs — APPROVED** [review]
Thanks @dwiley-akamai - I confirmed:
- Selecting a distributed region disables the checkbox with a help tooltip specific to distributed regions and the helper text described in the testing steps.
- Selecting Newark (encryption available) still enables the checkbox by default.
- For all other selected regions (or no selected region), the helper text contains the Learn more link, which links to a real page. 
- Changes are feature flagged.

Minor thing that is a little odd: when no region is selected, the help tooltip says "Disk encryption is not available in the selected region", when a user might find it more helpful if it said something more like "Select a region to enable disk encryption".

**Comment by dwiley-akamai** [comment]
> Minor thing that is a little odd: when no region is selected, the help tooltip says "Disk encryption is not available in the selected region", when a user might find it more helpful if it said something more like "Select a region to enable disk encryption".

The plan is to address that and other small oddities/inconsistencies in the flow once Linode Create v2 is rolled out: https://github.com/linode/manager/pull/10535#issuecomment-2145490068

**Comment by mjac0bs** [comment]
> > Minor thing that is a little odd: when no region is selected, the help tooltip says "Disk encryption is not available in the selected region", when a user might find it more helpful if it said something more like "Select a region to enable disk encryption".
> 
> The plan is to address that and other small oddities/inconsistencies in the flow once Linode Create v2 is rolled out: [#10535 (comment)](https://github.com/linode/manager/pull/10535#issuecomment-2145490068)

Ah, thanks, missed that comment thread! Sorry to be repetitive - I'm glad we're all thinking similarly.

**Review by abailly-akamai — APPROVED** [review]

**Comment by abailly-akamai** [comment]
e2e failures look to be unrelated tho another run wouldn't hurt

**Pull request merged**
