### PR TITLE
M3-5809: Cloud Manager changes for Cypress move to Jenkins

### PR DESCRIPTION
**Pull request by jdamore-linode**
## Description

**What does this PR do?**
Adds a couple package scripts that will simplify the Jenkins work required to run our E2E tests, and cleans up the old workflow file that will no longer be used.

- Creates a new `cy:e2e:wait` package script, which waits for `localhost:3000` to respond before running tests, but otherwise behaves similarly to `cy:e2e`
- Creates a new `cy:ci` package script, which runs `yarn start:manager` and waits for `localhost:3000` to respond before running tests, and kills both processes once the tests complete
- Deletes `e2e_pr.yml` workflow
- Deletes `wait-for-it.sh` script, which served the same purpose as the `npm-run-all` package that this PR adds

## How to test

**What are the steps to reproduce the issue or verify the changes?**
Run `yarn` or `yarn up` to update dependencies (kill `yarn up` afterwards), and then run:

```bash
yarn cy:ci
```

Confirm that:
- The tests run as expected, without the need to manually run `yarn up`
- When the tests are finished, Cypress and webpack-dev-server both quit (check that `localhost:3000` cannot be visited in your browser to confirm that webpack-dev-server is not still running in the background)

### CODE REVIEW

**Review by tiffwong — APPROVED** [review]

**Review by DevDW — COMMENTED** [review]
When I first checked out the PR, I did `yarn up`, then brought it down and ran `yarn cy:ci`. I got 37 failures for the tests 😳 re-running them now

**Review by HanaXu — COMMENTED** [review]
@DevDW I ran into the same issue. The failures were 401 unauthorized errors due to a change in OAuth credentials. You'll need to update your `.env` file with the new credentials

**Review by HanaXu — COMMENTED** [review]
`create-database-spec.ts` failed for me

image

**Review by DevDW — APPROVED** [review]
Ran it twice and got some intermittent failures from `databases/create-database.spec.ts`, `firewalls/migrate-linode-with-firewall.spec.ts`, and `objectStorage/buckets.spec.ts`, but those appeared to be server related as opposed to the tests themselves being broken.

**Review by HanaXu — APPROVED** [review]

**Comment by patthiel** [comment]
@jdamore-linode ahh we implemented something similar to this `wait-on` back in the day, but more by hand.. the remnants of it are still in the codebase! can you remove this as part of this PR? https://github.com/linode/manager/blob/develop/scripts/wait-for-it.sh

**Comment by patthiel** [comment]
bumping

**Pull request merged**
