### PR TITLE
fix: wording in "My Profile" -> "Login and Authentication"

### PR DESCRIPTION
**Pull request by jcallahan-akamai**
## Description 📝
**Old:** 
```
To disable Google authentication and log in using your Linode credentials, click the Linode button above. 
```

**New:**
```
To disable Google authentication and log in using your Cloud Manager credentials, click the Cloud Manager button above.
```

## Preview 📷
Screenshot 2023-07-03 at 11 13 07 AM

## How to test 🧪
- Run the app and check the copy at http://localhost:3000/profile/auth.

### CODE REVIEW

**Review by mjac0bs — COMMENTED** [review]
Nice catch; I'm surprised we didn't notice this when we made the initial rebranding changes to Login & Authentication .

I found one more mention of "Linode account" somewhat buried in this tab within  `QRCodeForm.tsx`. Can we also fix? 
Screenshot 2023-07-03 at 8 28 04 AM

(As a note, "Linode account" is present in 2 more places, `CloseAccountDialog.tsx` and `DisplaySettings.tsx`, if we want to expand the scope of this PR slightly.)

**Review by jaalah-akamai — APPROVED** [review]

**Comment by jcallahan-akamai** [comment]
Thanks @mjac0bs. I changed the QR code and Display Settings ones. I'm less sure about the instance in Close Account; will check with UX and follow up later.

**Review by mjac0bs — APPROVED** [review]
🚀

**Review by abailly-akamai — APPROVED** [review]
👍

**Pull request merged**
