### PR TITLE
test: [M3-8951] - Cypress component tests for firewall rules drag and drop `keyboard` interaction

### PR DESCRIPTION
**Pull request by pmakode-akamai**
## Description 📝
Add cypress Component tests for firewall rules table drag and drop keyboard interaction which was enhanced in #11127

- These tests confirm that the keyboard interaction for the Firewall Rules table's drag-and-drop feature works as expected.
- The tests also validate that the `CustomKeyboardSensor` functions correctly:
  - We have customized the default `KeyboardSensor` from `dnd-kit` to meet our specific requirements.
  - The sensor we are using is `CustomKeyboardSensor`, rather than the default `KeyboardSensor` from `dnd-kit`.
  - `CustomKeyboardSensor` works as expected on smaller window sizes, especially when the vertical scrollbar is enabled. In contrast, the default `KeyboardSensor` from `dnd-kit` does not function as intended in this scenario.

## Changes  🔄
-  Add Cypress Component tests for firewall rules drag and drop keyboard interaction
-  Refactor, clean-up and consolidate mouse drag-and-drop interactions
-  Add/Improve comments

## Target release date 🗓️
N/A

## How to test 🧪
```
yarn cy:component:run -s "cypress/component/features/firewalls/firewall-rule-table.spec.tsx"
```

OR

Test *firewall-rule-table.spec.tsx* using
```
yarn cy:component
```

- Ensure all tests pass.
- Confirm `CustomKeyboardSensor` works as expected (both for normal window sizes and when a smaller window with a vertical scrollbar is enabled).
   - This can be tested against both `CustomKeyboardSensor` and the `dnd-kit` default `KeyboardSensor`.
     - To test this scenario, replace `CustomKeyboardSensor` with the default `KeyboardSensor` from `dnd-kit` in the `FirewallRuleTable.tsx` component, and vice-versa.
     - All the tests should pass when using `CustomKeyboardSensor` and some of the tests (related to vertical scrollbar) will fail when using the default `KeyboardSensor`, confirming that `CustomKeyboardSensor` is functioning correctly.

<details>
<summary> Author Checklists </summary>

## As an Author, to speed up the review process, I considered 🤔

👀 Doing a self review
❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
🤏 Splitting feature into small PRs
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
🧪 Providing/improving test coverage
 🔐 Removing all sensitive information from the code and PR description
🚩 Using a feature flag to protect the release
👣 Providing comprehensive reproduction steps
📑 Providing or updating our documentation
🕛 Scheduling a pair reviewing session
📱 Providing mobile support
♿  Providing accessibility support

<br/>

- [x] I have read and considered all applicable items listed above.

## As an Author, before moving this PR from Draft to Open, I confirmed ✅

- [x] All unit tests are passing
- [x] TypeScript compilation succeeded without errors
- [x] Code passes all linting rules

</details>

### CODE REVIEW

**Review by abailly-akamai — COMMENTED** [review]
Thanks for working on this!

@jdamore-linode wouldn't such a test belong to our component test suite?

Perhaps both have their use, but worth checking

**Comment by abailly-akamai** [comment]
@pmakode-akamai & @subsingh-akamai 

M3-8951 & M3-8948 seem to have been duplicated into two different tasks and PRs? see https://github.com/linode/manager/pull/11344

can you please consolidate?

CC @jdamore-linode

**Comment by pmakode-akamai** [comment]
> @pmakode-akamai & @subsingh-akamai
> 
> M3-8951 & M3-8948 seem to have been duplicated into two different tasks and PRs? see #11344
> 
> can you please consolidate?
> 
> CC @jdamore-linode

The other PR is specifically for mouse-based drag and drop (not for keyboard). Should we consolidate both into the same file, or would it be better to keep the keyboard-specific e2e tests separate? I initially thought separating them would provide clearer context since they test different input methods. Let me know your thoughts.

**Comment by abailly-akamai** [comment]
@pmakode-akamai, thx for clarifying - i think those really belong as Cypress component tests (not e2e), and in the same test. we only have a couple at the moment, but this is really what they are meant for. 

The component suite will run in parallel, and won't slow down our e2e suite which has a different purpose.

One e2e would have value to test the actual reordering in the Firewall tables in the main suite, but for pure interaction tests please move those to component tests. Feel free to reach out if you need more detail on how to write them, but it's pretty clear from the examples

**Comment by subsingh-akamai** [comment]
> @pmakode-akamai & @subsingh-akamai
> 
> M3-8951 & M3-8948 seem to have been duplicated into two different tasks and PRs? see #11344
> 
> can you please consolidate?
> 
> CC @jdamore-linode

Hi @abailly-akamai - both tickets are subtask under M3-8862, and they will be under same spec file.

**Review by abailly-akamai — APPROVED** [review]
Thank you! test passes and code looks good - great coverage 👍

**Review by coliu-akamai — APPROVED** [review]
✅ confirmed tests passed

thank you! 🚀 comments were super helpful with explaining the test cases

**Review by subsingh-akamai — APPROVED** [review]
Approved.. Thank you for refactoring

**Pull request merged**
