### PR TITLE
M3-1717 Support search results list is too wide on production builds

### PR DESCRIPTION
**Pull request by WilkinsKa1**
While the css 'bracket' targeting works locally, once compiled, we lose the styling that is being applied to material ui elements. The solution was to add a class globally to the base component itself and styling their usage in specific, custom components. 

Algolia Search:

Before:
screen shot 2018-10-31 at 5 01 57 pm

After:
screen shot 2018-10-31 at 5 02 40 pm

Tag Selects (note there is related work forthcoming for this component):

Before:
screen shot 2018-10-31 at 5 08 24 pm

After:
screen shot 2018-10-31 at 5 03 48 pm

### CODE REVIEW

**Comment by alioso** [comment]
I fixed the additional classes but we are getting a bad PUT 400 API request now when trying to add an existing tag, which triggers the blur handler (therefore we can't see the error unless we re-open the select tag menu). this is not happening on Prod currently @martinmckenna

**Comment by patthiel** [comment]
Updated the description, since this isn't happening on prod _yet_ but is happening on production builds (which get shipped to the test/dev environments)

**Comment by Jskobos** [comment]
@patthiel I see this on prod as well, actually thought we'd reported it > a month ago

**Comment by patthiel** [comment]
@Jskobos I meant more that the fix initially implemented is not working on production builds (not the prod environment). The issue this PR is addressing is the approach the fix of this issue on production builds.

**Pull request merged**
