### PR TITLE
Add footer

### LINKED ISSUE #382: Add footer links and attributions

### PR DESCRIPTION
**Pull request by eatonphil**
And some minor cleanup

screen shot 2016-08-25 at 4 50 05 pm

Closes #382

### CODE REVIEW

**Comment by eatonphil** [comment]
Closes #382

**Comment by SirCmpwn** [comment]
For pages whose height < the screen height (like the one pictured) can you pin the footer to the bottom of the screen rather than putting it in the middle?

**Comment by eatonphil** [comment]
I'd support that if you can do it in just css. Can you think of that off the top of your head?

**Comment by SirCmpwn** [comment]
Can be done with some flexbox stuff. Look up the holy grail layout. It may not be easy.

**Comment by eatonphil** [comment]
Is it alright to make a new task for that?

**Comment by SirCmpwn** [comment]
:-1:

**Comment by eatonphil** [comment]
Will look at it tomorrow

**Comment by SirCmpwn** [comment]
kk

**Comment by eatonphil** [comment]
Good to go.

screen shot 2016-08-26 at 8 13 35 am

**Comment by SirCmpwn** [comment]
:+1:

**Comment by eatonphil** [comment]
thanks!

**Pull request merged**
