### PR TITLE
[WIP] polling backup status

### LINKED ISSUE #351: Poll backup status for pending/running
- [ ] When a snapshot is created
- [ ] On page load

### PR DESCRIPTION
**Pull request by na3d**
Closes #351 

Tests To Do
- [ ] subresource fetch until
- [ ] fetch backup until
- [ ] backup component status
- [ ] linter

### CODE REVIEW

**Comment by na3d** [comment]
Everything is working smoothly, just needs more tests.

**Comment by eatonphil** [comment]
Not running your linter? I see some console.logs already

**Comment by na3d** [comment]
Yeah, I normally do that after tests.

**Comment by eatonphil** [comment]
:/

```bash
$ cat .git/hooks/pre-commit
#!/usr/bin/env bash
npm run lint
```

**Comment by na3d** [comment]
This PR needs to be refactored due to changes to the API.

**Pull request closed without merging**
