### PR TITLE
Update NodeBalancerCreate to use new fast track create...

### PR DESCRIPTION
**Pull request by rjstires**
## Purpose
- Update NodeBalancer creation to use updated API.
- DRY'd up and removed lambdas in render in NodeBalancerSummary

### CODE REVIEW

**Comment by rjstires** [comment]
@alioso can you have a look at NodeBalancer creation/editing? The node fields are no longer inline as a result of mode being visible in creation but not in editing.

**Comment by asauber** [comment]
@rjstires not all of the error groups were updated on the config panel, updated them d3f0d8c

**Comment by alioso** [comment]
@rjstires these are the intended styles for best responsive handling. Too many inline fields breaks the flow of the containers

**Comment by asauber** [comment]
Error handling looks good, except the `ssl_` state needs to be cleared upon changing protocol.

screen shot 2018-06-27 at 6 16 42 pm

**Pull request merged**
