### PR TITLE
Release v1.131.2 - staging → master

### PR DESCRIPTION
**Pull request by bnussman-akamai**
### Fixed:

- APL summary panel not being loaded consistently ([#11207](https://github.com/linode/manager/pull/11207))

### CODE REVIEW

**Review by abailly-akamai — APPROVED** [review]

**Review by coliu-akamai — APPROVED** [review]
working as expected on staging -- thank you!!

**Comment by abailly-akamai** [comment]
i am actually seeing the same issue on staging after a couple more tries

**Comment by coliu-akamai** [comment]
oh no 😨

**Comment by coliu-akamai** [comment]
confirming not seeing the double reload for newly created clusters (didn't have pre-existing ones)

**Comment by bnussman-akamai** [comment]
Also not seeing any major double reload. Users may see extra loading states because we have to load in the Account Beta to know if they have the capability. It might be more noticeable for users not enrolled in the beta, but shouldn't break the experience for them. 

It's been quite tricky getting things tuned with React Query, the conditional endpoint, and the use of Account Betas 😣

**Comment by abailly-akamai** [comment]
@bnussman-akamai yes. not ideal at all. Thanks for getting this to the finish line and making it the best we can

**Pull request merged**
