### PR TITLE
feat: [M3-7343] – Display conditional Notices depending on config scenarios in Linode Add/Edit Config dialog 

### PR DESCRIPTION
**Pull request by dwiley-akamai**
## Description 📝
If a user is about to select an unrecommended configuration in the Add/Edit Config dialog, we want to display conditional warning notices informing them of this and what we recommend to avoid the network connectivity issues that would come with the unrecommended configuration.

## Changes  🔄
- Added `unrecommendedConfigNoticeSelector` function
- Added several constants for copy
- Display conditional notices depending on scenario in Add/Edit Config dialog

## Preview 📷
<details>
<summary>Scenario 1</summary>

- Have a VPC interface and another non-VPC interface (`public` is fine)
- the index of the primary interface !== the index of the VPC interface (i.e., the non-VPC interface should be primary)
- `nattedIPv4Address` (i.e., "Assign a public IPv4 address for this Linode" checked)

Screenshot 2023-11-20 at 10 51 31 AM
</details>

<details>
<summary>Scenario 2</summary>

- all of Scenario 1, except: `!nattedIPv4Address` (i.e., "Assign a public IPv4 address for this Linode" unchecked)

Screenshot 2023-11-20 at 10 50 43 AM
</details>

<details>
<summary>Scenario 3</summary>

- only eth0 populated, and it is a VPC interface where `!nattedIPv4Address` (i.e., "Assign a public IPv4 address for this Linode" unchecked)

Screenshot 2023-11-20 at 10 52 23 AM
</details>

### Prerequisites
- An account with the proper VPC tags

### Verification steps 
In the Add/Edit Config dialog, ensure that the specific scenarios outlined in the `Preview` section above are all handled as expected, and that none of the notices display outside of the outlined scenarios.

## As an Author I have considered 🤔
- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a changeset
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [x] 👣 Providing comprehensive reproduction steps
- [x] 📑 Providing or updating our documentation
- [x] 🕛 Scheduling a pair reviewing session
- [x] 📱 Providing mobile support
- [x] ♿  Providing accessibility support

### CODE REVIEW

**Review by mjac0bs — COMMENTED** [review]
✅  Tested all three scenarios and saw the different error messages as pictured, and confirmed that making the appropriate selections caused the notice to disappear. 
✅  Checked that the notice did not appear for scenarios other than the one specified and that multiple notices appeared if there were multiple VPCs.
❓ Checked that I could still submit the form without errors and found one thing mentioned below.

Question: in messing around with different settings, I created a config that had Public Internet in eth0, VPC in eth1, and VLAN in eth2. When I attempted to save my changes, the form did not submit and no feedback was given in the UI. In the console, I saw the error below. Do we want to either surface this or provide some validation in the form? 

Screenshot 2023-11-21 at 11 59 19 AM
Screenshot 2023-11-21 at 12 00 35 PM


I don't know enough about configs to know whether this is related to recent VPC changes or a separate issue related to VLANs (I suspect that we just never surfaced this error) -- or whether a user would ever reasonably even try this, but wanted to raise it. Disregard in this PR if it should be addressed in a follow up.

**Comment by dwiley-akamai** [comment]
> Question: in messing around with different settings, I created a config that had Public Internet in eth0, VPC in eth1, and VLAN in eth2. When I attempted to save my changes, the form did not submit and no feedback was given in the UI. In the console, I saw the error below. Do we want to either surface this or provide some validation in the form?
> 
> I don't know enough about configs to know whether this is related to recent VPC changes or a separate issue related to VLANs (I suspect that we just never surfaced this error) -- or whether a user would ever reasonably even try this, but wanted to raise it. Disregard in this PR if it should be addressed in a follow up.

Good find -- I believe from a networking perspective this would be a counterproductive configuration. The API explicitly forbids VLAN interfaces from being marked as `primary`, and that field is a newer one tied to the VPC project. We should definitely surface the error, but I find the current wording of it to be ambiguous when it's in the context of Cloud. Going to ask API if the `reason` can be adjusted and I'll create a follow-up ticket to address this issue.

**Review by mjac0bs — APPROVED** [review]
> Going to ask API if the reason can be adjusted and I'll create a follow-up ticket to address this issue.

Sounds good, thanks! Approving this now.

**Review by coliu-akamai — APPROVED** [review]
✅  Confirmed for the Add and the Edit config dialogs:
- scenario 1
- scenario 2
- scenario 3

Also confirmed could still submit for these scenarios (excluding the case Mariah pointed out) ✅ 
✅ code review

awesome job! 🚀

**Comment by dwiley-akamai** [comment]
The follow-up ticket mentioned earlier has been created (M3-7480)

**Pull request merged**
