### PR TITLE
Access docs cleanup

### PR DESCRIPTION
**Pull request by rmcintosh**
We're doing really weird spacing (or lack of spacing) all over this page ... I think I got all instances for this guide

### CODE REVIEW

**Comment by displague** [comment]
I think your editor added even more really weird spaces .. Can you make this PR look more like: https://github.com/linode/manager/pull/2439/files?w=1

**Comment by rmcintosh** [comment]
yes

**Comment by displague** [comment]
https://reactjs.org/blog/2014/02/20/react-v0.9.html#jsx-whitespace is behind this

**Comment by rmcintosh** [comment]
gonna re-PR this now that I've figured out how to fix

**Pull request closed without merging**
