### PR TITLE
Fix Volumes and Domains tests

### PR DESCRIPTION
**Pull request by Jskobos**
`yarn e2e --spec=e2e/specs/linodes/detail/create-volumes.spec.js`
`yarn e2e --spec=e2e/specs/domains/smoke-list-domains.spec.js`
(Or run both at once, just comma-separate the files)

### CODE REVIEW

**Comment by martinmckenna** [comment]
Ran twice - got this error both times

```
mmckenna@MartinMBP:~/code/manager ‹3fbe43dee›
$ yarn e2e --spec=e2e/specs/domains/smoke-list-domains.spec.js,e2e/specs/linodes/detail/create-volumes.spec.js --browser=headlessChrome
yarn run v1.10.1
$ npx wdio ./e2e/config/wdio.conf.js --spec=e2e/specs/domains/smoke-list-domains.spec.js,e2e/specs/linodes/detail/create-volumes.spec.js --browser=headlessChrome

DEPRECATION: Setting specFilter directly on Env is deprecated, please use the specFilter option in `configure`
DEPRECATION: Setting stopOnSpecFailure directly is deprecated, please use the failFast option in `configure`
Not on the Oauth Page, continuing
․․․․․․․․DEPRECATION: Setting specFilter directly on Env is deprecated, please use the specFilter option in `configure`
DEPRECATION: Setting stopOnSpecFailure directly is deprecated, please use the failFast option in `configure`
Not on the Oauth Page, continuing
․․․․․․․․․․․F․․․․․․․․

27 passing (198.20s)
1 failing

1) Create Attached Volume - Detach Volumesuite4 volume created successfully with tag:
Failed: Promise was rejected with the following reason: timeout
running chrome
error properties: Object({ details: undefined, type: 'WaitUntilTimeoutError' })
Error: Promise was rejected with the following reason: timeout
    at elements("[data-qa-tag]") - index.js:312:3



Removing all data from prod-test-003
✨  Done in 221.70s.
```

**Comment by johnwcallahan** [comment]
Ran this several times. First 2-3 times had mostly failures, then I had a run with all passing tests. Ran it one more time and got this:

```
․․․․․․․․․․․․․․․․F․․․

19 passing (129.70s)
1 failing

1) Attach Existing Volume - Detatch Volumesuite5 volume attached successfully:
Failed: element ("[data-qa-volume-cell]") still not visible after 12000ms
running chrome
error properties: Object({ details: undefined, type: 'WaitUntilTimeoutError' })
Error: element ("[data-qa-volume-cell]") still not visible after 12000ms
    at elements("[data-qa-volume-cell]") - isVisible.js:54:17
    at isVisible("[data-qa-volume-cell]") - waitForVisible.js:73:22
```

**Comment by Jskobos** [comment]
I'm not able to reproduce this:

```
․․․․․․․․․․․․․․․․․․․․

20 passing (122.90s)


Removing all data from prod-test-004
✨  Done in 146.56s.

$ npx wdio ./e2e/config/wdio.conf.js --spec=e2e/specs/linodes/detail/create-volumes.spec.js --headlessChrome


․․․․․․․․․․․․․․․․․․․․

20 passing (130.20s)


Removing all data from prod-test-004
✨  Done in 153.69s.
 
$ npx wdio ./e2e/config/wdio.conf.js --spec=e2e/specs/linodes/detail/create-volumes.spec.js --headlessChrome


․․․․․․․․․․․․․․․․․․․․

20 passing (120.40s)


✨  Done in 143.81s.

$ npx wdio ./e2e/config/wdio.conf.js --spec=e2e/specs/linodes/detail/create-volumes.spec.js --headlessChrome


․․․․․․․․․․․․․․․․․․․․

20 passing (124.80s)

```

**Comment by martinmckenna** [comment]
I ran 3 times, got all passing twice and got John's error once. I suggest making this

`VolumeDetail.volumeCellElem.waitForVisible(constants.wait.normal);`

`wait.long`

**Comment by patthiel** [comment]
Ran the tests and they passed but agree with @martinmckenna  that the volumes test could be flakey. adding that wait may help in the short term, but all in all i think that spec should be broken up into multiple specs. A ticket should be created to handle that^

**Comment by Jskobos** [comment]
@patthiel @martinmckenna extended the wait time

**Comment by Jskobos** [comment]
@martinmckenna @patthiel My .env has two manager users (sorry Russ!), do you think that could be why I'm consistently getting no errors for these but you guys are?

**Comment by Jskobos** [comment]
(just ran all of these >5 times with 0 errors)

**Pull request merged**
