### PR TITLE
feat: [M3-7267] - Add AGLB Rule Delete Dialog

### PR DESCRIPTION
**Pull request by bnussman-akamai**
## Description 📝

- Adds the functionality to delete rules from an AGLB route 🗑️🎉

## Preview 📷

Screenshot 2023-10-17 at 11 51 56 AM

### Prerequisites
- Turn on the MSW
- Navigate to `http://localhost:3000/loadbalancers/0/routes`

### Verification steps 
- Expand any of the Routes ⬇️
- Attempt to delete a rule on a route 🗑️
- Verify the route gets deleted ☑️

Test:
```
yarn cy:run -s "cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts"
```

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a changeset
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [x] 👣 Providing comprehensive reproduction steps
- [x] 📑 Providing or updating our documentation
- [x] 🕛 Scheduling a pair reviewing session
- [x] 📱 Providing mobile support
- [x] ♿  Providing accessibility support

### CODE REVIEW

**Review by dwiley-akamai — APPROVED** [review]
Functionality per verification steps looks good ✅
`load-balancer-routes.spec.ts` passed locally ✅
Code review ✅

**Review by mjac0bs — COMMENTED** [review]
Rule deletes successfully and `load-balancer-routes.spec.ts` passed. ✅ 

The UX of this has probably been discussed, but can you remind me why our action menu uses the language "Remove" and the modal uses the language "Delete"? This mismatch seems a little odd to me, so I wondered what the intent was. 

Screenshot 2023-10-19 at 10 25 33 AM
Screenshot 2023-10-19 at 10 25 41 AM

**Comment by bnussman-akamai** [comment]
I agree @mjac0bs. I took this down as something to address later. Probably was just a UX oversight

**Review by mjac0bs — APPROVED** [review]

**Comment by bnussman-akamai** [comment]
Actually, I'm just going to make it `Delete`. Remove doesn't make any sense here. Once the rule is "Removed", it's completely gone.

**Pull request merged**
