### PR TITLE
Adjust the snapshot section when appropriate

### LINKED ISSUE #334: Take backup text doesn't change after a manual snapshot does exist

### PR DESCRIPTION
**Pull request by SirCmpwn**
Fixes #334

### CODE REVIEW

**Comment by abemassry** [comment]
👍

**Comment by SirCmpwn** [comment]
Thanks

**Comment by eatonphil** [comment]
-1 on displaying the snapshot backup card in the snapshot section. but a lot of this page is bothersome anyway. I'm thinking we should remove the snapshot section and rework the location of a few buttons so things make more sense here in general.

**Comment by SirCmpwn** [comment]
I think it brings some consistency, but it is a departure from the mockup. A second opinion here would be nice.

**Comment by eatonphil** [comment]
If it were to be displayed here at all, I'd recommend putting that snapshot card above the warning text. But again, I'm sort of suggesting we remove the snapshot section in the long term.

**Comment by abemassry** [comment]
If there is a snapshot section and there is already a snapshot in place, it's a good visual indicator that there is one and you will be overwriting it.  As opposed to having to look at your backups on top and the snapshot being one of five

**Comment by eatonphil** [comment]
> snapshot being one of five

One of four

> If there is a snapshot section and there is already a snapshot in place, it's a good visual indicator that there is one and you will be overwriting it.

That there is a separate section for creating a new "one of four" backups in the above section is a poor visual indicator and the reason I think we should get rid of the snapshot section.

But again - if we can't do that for now - I just recommend putting the snapshot card above the warning text.

**Comment by SirCmpwn** [comment]
I originally had it that way and didn't like how it looked. On the side looks better. Why do you want to move it?

**Comment by eatonphil** [comment]
I think it is both confusing to have them side by side and looks awkward.

**Pull request merged**
