### PR TITLE
M3-5576: Fix row height and extra spacing around ActionMenu in Safari

### PR DESCRIPTION
**Pull request by tiffwong**
## Description

The `InlineMenuAction` and `ActionMenu` components weren't fully extending to the entire row height in Safari for certain entities (ie. Volumes and Images). This seems to be related to having an extra `div` inside the `TableCell` and applying the styling on that `div`. 

In order to make things more consistent and prevent having to copy and paste the styles for each `ActionMenu`, I created a `TableCell` variant that cleans up the code.

## How to test

Check the `ActionMenu`'s throughout the app on Chrome **and** Safari.

### CODE REVIEW

**Review by codyfinn — APPROVED** [review]
Awesome work finding the solution to this!

**Review by bnussman — CHANGES_REQUESTED** [review]
Looks great but I'm still seeing something like 2px of padding in the PaymentMethodRow component in Safari, can we get this fixed too? 

Screen Shot 2021-11-15 at 9 32 59 AM

**Review by bcmertz — COMMENTED** [review]
Awesome job! Could SortableTableHead.tsx also be refactored?

**Review by bnussman — APPROVED** [review]
This is great! Makes using Cloud Manager in Safari so much better and cleans up a lot of styles. Awesome work

**Pull request merged**
