### PR TITLE
noscript

### LINKED ISSUE #1977: Add noscript

### PR DESCRIPTION
**Pull request by na3d**
Closes #1977

### CODE REVIEW

**Comment by rmcintosh** [comment]
plz2sans-serif?<3

**Comment by na3d** [comment]
@eatonphil, yeah.  I wanted to use the PR review to verify how we wanted to approach the CSS.

**Comment by na3d** [comment]
screen shot 2017-09-29 at 9 22 46 am

**Comment by eatonphil** [comment]
Not exactly what I meant, but fine for now.

**Pull request merged**
