### PR TITLE
Netmask display

### LINKED ISSUE #832: Add netmask field to networking page and drop netmask on every other page

### PR DESCRIPTION
**Pull request by na3d**
Closes #832

### CODE REVIEW

**Comment by eatonphil** [comment]
Should also add a netmask field to both the ipv4 and ipv6 sides. 255.255.255.0 for ipv4 and / 64 (or whatever) on the ipv6 side. Did I get that right @abemassry?

**Comment by na3d** [comment]
They all already exist, much to my surprise.

**Comment by na3d** [comment]
https://github.com/linode/manager/blob/master/src/linodes/linode/networking/layouts/SummaryPage.js#L99-L122

**Comment by eatonphil** [comment]
Looks like that's a special case for private ipv4 but it should also drop the /17 and /24 things I'd think. We are talking about a completely new field to the ipv4 and ipv6 sides (like IP Address and Gateway) that says 255.255.255.0 on the ipv4 side and  / 64 (or whatever) on the ipv6 side I think.

**Comment by na3d** [comment]
The gateway stuff sounds like something else.  Did he want the private IP /17 removed on the networking page?

**Comment by abemassry** [comment]
@eatonphil yes that is correct

**Comment by eatonphil** [comment]
screenshot?

**Comment by na3d** [comment]
screen shot 2017-01-12 at 10 25 40 am

**Comment by eatonphil** [comment]
@jamesottinger says they'll explicitly provide us with the netmask in the future. For now, looks good.

**Comment by eatonphil** [comment]
Whoops

**Pull request merged**
