### PR TITLE
test: [M3-7783] Add cypress assertion and test for placement group deletion error handling

### PR DESCRIPTION
**Pull request by AzureLatte**
## Description 📝
Add new tests/assertions to check error handling in delete-placement-groups.spec.ts. 
Confirm that Cloud Manager gracefully responds if an API error occurs while un-assigning a Linode via the delete modal.
Confirm that Cloud Manager gracefully responds if an API error occurs upon attempt to delete a VM Placement Group.

## Changes  🔄

- Add new assertion to check user can retry and continue with deletion when unexpected error happens.
- Add new test to check that user can close and reopen the dialog when unexpected error happens during deletion. (skipped due to M3-8112)
- Add new assertion to check user can retry and continue with unassignment when unexpected error happens.
- Add new test to check that user can close and reopen the dialog when unexpected error happens during unassignment. (skipped due to M3-8112)

## How to test 🧪
```
yarn cy:run -s "cypress/e2e/core/placementGroups/delete-placement-groups.spec.ts"
```

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by jaalah-akamai — APPROVED** [review]
✅ 
Screenshot 2024-05-21 at 11 02 48 AM

**Comment by abailly-akamai** [comment]
@AzureLatte you will need to rebase this PR with the latest develop. All tests are failing now because of a bad merge that ended up in develop.

**Comment by AzureLatte** [comment]
> @AzureLatte you will need to rebase this PR with the latest develop. All tests are failing now because of a bad merge that ended up in develop.

Just updated. Could you please retry? Thank you!

**Comment by abailly-akamai** [comment]
@AzureLatte https://github.com/linode/manager/pull/10486 was merged!

you should be able to remove this [skip](https://github.com/linode/manager/pull/10493/files#diff-465e4d53e183c28e3acee6ed96f8757c6bdd9502dc0de083a982a1f96dc46899R326) in this PR now

**Review by jdamore-linode — APPROVED** [review]
Nice work @AzureLatte, tests look great and bonus points for catching that dialog reset issue too!

Also confirmed that pulling in the latest changes from `develop` allows those skipped tests to pass 👍 approved pending the latest from `develop` getting merged in and those tests being unskipped!

**Review by abailly-akamai — APPROVED** [review]
Looks great, thanks for the coverage and reporting that bug! 🚢

**Pull request merged**
