### PR TITLE
reduce primary list item height to 50px

### PR DESCRIPTION
**Pull request by mparke**
somewhat aesthetically subjective, but removes excess whitespace, and is a closer ratio to relative UI elements.

### CODE REVIEW

**Comment by eatonphil** [comment]
-1, Took a while to tune and I am pretty happy with the 65px

**Comment by na3d** [comment]
Can you post screens of before and after?

**Comment by mparke** [comment]
Just trying stuff out. 

@na3d 
Before:

screen shot 2017-03-29 at 10 11 09 am

After:

screen shot 2017-03-29 at 10 10 20 am

**Comment by mparke** [comment]
at a later time, with more data perhaps, closing

**Pull request closed without merging**
