### PR TITLE
Backup schedule

### LINKED ISSUE #274: Implement backup schedule editing

### PR DESCRIPTION
**Pull request by SirCmpwn**
Closes #274 

Needs more tests.

### CODE REVIEW

**Comment by na3d** [comment]
👍

**Comment by eatonphil** [comment]
Still needs more tests or good to go?

**Comment by SirCmpwn** [comment]
Good to go.

**Comment by eatonphil** [comment]
👍

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
