### PR TITLE
Change nevermind buttons to links

### LINKED ISSUE #509: Nevermind in modal should be link, not button

### PR DESCRIPTION
**Pull request by briansteffens**
Closes #509

### CODE REVIEW

**Comment by eatonphil** [comment]
Good candidate for a screenshot

**Comment by briansteffens** [comment]
screen shot 2016-10-04 at 3 58 55 pm

**Comment by briansteffens** [comment]
screen shot 2016-10-04 at 4 33 59 pm

**Comment by eatonphil** [comment]
https://github.com/linode/manager/issues/517

**Pull request merged**
