### PR TITLE
Add account dropdown

### LINKED ISSUE #1546: Move users/billing/settings out of profile dropdown
Discuss:

Separate Icon or Primary Nav Account

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #1546 

screen shot 2017-04-18 at 5 10 59 pm
screen shot 2017-04-18 at 5 11 10 pm

### CODE REVIEW

**Comment by na3d** [comment]
Would a gear work better than the people for account?  Since you are managing users, billing, and settings under it?

**Comment by eatonphil** [comment]
> Would a gear work better than the people for account? Since you are managing users, billing, and settings under it?

Not that the people icon is particularly great, but if we're trying to illustrate _account-wide_ options I think the people icon is a little more helpful than a settings / gear icon.

**Comment by mparke** [comment]
the list of pull requests doesn't show it, @eatonphil ^ merge conflicts

**Comment by eatonphil** [comment]
Yeah I've got some work to do on #1621 before I am done here.

**Comment by eatonphil** [comment]
screen shot 2017-05-01 at 4 49 21 pm
screen shot 2017-05-01 at 4 49 15 pm

**Comment by mparke** [comment]
@eatonphil #1621 was merged, still conflicts here, mind fixing?

**Comment by na3d** [comment]
Is this PR still relevant?  Or do the screens need updated?

**Comment by eatonphil** [comment]
Needs to be revisited since the last review.

**Pull request closed without merging**
