### PR TITLE
Fix domain display group

### PR DESCRIPTION
**Pull request by eatonphil**
To test, no group name should be undefined on Domains page.

### CODE REVIEW

**Comment by abemassry** [comment]
was this the desired effect?
a_dashes

**Comment by eatonphil** [comment]
@abemassry nope, I got some of these PRs mixed up. Thankfully you helped me find some lost commits. :D

**Comment by eatonphil** [comment]
@abemassry fixed, thanks!

**Comment by eatonphil** [comment]
@mparke fixed em up

**Comment by eatonphil** [comment]
Thanks!

**Pull request merged**
