### PR TITLE
feat: [OCA-1135] - June 2023 Marketplace Release

### PR DESCRIPTION
**Pull request by tbaka**
## Description 📝
**adds partner submitted marketplace apps for May 2023**

## Major Changes 🔄
- updates fakespec + ref May 2023 docs
- updates selectapppanel
- adds partner submitted .svgs

### CODE REVIEW

**Comment by jaalah-akamai** [comment]
@tbaka I believe we need to add those new apps [here](https://github.com/linode/manager/blob/develop/packages/manager/src/features/StackScripts/stackScriptUtils.ts#L131) too

**Comment by tbaka** [comment]
Updated, thanks for the review.

**Review by hana-linode — COMMENTED** [review]
@tbaka For some reason, the API is not returning the new apps from the `/stackscripts` endpoint

**Comment by tbaka** [comment]
I will double check my changes and investigate the possibility of a problem on the API end as well.

**Review by bnussman-akamai — COMMENTED** [review]
I see the app now, but it looks like we need to fix a few things

- Details drawer for OwnCloud shows `App Details Not Found`
- No white icons show in the details drawer

**Review by hana-linode — APPROVED** [review]

**Pull request merged**
