### PR TITLE
Update create styles and structure

### PR DESCRIPTION
**Pull request by eatonphil**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Screenie?

**Comment by eatonphil** [comment]
Basically just this:

screen shot 2016-07-07 at 3 26 05 pm

The rest is reorganization.

**Comment by SirCmpwn** [comment]
LGTM, waiting on build

**Comment by eatonphil** [comment]
Added [DO NOT MERGE], datacenters are not showing up for some reason...

**Comment by eatonphil** [comment]
I am fine with the -0.1% change.

**Comment by eatonphil** [comment]
ty

**Pull request merged**
