### PR TITLE
M3-569 - Replace hardcoded timeouts, editDnsAction

### PR DESCRIPTION
**Pull request by patthiel**
* Refactored tests to use standardized waitFor timeouts configured in the constants.js file.
* Added `editDNS` domains page object utility method.

### CODE REVIEW

**Comment by rjstires** [comment]
So the code looks good and DRY, but I made the mistake of running `e2e:all` and there were just so many failures. I don't know if this is related. We'll have to sync up.

**Comment by rjstires** [comment]
This might not be on the tests. there's some sort of API situation going on preventing the creation of Linodes in dev. I'll circle back once it's been resolved.

**Comment by patthiel** [comment]
@rjstires  thanks for reviewing. The next PR will contain the setup/teardown process refactor. It should make the tests significantly more reliable. (I just ran the full suite yesterday with the refactored code and got 14 failures total). Still some fixes to be made, but some of the failures are genuine bugs.

**Comment by martinmckenna** [comment]
Looks :+1:

**Pull request merged**
