### PR TITLE
M3-5859: Upgrade Cypress to v10

### PR DESCRIPTION
**Pull request by jdamore-linode**
## Description

**What does this PR do?**

This upgrades Cypress from v9.x to v10.x.

Some changes were made to Cypress's config and directory structure to accommodate its new component testing functionality.

## How to test

**What are the steps to reproduce the issue or verify the changes?**

Confirm that Cypress tests work as expected:
```
yarn cy:debug
```

```
yarn cy:run
```

### CODE REVIEW

**Comment by jdamore-linode** [comment]
@bnussman I'm getting conflicting info reading Cypress's changelog and GH issues, but I think Cypress 10 has better support for Webpack 5 -- maybe this will allow us to do away with the alias workaround for {{api-v4}} and {{validation}}?

**Comment by bnussman** [comment]
I tried to remove the alias in the tsconfig but I still saw this :(

Screen Shot 2022-08-15 at 5 18 15 PM

**Comment by jdamore-linode** [comment]
Bummer :/ Thanks for taking a look! I may spend some time looking at that later!

**Review by bnussman — APPROVED** [review]
e2es run well! The new Cypress UI looks nice!

**Review by HanaXu — APPROVED** [review]
Two tests failed for me (`change-username.spec.ts` & `attach-volume.spec.ts`) but it's probably just due to test flakiness. LGTM otherwise!

**Pull request merged**
