### PR TITLE
M3-5063: Linode Configs modal refinements

### PR DESCRIPTION
**Pull request by tiffwong**
## Description

Adjust color and spacing of divider and shift the "Add a Device" button over by 1px

## How to test

1. Go to `/linodes`
2. Click on any Linode
3. Go to the "Configurations" tab
4. Click "Add Configuration"
5. Scroll through the modal and check for issues

### CODE REVIEW

**Review by bnussman — APPROVED** [review]
Modal looks good!

**Review by HanaXu — COMMENTED** [review]
What are your thoughts on spacing the divider evenly instead? The divider also disappears on dark mode

image

image

**Comment by tiffwong** [comment]
@HanaXu good catch on the dark mode! I always forget that and I prefer a tighter spacing below the divider but I could be convinced 🤔

**Comment by HanaXu** [comment]
@tiffwong Is this convincing enough? :laughing: https://material-ui.com/components/dividers/

**Review by HanaXu — APPROVED** [review]

**Pull request merged**
