### PR TITLE
fix: [M3-6763] - Cleared OAuth client inputs after canceling or submitting

### PR DESCRIPTION
**Pull request by tyler-akamai**
## Description 📝
When adding an OAuth app in Cloud Manager, the data entered into the "Create OAuth App" drawer persists after cancelling or creating an app.

## Major Changes 🔄
- Added `formik.resetForm()` whenever the `open` state is changed.

## Preview 📷

| Before  | After   |
| ------- | ------- |
| <video src="https://github.com/linode/manager/assets/139489745/6e7af030-ae03-4763-b342-4ec0ff1792c6"/> | <video src="https://github.com/linode/manager/assets/139489745/607fab2a-e709-4804-bc08-558a18696814"/> |

## How to test 🧪
1. Navigate to the `My Profile` Page
2. Navigate to the `OAuth Apps` tab (http://localhost:3000/profile/clients)
3. Test if the `Add An OAuth App` tab clears when submitting or canceling

### CODE REVIEW

**Review by mjac0bs — APPROVED** [review]
🧼  form, thanks for fixing.

(Small tip: including `<video src=FILE_URL/>` in tables will render a little preview of the video. Without that tag, videos will show up as links only.)

**Review by hana-linode — APPROVED** [review]
🧹

**Comment by tyler-akamai** [comment]
> 🧼 form, thanks for fixing.
> 
> (Small tip: including `<video src=FILE_URL/>` in tables will render a little preview of the video. Without that tag, videos will show up as links only.)

**Comment by tyler-akamai** [comment]
> 🧼 form, thanks for fixing.
> 
> (Small tip: including `<video src=FILE_URL/>` in tables will render a little preview of the video. Without that tag, videos will show up as links only.)

Awesome, Thank you!

**Pull request merged**
