### PR TITLE
hotfix: [M3-7084] - Fix Restricted User Permissions after entity creation

### PR DESCRIPTION
**Pull request by bnussman-akamai**
## Description 📝

- FIxes bug where restricted users would not have read-write permissions after they created a firewall

## Preview 📷

| Before  | After   |
| ------- | ------- |
| <video src="https://github.com/linode/manager/assets/115251059/269ec1fd-364d-4962-aaca-6cd776a2760b" /> | <video src="https://github.com/linode/manager/assets/115251059/da0fb2a9-45fd-443c-bffb-be7743783289" /> |

## How to test 🧪
- As a restricted user
  - Create a firewall
  - Verify that a GET to `/v4/profile/grants` happens
  - Verify that you can edit that firewall immediately after creation
- As a non-restricted user
  - Create a firewall
  - Verify you **don't** see a GET to `/v4/profile/grants` (because it's unnecessary for an unrestricted user)
  - Verify that you can edit that firewall immediately after creation

### CODE REVIEW

**Review by mjac0bs — APPROVED** [review]
Confirmed `/v4/profile/grants` happens for restricted users only and editing a firewall post-creation is possible without refreshing the page.

**Review by cpathipa — APPROVED** [review]

**Review by abailly-akamai — COMMENTED** [review]
As for any bug we fix, could we include a test to cover this behavior?

**Comment by bnussman-akamai** [comment]
Hm, I don't think a unit test would be great here. We could do an e2e but I don't think we do much restricted user testing in the e2es. Any thoughts @jdamore-linode on how this should be tested in an automated way?

**Comment by abailly-akamai** [comment]
@bnussman-akamai @jdamore-linode let's make a follow up ticket to consider tests for restricted users for now and get this to production?

**Review by abailly-akamai — APPROVED** [review]

**Comment by jdamore-linode** [comment]
> @bnussman-akamai @jdamore-linode let's make a follow up ticket to consider tests for restricted users for now and get this to production?

Sorry I missed your ping Alban! If I remember correctly we do have a ticket or spike to examine restricted user tests -- I'll definitely revisit with this with this issue in mind.

**Review by jaalah-akamai — APPROVED** [review]

**Review by abailly-akamai — APPROVED** [review]
👍

**Review by mjac0bs — APPROVED** [review]

**Review by jaalah-akamai — APPROVED** [review]

**Review by cpathipa — APPROVED** [review]

**Pull request merged**
