### PR TITLE
M3-5691: Payment information panel tests

### PR DESCRIPTION
**Pull request by jdamore-linode**
## Description

**What does this PR do?**
Adds Jest tests for the `<PaymentInformation />` component and components upon which it depends.

## Notes & Known Issues
* One of the tests in `PaymentInformation.test.tsx` fails due to import issues with `react-number-format`, and is resolved by adding `"esModuleInterop": true` within `"compilerOptions"` in `tsconfig.test.json`. I declined to add that line to this PR because it's already added by [PR #8040, M3-5473: Webpack 5](https://github.com/linode/manager/pull/8040), which also includes a number of import statement fixes that are necessary to avoid more test failures caused by the config change -- let me know if anyone would prefer that to be added here

## How to test

**How do I run relevant unit tests?**
```
yarn test PaymentMethodRow.test ThirdPartyPayment.test BillingSummary.test CreditCard.test.tsx PaymentInformation.test
```

### CODE REVIEW

**Review by HanaXu — COMMENTED** [review]
One test is failing for me 🤔 

image

**Review by HanaXu — APPROVED** [review]

**Comment by bnussman** [comment]
Welp... changing that grant fixed your test, but broke another

**Comment by jdamore-linode** [comment]
> Welp... changing that grant fixed your test, but broke another

All good 😄 looking at that one now! Thanks for merging in develop and working out that initial MSW issue!

**Review by bnussman — APPROVED** [review]
Awesome job and solution for the MSW

**Pull request merged**
