### PR TITLE
Stripe progress bar and fix over progression

### LINKED ISSUE #711: Improve progress bar
Barber poll stripes

### PR DESCRIPTION
**Pull request by na3d**
Closes #711

### CODE REVIEW

**Comment by na3d** [comment]
screen shot 2016-12-01 at 11 03 17 am

**Comment by eatonphil** [comment]
Looks nice, but this should probably be keyframified because it does not currently solve the task of displaying progress when the bar is not moving.

**Comment by na3d** [comment]
Could you explain what you mean.

**Comment by eatonphil** [comment]
Use keyframe animation to make it look like the bar is spinning by lowering that diagonal over time. This way even while the progress bar is not moving, some visual indication of progress is still there.

**Comment by eatonphil** [comment]
Pulled it and it looks pretty cool! Nice work.

**Comment by na3d** [comment]
Thank you!

**Pull request merged**
