### PR TITLE
Fix our usage of sinon

### PR DESCRIPTION
**Pull request by SirCmpwn**

### CODE REVIEW

**Comment by eatonphil** [comment]
This looks good. Thanks for putting in the time here.

**Comment by eatonphil** [comment]
Could you clarify though what the issues were and why this solved them?

**Comment by SirCmpwn** [comment]
Our sandboxing wasn't done right, so if a test would create mocks or stubs and the test raised an exception, the rest of the tests would fail instead of just the one that was broken (since the stub isn't cleaned up and futher attempts to stub out the same thing will fail).

**Comment by eatonphil** [comment]
Got it. Much nicer. Is this ready for merging?

**Comment by SirCmpwn** [comment]
Yep.

**Comment by eatonphil** [comment]
:+1:

**Pull request merged**
