### PR TITLE
fix: [M3-8730] - Remove `@mui/system` imports

### PR DESCRIPTION
**Pull request by bnussman-akamai**
## Description 📝

- Believe it or not, this helps the pnpm effort 📦 
  - `@mui/system` is **not** in our `package.json` so we should not be importing it
  - When we are on pnpm, importing `@mui/system` will not work so we'll either have to install it or remove usage of it. This PR removes it because it seems to help with our TypeScript performance issues
- This should hopefully help TypeScript performance 🏎️ 
  - Seeing **24 second improvement** in Github Actions
  - Seeing **21 second improvement** locally on my Intel MacBook Pro
## Preview 📷

| Runner | Before  | After   |
| ------- | ------- | ------- |
| Intel MacBook Pro | Screenshot 2024-10-09 at 6 51 33 PM | Screenshot 2024-10-09 at 6 49 04 PM  |
| Github Actions | Screenshot 2024-10-09 at 6 57 55 PM | Screenshot 2024-10-09 at 6 57 38 PM | 

## How to test 🧪

- Verify the app still works and looks normal 🎨 
- Verify TypeScript performance is significantly better 🏎️ 

## As an Author I have considered 🤔

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by abailly-akamai — APPROVED** [review]
Awesome! great find and resolution

Screenshot 2024-10-10 at 09 27 55

done from ~80s after the few PRs merged and this one 🎉

**Comment by hkhalil-akamai** [comment]
Thanks for the clean up and great to see the performance improvements!

Noticing at least one regression in dark mode -- the menu icon renders in the light mode color even when in dark mode:

This Branch | Develop
-|-
Screenshot 2024-10-11 at 12 37 55 PM | Screenshot 2024-10-11 at 12 38 01 PM

**Comment by bnussman-akamai** [comment]
@hkhalil-akamai Fixed in c79402d

Dark mode was inhereting light theme's `color` so I just had to add a dark mode `color` to the dark theme. Also not sure why this PR's changes caused this, but It's likely due to using a different method to merge themes

**Comment by abailly-akamai** [comment]
> but It's likely due to using a different method to merge themes

it is - and likely to have a few more regressions. I did try to hunt but we know but nothing jumped so we should be good (we also have a sprint cycle to find more if any)

**Review by hkhalil-akamai — APPROVED** [review]
Thanks for addressing feedback, not noticing any additional dark mode regressions. 🚀

**Review by jaalah-akamai — APPROVED** [review]

**Review by dwiley-akamai — APPROVED** [review]
CM looks good ✅
Observed improvement in TS performance ✅
Code review ✅

**Pull request merged**
