### PR TITLE
M3-5451: Changes to Cluster Details for HA Clusters and Kubernetes Dashboard

### PR DESCRIPTION
**Pull request by codyfinn**
## Description

This PR adds functionality for HA clusters to manager. These additions are:

- [x] Upgrade to HA button
- [x] HA cluster chip

Also included is the new feature for all clusters to reach an external K8s dashboard:
- [x] External link button to K8s dashboard
The external link ti K8s dashboard does not render if the API returns an error or no URL.

## How to test

**What are the steps to reproduce the issue or verify the changes?**

You must include `REACT_APP_LKE_HIGH_AVAILABILITY_PRICE` in your env to see new features.

**How do I run relevant unit tests?**

### CODE REVIEW

**Review by HanaXu — APPROVED** [review]
Functionally LGTM, left some more UI feedback that we can address later

For mobile:
- Should we align the docs and upgrade button to the right, similar to `/kubernetes/clusters`?
- Remote the left margin on the delete cluster button.
    - Something else to consider, the delete cluster button is aligned to the top right on prod. Placing it under kubeconfig seems a bit odd and squishes a lot of actions together.

image

prod
image

Chip and delete button order is swapped on mobile. Chip font size looks jarring
image

Desktop Delete Cluster button alignment
image

**Review by tiffwong — COMMENTED** [review]
Functionality looks good but other than the UI stuff Hana mentioned, I found a couple others. Most of them can be addressed later but i'd say we should try to get the right chip styles in

- The chip and actions wrap too early imo
- After upgrading to HA, the "Kubernetes dashboard" link doesn't show up.
- The background color, border radius and font-size for the "HA Cluster" chip doesn't match the designs.

**Review by codyfinn — COMMENTED** [review]
Functionality looks good. I agree with the above UI issues

**Comment by HanaXu** [comment]
@tiffwong iirc, the dashboard button link is hidden for now since it's not available via the api

**Review by tiffwong — APPROVED** [review]

**Pull request merged**
