### PR TITLE
feat: [M3-8207] - Auto-close Stale Issues/PRs with Github Actions

### PR DESCRIPTION
**Pull request by bnussman-akamai**
## Description 📝

- Adds a Github Action to auto-close stale PRs
- Based on the [DX team's workflow](https://github.com/linode/linodego/blob/main/.github/workflows/stale.yml)

### CODE REVIEW

**Review by hkhalil-akamai — COMMENTED** [review]
Curious what the team thinks about closing PRs after 20 days -- did we already decide in cafe?

**Review by dwiley-akamai — COMMENTED** [review]
Should we exempt any labels like `Do Not Merge` or `Wait to Merge`?

**Comment by bnussman-akamai** [comment]
I'd be in favor of having no exceptions, but happy to add those exemptions if the team thinks we should

**Review by mjac0bs — APPROVED** [review]
My preference is to try it out like it's configured now, and then we can add some exceptions via tags if we find that good reason for it (e.g. there's actually PRs that need to be open for a long time for testing and it becomes annoying to bump it with a new comment saying that). It would be a good retro topic to check in on once this is part of our flow.

**Review by dwiley-akamai — APPROVED** [review]
I would be fine with giving this a go and tweaking as needed 👍🏾

**Pull request merged**
