### PR TITLE
fix: [M3-8563 & M3-8566] – Fix BSE capability for linodes & prevent unnecessary API request on Volume Create page

### PR DESCRIPTION
**Pull request by dwiley-akamai**
## Description 📝
- Change BSE capability for Linodes from `blockstorage_encryption` --> `Block Storage Encryption`
- Adjust `enabled` condition passed to `useLinodeQuery()` on Volume Create page so it is true only if `linode_id !== null`

## Target release date 🗓️
9/16/24

## Preview 📷
| Before  | After   |
| ------- | ------- |
| Screenshot 2024-09-11 at 10 55 05 AM | Screenshot 2024-09-11 at 11 01 21 AM |

### Prerequisites
Point at the dev environment with the `blockstorage-encryption` tag on your account

### Verification steps
On the Volume Create page, you should no longer see requests to `linode/instances/-1` before selecting a linode.

## As an Author I have considered 🤔
- [X] 👀 Doing a self review
- [X] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [X] 🤏 Splitting feature into small PRs
- [X] ➕ Adding a changeset
- [X] 🧪 Providing/Improving test coverage
- [X] 🔐 Removing all sensitive information from the code and PR description
- [X] 🚩 Using a feature flag to protect the release
- [X] 👣 Providing comprehensive reproduction steps
- [X] 📑 Providing or updating our documentation
- [X] 🕛 Scheduling a pair reviewing session
- [X] 📱 Providing mobile support
- [X] ♿  Providing accessibility support

### CODE REVIEW

**Review by bnussman-akamai — APPROVED** [review]
Looks good!

Should we update the `capabilities` type to be more strict than just `string`? 

https://github.com/linode/manager/blob/4d8a24113568ceee0a0a0e788915cacdb0e48461/packages/api-v4/src/linodes/types.ts#L22

**Review by mjac0bs — APPROVED** [review]
👍🏼  Extra requests are gone.

Unrelated to this PR, while testing, I did notice a console state error that's happening once a Linode is selected and the config loads - but only initially. This probably existed before BSE changes and can be its own ticket, but mentioning here in case you had any recent context.

https://github.com/user-attachments/assets/7a5c2e0b-764f-43b3-b28a-20737e716670

**Review by coliu-akamai — APPROVED** [review]
Confirmed extra requests to -1 are gone!

**Comment by dwiley-akamai** [comment]
> Unrelated to this PR, while testing, I did notice a console state error that's happening once a Linode is selected and the config loads - but only initially. This probably existed before BSE changes and can be its own ticket, but mentioning here in case you had any recent context.

Maybe it has something to do with the replacement of `Select` with `Autocomplete` a few months ago?

**Pull request merged**
