### PR TITLE
Edit SOA record and abstract some form modal components

### LINKED ISSUE #1145: Implement add / edit SOA record

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #1145

screen shot 2017-02-13 at 9 08 12 am

### CODE REVIEW

**Comment by mparke** [comment]
what's the diff between `secondary / slave` in the wording here?

**Comment by eatonphil** [comment]
@mparke not sure, mostly copying that from the CF manager.

**Comment by mparke** [comment]
gotcha, my understanding is they're synonymous. if we want to say slave, perhaps in parens, like `secondary (slave)`

**Comment by mparke** [comment]
Is `Default` in `Default (5 minutes)` redundant here being the default select option? 

can just be `5 minutes`

**Comment by mparke** [comment]
we should consider adding a toggle to `Advanced`, and default it to collapsed to simplify the form.

**Comment by eatonphil** [comment]
@mparke re: defaults, no I don't think it's redundant. In the CF manager there is an entire field dedicated to Default (with no label). So I think the idea is that even if you modify the field, you'll be able to know which one is the default so you can reset it to that.

**Pull request merged**
