### PR TITLE
Group and quantity options for Linode create

### LINKED ISSUE #235: Add group and quantity options to add a linode
Quantity is a number field - as it increases, more label fields are added for each linode. There should be some reasonable max.

Group should be a switch toggling between existing (which is a select of existing groups) and new (which is a text input).

### PR DESCRIPTION
**Pull request by SirCmpwn**
Closes #235

### CODE REVIEW

**Comment by eatonphil** [comment]
Very nice. In the second screenshot though where it has the lol-[1-4] placeholders, will it actually fill those out for you?

**Comment by eatonphil** [comment]
Where is the loading bar blue set?

**Comment by SirCmpwn** [comment]
>Very nice. In the second screenshot though where it has the lol-[1-4] placeholders, will it actually fill those out for you?

Yes

>Where is the loading bar blue set?

Dunno, whatever bootstrap does. It's a bootstrap progress bar.

**Comment by na3d** [comment]
Is that all of the tests you plan on including?

**Comment by SirCmpwn** [comment]
This exercises all code paths, I don't really know what else there'd be to test.

**Comment by na3d** [comment]
How about:
- [ ] Works without a group. (It looks like the tests include a group named group.)
- [ ] Does it test that auto generated labels work?

**Comment by SirCmpwn** [comment]
Good call, I'll add tests for both of those.

**Comment by SirCmpwn** [comment]
Bump

**Comment by na3d** [comment]
👍

**Comment by eatonphil** [comment]
👍

**Pull request merged**
