### PR TITLE
Disk from image

### LINKED ISSUE #2680: Create Disk from Image

### PR DESCRIPTION
**Pull request by na3d**
Adds Images to the distributions dropdown.

Closes #2680 

screen shot 2017-11-21 at 3 08 31 pm

### CODE REVIEW

**Comment by asauber** [comment]
When adding a disk from an image, the password prompt is displayed, implying that we are going to change the password on the image, this doesn't make sense.

screen shot 2017-11-17 at 5 07 42 pm

**Comment by asauber** [comment]
When the AddDisk modal is opened, the following warning is thrown.

Failed prop type: The prop `options` is marked as required in `_type`, but its value is `undefined`.

This appears to be the `options` prop of the `Select` inside `DistributionSelect`

**Comment by na3d** [comment]
@asauber there are multiple reasons for doing this.  May it be because of an image being years old, encouraging different passwords on systems, or continuity, because distros are going to become images as well.

**Comment by asauber** [comment]
Do we attempt to overwrite root passwords on Linodes created with user-created images?

**Comment by na3d** [comment]
We require it.

**Pull request merged**
