### PR TITLE
Fix #95

### LINKED ISSUE #95: Group/label edit should go away on page exit

### PR DESCRIPTION
**Pull request by SirCmpwn**
This closes the edit form when you leave the page. To implement this I
had to upgrade react-router, so this commit includes all of the changes
necessary for that as well. I also went ahead and updated our other
dependencies and there were no breaking changes in the rest of the
ugprades.

### CODE REVIEW

**Comment by eatonphil** [comment]
Looks good.

**Comment by eatonphil** [comment]
Ready for merge?

**Comment by SirCmpwn** [comment]
Yep.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
