### PR TITLE
M3-4169: Don't prompt users to save a password for a Linode that wasn't created

### PR DESCRIPTION
**Pull request by DevDW**
## Description
The challenge here is that, in Safari and possibly other browsers as well, when a user types out a password when creating a Linode and navigates elsewhere by clicking another tab or a link (e.g., the link to open a support ticket, if they receive that error message), the browser prompts them asking if they'd like to save that password, despite no Linode being created.

## Type of Change
- Bug fix ('fix', 'repair', 'bug')

### CODE REVIEW

**Comment by DevDW** [comment]
This first commit tries to address part of this by checking to see if the error message text matches on "support ticket," and if it does, the password field gets cleared out. However, this does not solve the problem.

Before this, my initial approach was to try passing a `shouldNotAutocomplete` prop down from `FromImageContent.tsx` --> `AccessPanel.tsx` --> `PasswordInput.tsx` --> `HideShowText.tsx` that would set autoComplete to 'off'. I intend to take another look at that, as well as investigate whether the `TextField` "type" attribute in `HideShowText.tsx` getting set to "text" instead of "password" could make a difference.

**Comment by Jskobos** [comment]
> This first commit tries to address part of this by checking to see if the error message text matches on "support ticket," and if it does, the password field gets cleared out. However, this does not solve the problem.
> 
> Before this, my initial approach was to try passing a `shouldNotAutocomplete` prop down from `FromImageContent.tsx` --> `AccessPanel.tsx` --> `PasswordInput.tsx` --> `HideShowText.tsx` that would set autoComplete to 'off'. I intend to take another look at that, as well as investigate whether the `TextField` "type" attribute in `HideShowText.tsx` getting set to "text" instead of "password" could make a difference.

Do we ever need autocomplete for our password forms? I don't know, just putting it out there. There are no "standard" password fields in Cloud, and no case where you're expected to type your Linode's current root password into a form. Maybe some people like autofill because they use the same root password for everything, but they really shouldn't do that.

**Comment by DevDW** [comment]
I've identified the key issue as being the `type` prop for `<TextField>`  in `HideShowText.tsx`; when it's set to "text," Safari doesn't prompt the user to save the password. However, when it's set to "text," the password masking breaks -- so adding conditional logic in there that sets it to "text" based upon a prop that gets sent down from higher up introduces that challenge.

**Comment by DevDW** [comment]
> I agree this is probably the best solution available, it looks good to go. You've done more research on this than I have, I'm curious why we're not putting the `autoComplete` directly on the native `<input />` element in `PasswordInput`. Does putting it on the `<form />` make it higher-priority?

I don't believe so; my understanding is that putting it at the `<form>` level sets it for all the inputs therein, but you can override what's set at the `<form>` level for individual inputs by specifying the attribute value on them. So for example, you could have a case of `autocomplete="on"` at the `<form>` level but have `autocomplete="off"` on an individual input if you wanted all of the form's inputs except the one specified to autocomplete.

But, it doesn't hurt to put it on the native <input> element too, so I added that as well

**Pull request merged**
