### PR TITLE
[CMR] M3-4206 pt2: Prevent text from being flush to the screen

### PR DESCRIPTION
**Pull request by tiffwong**
## Description
Created a separate PR to prevent scope creep and to handle adding margins to prevent standalone headings and buttons from being flush with the edge of the screen when the width is less than 1280px

## Type of Change
- Non breaking change ('update', 'change')

## Note to Reviewers
~~Wait for [M3-4206: Main content width](https://github.com/linode/manager/pull/6848) to be merged first~~

### CODE REVIEW

**Review by DevDW — COMMENTED** [review]
I noticed a couple of things on the NodeBalancers pages, although both seem to be existing UI bugs:

1. Row bottom border misalignment when name goes onto two lines
Screen Shot 2020-09-14 at 4 59 27 PM

2. NodeBalancer Details box nudged a bit higher above the first graph box
Screen Shot 2020-09-14 at 5 01 00 PM

Also, the StackScript header overflows on the right:

Screen Shot 2020-09-14 at 5 11 28 PM

**Review by johnwcallahan — APPROVED** [review]
Nice work! I looked through the code and each page of the app in CMR and non CMR views.

Below are a few things I noticed. Feel free to make a ticket to come back later.

**Profile:**
Screen Shot 2020-09-15 at 9 57 00 AM

**Support Ticket Landing:**
Screen Shot 2020-09-15 at 9 58 11 AM

**Search Landing:**
Screen Shot 2020-09-15 at 9 58 35 AM

**Review by WilkinsKa1 — COMMENTED** [review]
Nice work on this! In addition to what others have noticed, just a few other headings that will need to be addressed: 
• Linode Details- Backups/Activity Logs/Settings tabs
Screen Shot 2020-09-15 at 10 33 29 AM
• Longview's headings (all tabs) 

If it's easier to address separately (and since this was a bit of an add-on from your other ticket, we could open a separate task to capture all this feedback)

**Comment by tiffwong** [comment]
@DevDW @johnwcallahan @WilkinsKa1 thanks for reviewing this behemoth and I'll open a separate task to address all the feedback since this PR is already quite gnarly

**Pull request merged**
