### PR TITLE
M3-2319 Update: Summary Panels in Sidebar

### PR DESCRIPTION
**Pull request by alioso**
## Summary Sidebar

This PR implements a new UI pattern in which we feature the summary panel in a new sidebar. It was a major rework in order to move the TagsPanel in there as well. 

This pattern is implemented for the following entities:
- linodes
- nodebalancers
- domains
- account

## Type of Change
- Non breaking change ('update')

## Note to Reviewers

linodes/[id]/summary
/nodebalancers/[id]/summary
domains/[id]/records
/account/billing

### CODE REVIEW

**Comment by rulikrulit** [comment]
Non-blocking but there is a weird bug with paypal. Steps to reproduce:
1. Click "PayPal" radio
2. Press "tab" 3 times
3. Click enter
4. Observe paypal button disappear

**Comment by rulikrulit** [comment]
Another non-blocking comment is that our forms are not actually forms. It's a potential accessibility issue and also it doesn't allow you to submit form with "Enter" button. I would suggest wrap them all with forms and move submit button event to form submit event

**Comment by rulikrulit** [comment]
There are two h1s on the page. This is a blocking comment.
screen shot 2019-02-04 at 9 02 39 am

**Comment by alioso** [comment]
@rulikrulit fixed the headers

**Pull request merged**
