### PR TITLE
Fix: [M3-6800] Firewall custom port validation

### PR DESCRIPTION
**Pull request by abailly-akamai**
## Description 📝
The previous validation for firewall custom ports made use of a regex that was not encompassing the same conditions as what the validation was doing sever-side. 

In order to fix this in a more permanent manner, I more closely matched the API validation on the client and returned the same error messages for better feedback for the user. I also added test cases to reflect these new changes. 

Screenshot 2023-06-28 at 4 23 35 PM

## How to test 🧪
1. Navigate to an existing firewall or create a new one
2. Click on the "Add an Outbound Rule" (or "Inbound"), follow a similar config as the screenshot above, and hit the "Custom Port Range" fields with a lot of combinations making sure it passes or fails properly (you can use the examples in the updated test for example
3. Click on Add Rule with a valid port/port range
4. When drawer close, hit save and confirm the value saved properly without an API error (client and API validation should always match!)

### CODE REVIEW

**Review by bnussman-akamai — APPROVED** [review]
Looks good! 🚀

I could see people entering a range like `1 - 2` with spaces, so it would be nice if we could somehow tell users to not put spaces. We can worry about this down the road if we need to. 

Screenshot 2023-06-29 at 9 46 46 AM

**Review by mjac0bs — APPROVED** [review]
Validation worked for everything I threw at it and looks like it matches API. 

As a side note: 'Port must not have leading zeroes' isn't the most helpful error message if the user doesn't have any zeroes and the problem is something like including `;` as delimiters rather than commas (since we don't specify how to format) or the spaces as Banks showed above, but at least it does error. I wonder if using something like "Ports must be an integer, range of integers, or a comma-separated list of integers." for the field's placeholder text would be more transparent.

**Comment by abailly-akamai** [comment]
@bnussman-akamai @mjac0bs thanks for the review! agreed with feedback and pushed a small change to have the leading zero show up only for that particular case, otherwise users will get the more generic error. All other feedback is unchanged

**Review by cpathipa — APPROVED** [review]
LGTM! validations are working as expected.

**Pull request merged**
