### PR TITLE
fix missing shrinkwrap update

### PR DESCRIPTION
**Pull request by mparke**
missed in https://github.com/linode/manager/pull/1492

make sure to do a fresh npm install

### CODE REVIEW

**Comment by mparke** [comment]
oops...something wrong here, will re-open

**Comment by eatonphil** [comment]
Is this for the bootstrap change? If so, thanks and sorry about that.

**Comment by mparke** [comment]
yeah, it's no problem I missed it reviewing too. need to do a quick manual test on this some other versions got bumped too

**Comment by mparke** [comment]
everything looks normal,

a couple new deprecation warnings with a react bump:

https://github.com/facebook/react/releases/tag/v15.5.0

**Comment by eatonphil** [comment]
Oh great, I forgot we were tracking the latest minor version. Should be fine for this version for now.

**Pull request merged**
