### PR TITLE
test: [M3-8147] - Confirm refactored Linode Create flow with Firewalls attached

### PR DESCRIPTION
**Pull request by AzureLatte**
## Description 📝
Add Cypress integration tests using mock API data to confirm refactored Linode Create flow with Firewalls attached

## Changes  🔄
- Add new test in e2e packages/manager/cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts
- Add new intercepts functions in packages/manager/cypress/support/intercepts/firewalls.ts
- Update TODO comment to confirm toast notification should appear on Linode create.

## How to test 🧪
```
yarn cy:run -s "cypress/e2e/core/linodes/*"
```

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by hkhalil-akamai — APPROVED** [review]
These tests are looking good and passing in CI.

For some reason, I can't get them to pass locally which may be due to a misconfiguration on my end. Looking at the videos, it seems like the tests get stuck when trying to select a region. Typing the region's id, like 'us-east{enter}' causes a "No results" error which blocks the rest of the create flow:

Screenshot 2024-07-16 at 4 26 37 PM

Do you or @jdamore-linode have any suggestions for getting these to pass locally?

**Comment by AzureLatte** [comment]
Screenshot 2024-07-18 at 1 19 47 PM
Somehow I am unable to reproduce the issue above. Tried `repeat 10` and everything looks fine.
I will take a further look though.

**Review by cliu-akamai — APPROVED** [review]
Passed in local

**Comment by AzureLatte** [comment]
I'm going to merge the PR as test passed in latest integration tests. Will create a new ticket is the issue still exists.

**Pull request merged**
