### PR TITLE
describe paravirt and fullvirt

### PR DESCRIPTION
**Pull request by asauber**

### CODE REVIEW

**Comment by displague** [comment]
I would argue that we should match the existing controls that follow a similar pattern (on the same page):
image

**Comment by asauber** [comment]
@displague updated to use bootstrap styles instead of custom styles

**Comment by displague** [comment]
I'm merging this as-is, but while trying to make this section more responsive (like the checkboxes below) I realized these text labels don't describe the options they are next to.  These new text labels are actually a single description of this fieldset.

**Comment by displague** [comment]
I also would have preferred these text additions to be `<small className="text-muted">`, but since I later realized these aren't actually element descriptions, I didn't hold the task up.

**Pull request merged**
