### PR TITLE
Remove linode prefix from sass variables

### PR DESCRIPTION
**Pull request by eatonphil**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
:-1: 

I like the linode- prefix. It makes it a little more clear imo.

**Comment by eatonphil** [comment]
I think it's silly - of course it's linode.

**Comment by SirCmpwn** [comment]
Brought in a second opinion who agrees with you. Will merge once conflicts are fixed.

**Comment by eatonphil** [comment]
Thanks!

**Pull request merged**
