### PR TITLE
change: [M3-8175] - Refactor KubeConfigDrawer to use CodeBlock and add Codeblock story

### PR DESCRIPTION
**Pull request by hana-linode**
## Description 📝
Refactor KubeConfigDrawer component to use the CodeBlock component for UI consistency. I also moved CodeBlock to the components folder since it is pretty generic and added a story for it

## Changes  🔄
List any change relevant to the reviewer.
- Refactor `KubeConfigDrawer` to use `CodeBlock` component and minor cleanup
- Moved `CodeBlock` from `features` to `components` folder and decoupled it a bit from Linode Create
- Added `CodeBlock` story

## Preview 📷
(info has been obscured)
| Before  | After   |
| ------- | ------- |
| image | image |

image

### Verification steps
(How to verify changes)
- Create a cluster pointing to dev API
- Once the cluster is provisioned, go to the cluster's details page
- Click on View under Kubeconfig
- Confirm new UI and no regressions
- Delete the cluster afterward

- Run storybook locally and confirm CodeBlock story

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [x] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Comment by coliu-akamai** [comment]
heads up - there's a few conflicts that need to be resolved

**Comment by hana-linode** [comment]
@coliu-akamai thanks for the heads-up! Just rebased with develop to resolve conflicts

If you run into issues pulling, you might need to delete your pulled down branch and `gh pr checkout 11019` again

**Review by harsh-akamai — APPROVED** [review]
PR looks good! 👍

**Comment by coliu-akamai** [comment]
just saw this console error this when closing the View codeblock drawer for the Kubeconfig:

image

**Pull request merged**
