### PR TITLE
sub-headers for add/edit config

### LINKED ISSUE #835: Break out Edit/Add config into multiple sections like current Manager

### PR DESCRIPTION
**Pull request by na3d**
Closes #835

### CODE REVIEW

**Comment by eatonphil** [comment]
Screenshot?

**Comment by na3d** [comment]
screen shot 2017-01-04 at 5 10 44 pm

**Comment by eatonphil** [comment]
Pulling locally for review

**Comment by eatonphil** [comment]
Could we please drop the overly redundant first two sub-headers?

**Comment by na3d** [comment]
I absolutely agree, this was a very specific adamant request though.

**Comment by eatonphil** [comment]
Would you take a screenshot without the first two headers just for the sake of review?

**Comment by na3d** [comment]
screen shot 2017-01-05 at 11 10 42 am

**Pull request merged**
