### PR TITLE
Add volumes to advanced page

### LINKED ISSUE #1943: fix domains > NS record actions alignment, should be right aligned

### LINKED ISSUE #2203: Implement create and edit volume modal

### LINKED ISSUE #2207: Add Volume section to Linode -> Settings -> Advanced page

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #2203, closes #2207, closes #1943

TODO:
* [x] Test add modal
* [x] Test edit modal
* [x] Test configs list
* [x] Test delete configs
* [x] Test disks lists

screen shot 2017-08-09 at 6 04 20 pm
screen shot 2017-08-09 at 6 04 28 pm

### CODE REVIEW

**Comment by eatonphil** [comment]
screen shot 2017-08-10 at 5 58 44 pm

**Comment by displague** [comment]
This appears to work as described.  I think the interface here could be better, but perhaps that should be deferred.

For example:

"Add a Disk" should be a drop down that lets you create a disk from clone, image, backup, or create a disk.

"Add a Volume" should be a drop down that includes: "Create a Volume" (the modal would preselect this linode), followed by a list of volumes in this datacenter (or a "Attach a Volume" option that opens another modal).

**Comment by displague** [comment]
The syntax highlighter is picking up labels in the shell commands offered by the Volumes dialog:
image

**Comment by displague** [comment]
Adding a volume with a name that builds off of the name of an existing volume causes the existing volume to be replaced in the Volumes list with the new volume.

Create a volume called "Test".  
"Test" appears in the Volume list.
Create a volume called "Testing".  
The latter will replace the former in the Volume list.
Refreshing clears the listing up.

**Pull request merged**
