### PR TITLE
M3-4837 Change: Delete most notification sections and related logic

### PR DESCRIPTION
**Pull request by Jskobos**
## Description

Fun trip down memory lane here.

### CODE REVIEW

**Review by DevDW — APPROVED** [review]
LGTM -- is the chronological view logic still needed in `NotificationDrawer.tsx`?

**Review by johnwcallahan — APPROVED** [review]
☠️

**Comment by johnwcallahan** [comment]
Also, @DevDW is right here that we don't need the chronological display.

**Review by tiffwong — APPROVED** [review]
RIP

**Pull request merged**
