### PR TITLE
Update rebuild and resize page

### LINKED ISSUE #1629: Ubuntu 16.04 is hard-coded as default selected distribution on Rebuild page
It probably shouldn't be.

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #1629

screen shot 2017-08-15 at 11 25 44 am
screen shot 2017-08-15 at 11 34 32 am

### CODE REVIEW

**Comment by eatonphil** [comment]
@na3d thanks! Fixed up. @TheSchwa this includes changes you worked on so you should get some commit credit for the initial work. Thank you!

**Comment by displague** [comment]
Hitting "Rebuild" before selecting a "New Distribution" yields: "RebuildPage.js:51 Uncaught (in promise) TypeError: Cannot read property 'label' of undefined"

**Comment by eatonphil** [comment]
@displague try rebuilding components? I cannot reproduce.

**Comment by displague** [comment]
I pulled latest and rebuilt.  Same error.

The only distribution available in my environment is the one the disk is already configured with. 

---

image

image

**Pull request merged**
