### PR TITLE
M3-4128 Refactor User details, NodeBalancer details, Profile, Longview landing and details

### PR DESCRIPTION
**Pull request by WilkinsKa1**
## Description
Edit: This also introduces a new component, `SafeTabPanel` that will only render content based on active tab selection (thanks @johnwcallahan for this addition!)

Switching over to the Reach pattern for the above sections + cleanup. 

## Type of Change
- Non breaking change ('update')

## Note to Reviewers

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

### CODE REVIEW

**Comment by johnwcallahan** [comment]
@WilkinsKa1 I looked a bit more into the issue I mentioned above. I think we could solve this with a custom `TabPanel` component:

```ts
// Only renders its children when the tab is selected.
const _TabPanel: React.FC<{ index: number } & TabPanelProps> = props => {
  const { index, ...tabPanelProps } = props;

  const { selectedIndex } = useTabsContext();
  const isSelected = selectedIndex === index

  return (
    <TabPanel {...tabPanelProps}>
      {isSelected ? props.children : null}
    </TabPanel>
  );
};
```

Then, in the `<TabPanels/>` sequence:

```ts
<TabPanels>
  <_TabPanel index={0}>
    <DisplaySettings />
  </_TabPanel>
  <_TabPanel index={1}>
    <AuthenticationSettings />
  </_TabPanel>
  {/* ...etc */}
</TabPanels>
```

It's not as fast moving between tabs of course, but it makes initial load quicker and doesn't request a ton of data we might not need,

**Comment by WilkinsKa1** [comment]
@johnwcallahan I like that idea alot! I can work on that- would we apply this new component anywhere we're not using the TabbedPanel component, I'm thinking?

**Comment by WilkinsKa1** [comment]
I apologize for the scope change in this PR- I wanted to see if the TabPanel abstraction would fix the Longview issue mentioned in the PR referenced above, looks like it does! I did have to do some strange checking for conditional tabPanels (LV apps) but there is likely a much better way to handle this.

**Comment by johnwcallahan** [comment]
> would we apply this new component anywhere we're not using the TabbedPanel component, I'm thinking? 

I think anywhere we are requesting data when a component mounts. If it's a simple component that is purely presentation, we could get by with the regular TabPanel and there'd be a slight performance benefit in doing so.

**Pull request merged**
