### PR TITLE
limit coveralls from styleguide dir

### PR DESCRIPTION
**Pull request by abemassry**

### CODE REVIEW

**Comment by briansteffens** [comment]
Regarding the parser script, at the very least it should be named something more specific than ```parser.js```. As to its location, maybe ```test/``` would make sense? Or ```test/bin/``` or just ```bin/```. I'm not really sure. It stands to reason we'll have more one-off scripts like this in the future so making a bin directory somewhere shouldn't be a problem.

**Comment by abemassry** [comment]
I like the bin/ idea. For the filename how about bin/styleguideTestFilter.js ?

**Comment by briansteffens** [comment]
Sounds pretty good, any thoughts @ndodson @mparke ?

**Comment by mparke** [comment]
+1 /bin

**Pull request merged**
