### PR TITLE
fix: `create-volume.spec.ts` and `dynamicPricing.test.ts`

### PR DESCRIPTION
**Pull request by bnussman-akamai**
## Description 📝
- Fix `create-volume.spec.ts` by selecting the Region select differently. The copy was being selected because it now contains "Select a Volume" after changes in https://github.com/linode/manager/pull/9569

## How to test 🧪
- `yarn cy:debug`
- Run `create-volume.spec.ts`

### CODE REVIEW

**Review by abailly-akamai — APPROVED** [review]
TY 👍

**Comment by abailly-akamai** [comment]
@bnussman updated the failing unit test as well in there. It needs to be dynamic (will do a follow up) but going for the quick turnaround now

**Comment by bnussman-akamai** [comment]
Thanks! You beat me to it! @abailly-akamai

**Comment by bnussman-akamai** [comment]
Really struggling to get e2es to run in jenkins todat. Looking for 1 more approval

**Pull request merged**
