### PR TITLE
feat: [M3-8185] - Add Accessibility tab to Storybook Stories

### PR DESCRIPTION
**Pull request by hana-linode**
## Description 📝
We could utilize Storybook more. One way we could do that is by using it for Accessibility testing when developing a component

## Changes  🔄
- Add Accessibility tab to Stories

## Preview 📷
https://github.com/user-attachments/assets/a61c8030-63f0-4a0c-8524-30bb841b8253

### Verification steps
(How to verify changes)
- Pull this PR and run storybook locally
- Open a Story and you should see a new Accessibility tab

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

### CODE REVIEW

**Review by abailly-akamai — APPROVED** [review]
I like the accessibility addition! Provides some useful context.

The interactions I could do without, but also it does not bother me

One thing i noticed is that when landing on of of those new CopyableFields stories the CTA is triggered without a click, which is rather unexpected. Prob something we'd want to present.

https://github.com/user-attachments/assets/7d7fefee-7505-48bc-b4b8-1c589106ffbb

**Comment by hana-linode** [comment]
@abailly-akamai Yeah, unfortunately there's no way to turn the autoplay off. I'll bring this up in Cafe to see if it's worth keeping!

**Review by hkhalil-akamai — APPROVED** [review]
Echoing @abailly-akamai's comment. I like that this will give more attention to accessibility issues. Interactions seem unnecessary except possibly for complex/non-obvious components.

**Comment by hana-linode** [comment]
Thanks for the feedback! I split the Interactions/Component testing to a separate PR https://github.com/linode/manager/pull/10974 and will just merge the accessibility addition in this PR

**Pull request merged**
