### PR TITLE
M3-368 Add 'Unknown Image' to Linode Card

### PR DESCRIPTION
**Pull request by Jskobos**
**Purpose**

Add an "Unknown Image" label to Linode Card
when a Linode's image name is unavailable
(images no longer supported by the API)

* Add label
* Refactor Lambda methods in render()
* Fix linter warnings

### CODE REVIEW

**Comment by martinmckenna** [comment]
Per @jamesottinger, we can differentiate between Linodes with no images (`{image: 'old-image-label'}` from the API) and Linodes with non-supported images (`{image: null}` from the API). The question is whether we want to have a catch-all and just display _unknown image_ to the user or do we want to display _unknown image_ and _no image_ to the user.

I think the latter is more helpful.

@rjstires @asauber

**Comment by jamesottinger** [comment]
The image will be filled out if the Linode was originally created from an image that was a distro image (with the image at time of creation), otherwise is it null. If the image is returned, it may or may not still be available. POST /linode/instances (create Linode) checks if images are still available upon reuse.

**Comment by asauber** [comment]
per @rjstires note that the code in the above comment is pseudocode, and we may be swallowing the `null` value in a higher context

**Comment by rjstires** [comment]
@asauber so the image is selected in LinodesGridView. It kind of makes sense, too, that instead of sending "the image" we do this logic further up the DOM and just send "the image label" (whatever that may be).

**Comment by martinmckenna** [comment]
while we're at it, let's implement the last commit in the Linode Summary as well

**Comment by rjstires** [comment]
@martinmckenna make a card for no image in summary please. Closing/merging.

**Pull request merged**
