### PR TITLE
M3-4567 Update Dark Theme Styling

### PR DESCRIPTION
**Pull request by WilkinsKa1**
## Description

This introduces dark theme styling for CMR components, mostly impacting dashboard, landing views, and Linode Details. Please have a look through, toggling both views and check for anything glaringly wrong. While this does touch a lot of files, it is by no means comprehensive and some older DT styles (form elements, other non CMR components, etc.) will need to be updated probably post-GA at some point, when we're able to modify core theme styles.

## Type of Change
- Non breaking change ('update')

## Note to Reviewers

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

### CODE REVIEW

**Review by tiffwong — APPROVED** [review]
Great work!

I found a few things that were already there but highlighted when I was looking through the site with dark mode. 

We can address these in another ticket but just wanted to have these noted down somewhere:
- We should increase the contrast between the active tab and the rest 
- Missing the top border on the last column
  Screen Shot 2020-10-07 at 11 24 34 AM
- The center of the Kubernetes logo is filled in in the dark version, not sure if this is intentional or not
  Screen Shot 2020-10-07 at 11 25 53 AMScreen Shot 2020-10-07 at 11 26 03 AM
- We just got another ticket from a customer having issues with not enough contrasts in the colors used in the graphs on dark mode so we should address that at some point as well 😬

**Review by DevDW — APPROVED** [review]
Great work! I noticed a couple of things:

1. The black line above "No Tags" in dark mode; there doesn't appear to be a corresponding one in light mode -- seems like it shouldn't be there
Screen Shot 2020-10-08 at 5 40 59 PM

Screen Shot 2020-10-08 at 5 41 15 PM

2. In our modals in dark mode, the modal title is contained within an element that is lighter than the rest of the modal background, which looks a bit odd to me.
Screen Shot 2020-10-08 at 5 46 35 PM

Screen Shot 2020-10-08 at 5 46 46 PM

**Review by johnwcallahan — COMMENTED** [review]
The borders of the processes table rows look better, but I'm seeing this on Chrome (and not FF):
Screen Shot 2020-10-09 at 8 26 10 AM

**Comment by WilkinsKa1** [comment]
Thanks all for the feedback! All should be addressed now, with exception of the icon and contrast issues. @tiffwong I ran an audit and we're still failing a11y standard for contrast (both themes) Pat will be prioritizing that work after icons so will likely have a follow up task to address that specifically!

**Pull request merged**
