### PR TITLE
Progress bar

### LINKED ISSUE #551: Implement progress bar

### PR DESCRIPTION
**Pull request by abemassry**
Here is my first attempt at a progress bar, this uses rc-progressbar right now which might be replaced by something custom and simple very soon.

Closes #551

### CODE REVIEW

**Comment by na3d** [comment]
screenshot or it didn't happen

**Comment by eatonphil** [comment]
Could you drop your two webengage commits? They will be taken care of by #606

**Comment by abemassry** [comment]
screen shot 2016-10-31 at 4 10 30 pm
screen shot 2016-10-31 at 4 10 56 pm

**Comment by abemassry** [comment]
comment updated ^

**Pull request merged**
