### PR TITLE
Billing page stub

### LINKED ISSUE #1408: Add billing page placeholder
Placeholder needs appropriate messaging

### PR DESCRIPTION
**Pull request by mparke**
closes #1408 

Moves active tab calculation into Tab component

screen shot 2017-03-21 at 12 50 44 pm

### CODE REVIEW

**Comment by na3d** [comment]
Do we need the tab, since it is just a placeholder page where there are no other tabs to go to?

**Comment by eatonphil** [comment]
I'd vote drop the tab and the extra padding and centering IMO

**Comment by mparke** [comment]
tab is only based on mockups, I could drop it.

If this is the only thing on this page, a little padding + centering goes a long way no?

**Comment by eatonphil** [comment]
My comments stay the same for now. :) But I'm fine to be voted out of either.

**Comment by na3d** [comment]
Keep centered, since when NB is empty, it is centered.

**Comment by eatonphil** [comment]
> Keep centered, since when NB is empty, it is centered.

Then could we use the CreateHelper style here instead?

**Comment by mparke** [comment]
Updated `CreateHelper` scss to be called `BlankSlate` to be generic, and just swapped the classes in `CreateHelper.js`

Adding padding to give it some space from the top

Billing now:
screen shot 2017-03-22 at 10 10 20 am

Create Helper Example now:
screen shot 2017-03-22 at 10 11 39 am

**Comment by mparke** [comment]
coveralls is throwing an error in travis here?

**Comment by na3d** [comment]
Yeah, tests are having issues.  It still looks weird with that tab, and it will look better in a card, especially when the nav goes to the top.

**Comment by mparke** [comment]
trying not to flip flop on styles in the pull, so I made an issue: https://github.com/linode/manager/issues/1439

**Comment by eatonphil** [comment]
Cool, thank you!

**Pull request merged**
