### PR TITLE
dont display backup ids in select

### LINKED ISSUE #2450: Restore from Backups should use dates or snapshot labels (not ids)
image

### PR DESCRIPTION
**Pull request by na3d**
Closes #2450 

screen shot 2017-09-22 at 3 11 44 pm
The reason the weeklies are saying a month ago is because the backups aren't running on that Linode.

### CODE REVIEW

**Comment by rmcintosh** [comment]
I feel like it would be better if we were more specific than "a month ago" which to me is really ambiguous...

I'm also a little confused by the snapshot saying "in 4 hours" - does that not suggest a snapshot from the future?

**Comment by na3d** [comment]
@rmcintosh the description below the image explains the "a month ago" part, it normally is more specific.  Also you can talk to @jfrederickson about the in 4 hours, haha.

**Comment by rmcintosh** [comment]
ah - what would it normally say there? x days ago? That would be better, although it would be nice to see the specific date somewhere - people oftentimes need to restore their backups based on a time period as specific as minutes/hours, so that information may play a role in whether they choose to restore at all...

point well taken RE: @jfrederickson 😜

**Comment by na3d** [comment]
Yeah, it is normally x days ago.  I am not against the DT, maybe "Relative (DT)", since we default to relative everywhere in Beta, and have hover to see exact DT.

**Comment by jfrederickson** [comment]
...oops. 🙃

**Comment by eatonphil** [comment]
This looks like it does not respect the user's chosen timezone? We should not ignore that.

**Comment by na3d** [comment]
Timezone only matters for absolute time, not relative.

**Comment by eatonphil** [comment]
doh! Jet lag.

**Pull request merged**
