### PR TITLE
Remove heebo and darken yellow

### PR DESCRIPTION
**Pull request by eatonphil**
I noticed by chance that Heebo didn't show up in a production build because nginx wasn't configured to serve fonts. I think the default font looks better than Heebo. So I'm reverting it. Also, here is a darker yellow.

screen shot 2016-07-12 at 4 10 00 pm
screen shot 2016-07-12 at 4 10 10 pm

### CODE REVIEW

**Comment by SirCmpwn** [comment]
What if we did the blue, but on the distro selection that looked like a blue inset border instead of the whole background? Avoids conflict with arch logo.

**Comment by eatonphil** [comment]
Light blue?
screen shot 2016-07-12 at 4 19 38 pm
screen shot 2016-07-12 at 4 20 12 pm

**Comment by SirCmpwn** [comment]
+1

**Comment by eatonphil** [comment]
The yellow has more contrast against the blue links and the red (and green) statuses though.

**Comment by SirCmpwn** [comment]
The blue also doesn't look like urine.

**Pull request merged**
