### PR TITLE
Add create from backup

### LINKED ISSUE #2349: Create from backup

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #2349 
screen shot 2017-08-06 at 3 42 21 pm

### CODE REVIEW

**Comment by na3d** [comment]
Shouldn't create from backup, the plan default to the size of the Linode it was backed up from?

**Comment by na3d** [comment]
Can you create from backup into a different data DC?

**Comment by eatonphil** [comment]
@na3d to both questions: I don't think it actually matters.

**Comment by na3d** [comment]
Shouldn't be able to create from backups on a Linode that has backups disabled, right?

**Comment by eatonphil** [comment]
@na3d no, this line should be filtering those out: https://github.com/linode/manager/pull/2380/files#diff-e3e74d778d99d0add40c91af885b8c21R77. Is that not the case?

**Comment by eatonphil** [comment]
Thank you!

**Pull request merged**
