### PR TITLE
fixed nodebalancer ssl settings placeholder color

### LINKED ISSUE #2179: NodeBalancer - Helper text font color change for SSL Settings section
The helper text for SSL Settings --> SSL Certificate and Private Key are not the same as the other fields 

FROM:
#8E8E8E

TO:
#ACACAC

image

### PR DESCRIPTION
**Pull request by ryan-hughes**
Closes #2179 

This is my first pull request! Please let me know if something needs to be changed or added.

### CODE REVIEW

**Comment by eatonphil** [comment]
Thanks! Two things: 1) could you make this pr against the `develop` branch instead of `master` and 2) could you delete these lines from inside the `.Input` section in `components/scss/components/forms/Input.scss`?

**Comment by eatonphil** [comment]
If this is doing what I think it is then it will also close #1684.

**Comment by ryan-hughes** [comment]
Closes #1684 now.

Added the rules to the .form-group class, and now the placeholder text is the same color for Input and textarea boxes.

**Comment by abemassry** [comment]
Tested, looks good

**Comment by eatonphil** [comment]
LGTM. Thank you!

**Pull request merged**
