### PR TITLE
Initial implementation of d3 charts

### PR DESCRIPTION
**Pull request by SirCmpwn**

### CODE REVIEW

**Comment by eatonphil** [comment]
Could you post a screenshot?

**Comment by SirCmpwn** [comment]
Not too concerned about the test coverage until we have real data to plug into this.

**Comment by eatonphil** [comment]
Are you choosing the scale? I assume D3 must be able to guess a good y scale.

**Comment by SirCmpwn** [comment]
Yes, I'm choosing the scale. For CPU% I picked 0...100.

**Comment by eatonphil** [comment]
Cool. Nice work. Ready for merge then?

**Comment by SirCmpwn** [comment]
Yep.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
