### PR TITLE
Replace direct sinon calls with sandbox

### PR DESCRIPTION
**Pull request by eatonphil**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
LGTM

**Comment by eatonphil** [comment]
If there are nested describes, I'm assuming the sandbox must be on the inner-most one if there are multiple tests there?

**Comment by SirCmpwn** [comment]
Yes, if you need the sandbox cleaned up for each of those tests, I think.

**Comment by eatonphil** [comment]
I'm not a big fan of the nested describes so far. Looks like tests are failing. Just a sec.

**Comment by SirCmpwn** [comment]
Nested describes is an advertised feature of Mocha and a Good Thing imo.

**Comment by eatonphil** [comment]
*shugs*

**Comment by SirCmpwn** [comment]
Example:

    linodes/actions
      changeView
        ✓ should return a CHANGE_VIEW action
      toggleSelected
        ✓ should return a TOGGLE_SELECTED action
      toggleSelectAll
        ✓ returns a function
        ✓ should call getState() once
        ✓ should call dispatch({ action }) once

**Comment by eatonphil** [comment]
Yeah that's pretty, but I don't like how the tests are written.

**Comment by SirCmpwn** [comment]
I guess it just comes down to a difference of opinion, then.

**Comment by SirCmpwn** [comment]
Ready to merge?

**Comment by eatonphil** [comment]
Yep. And yep

**Comment by eatonphil** [comment]
thanks

**Pull request merged**
