### PR TITLE
Convert Support ticket drawer to a dialog and make inputs bigger

### PR DESCRIPTION
**Pull request by Jskobos**
## Description

Customers had mentioned that they don't always have enough room to fill out ticket text. Expanded everything to improve the situation.

### CODE REVIEW

**Review by johnwcallahan — COMMENTED** [review]
I think this works well in the modal, much more room to write.

I don't think the existing SupportTicketLinks are working correctly. That brings up the question: should opening this modal update the URL (and should we handle that route?) e.g. support/tickets/create.

Another potential risk is that the "Submit" button isn't visible unless you scroll down (on my monitors, at least). I can't really think a solution without moving things around substantially. Maybe it's fine, curious to hear your thoughts.

**Review by tiffwong — APPROVED** [review]
I don't' have a problem seeing the "Submit / Open Ticket" button but maybe we can decrease the height of the description by default but allow the user the adjust that if they want to

**Review by DevDW — APPROVED** [review]
LGTM -- I'm also able to see the `Open Ticket` button without scrolling

**Comment by Jskobos** [comment]
I'm locked out of JIRA again but once I get back in I'll open a ticket for adding the resizable textarea. I looked into it and it'll take a bit of work to match the styles etc.

**Pull request merged**
