### PR TITLE
Filtering

### LINKED ISSUE #232: Add support for filtering to api-store
We should be able to apply a filter to any API store. We could then invalidate the cache and use the existing functions to start getting information back for these.

### PR DESCRIPTION
**Pull request by SirCmpwn**
Closes #232

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Ready for review. I was going to add a test to make sure the filter header was included but that seems trivial and would be complicated to implement.

**Comment by eatonphil** [comment]
Could you maybe implement one use of this somewhere?

**Comment by SirCmpwn** [comment]
I don't really know of a place where it'd be appropriate to use filters at the moment.

**Comment by SirCmpwn** [comment]
Actually I can add this for backups.

**Comment by SirCmpwn** [comment]
So I finally have a linode with backups to test this with... and the API doesn't support filtering against linodes with backups enabled. I mentioned it to @Dorthu, he'll look into it, but I removed [WIP] since I don't want to be blocked by that.

**Comment by eatonphil** [comment]
Unfortunate there is not an example of this in use yet, but I'm still ok with the rest of it.

**Pull request merged**
