### PR TITLE
DBaaS1-89: Add factories and mocks for DBaaS

### PR DESCRIPTION
**Pull request by DevDW**
## Description
Add factories & mocks for DBaaS

## How to test
Multiple factories and server handlers were added, but as of right now you can only visit the Databases landing page and see mocks (not any Database Detail pages). The old code is still wired up via Redux; since the files containing or touched by that old code will be deleted or refactored shortly since we'll be using React Query for this, I touched those files as minimally as possible, just enough to get the Databases landing page mocks working.

### CODE REVIEW

**Review by HanaXu — COMMENTED** [review]
Mocks LGTM, I am seeing an issue with the tags dropdown positioning though

image

**Comment by DevDW** [comment]
> Mocks LGTM, I am seeing an issue with the tags dropdown positioning though
> 
> image

The landing table that displays is from the old DBaaS code/iteration; the new table won't have tags show up at all

**Review by HanaXu — APPROVED** [review]
🚢

**Review by tiffwong — APPROVED** [review]
LGTM 🎉

**Review by bnussman — APPROVED** [review]

**Review by bcmertz — APPROVED** [review]

**Pull request merged**
