### PR TITLE
Drop LISH_ROOT

### LINKED ISSUE #1794: Lish root cannot be based on a single constant

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #1794

### CODE REVIEW

**Comment by eatonphil** [comment]
@mparke probably because I haven't rebased. Rebasing now.

**Comment by eatonphil** [comment]
Rebased, create page working.

**Comment by mparke** [comment]
merge conflicts, rebase again?

**Comment by eatonphil** [comment]
Thanks!

**Pull request merged**
