### PR TITLE
change: [UIE-8228] - DBaaS Resize GA: Enable Downsizing, update node presentation

### PR DESCRIPTION
**Pull request by mpolotsk-akamai**
## Description 📝

DBaaS Resize GA: Enable Downsizing (horizontal and vertical) and enable 'Shared' tab for resizing 2N cluster. Updated node presentation.

## Changes  🔄

Database Resize: 
- Enable Downsizing (horizontal and vertical)
- Enable the 'Shared' tab for resizing 2N cluster
- Enable 'Current Plan' for selection

Updated node presentation in the 'Database Summary' and 'Database Resize' tabs.

## Target release date 🗓️

12/10/24

## Preview 📷

| Before  | After   |
| ------- | ------- |
| Screenshot 2024-11-22 at 4 00 42 PM | Screenshot 2024-11-22 at 4 01 06 PM |
| Screenshot 2024-11-22 at 4 05 31 PM | Screenshot 2024-11-22 at 4 05 40 PM |
| Screenshot 2024-11-22 at 4 06 04 PM | Screenshot 2024-11-22 at 4 06 13 PM |

### Prerequisites

- dbaasV2 feature flag set to GA
- choose a new database

### Verification steps

- Select the new database.
- Navigate to the Database Resize tab.
- Database Cluster is available for downsizing (both horizontal and vertical)
- Shared Tab is enabled for 2 Nodes Cluster 
- Database Resize > Current configurations: the Nodes presentation is updated
- Summary tab: the Nodes presentation is updated

## As an Author, I have considered 🤔

- 👀 Doing a self review
- ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- 🤏 Splitting feature into small PRs
- ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- 🧪 Providing/improving test coverage
- 🔐 Removing all sensitive information from the code and PR description
- 🚩 Using a feature flag to protect the release
- 👣 Providing comprehensive reproduction steps
- 📑 Providing or updating our documentation
- 🕛 Scheduling a pair reviewing session
- 📱 Providing mobile support
- ♿  Providing accessibility support

<br/>

- [x] I have read and considered all applicable items listed above.

## As an Author, before moving this PR from Draft to Open, I confirmed ✅

- [x] All unit tests are passing
- [x] TypeScript compilation succeeded without errors
- [x] Code passes all linting rules

### CODE REVIEW

**Comment by bnussman-akamai** [comment]
Can you resolve the conflicts? We just fixed some DBaaS test flake in https://github.com/linode/manager/pull/11332 and are hoping to keep it not flakey

**Comment by mpolotsk-akamai** [comment]
> Can you resolve the conflicts? We just fixed some DBaaS test flake in #11332 and are hoping to keep it not flakey

@bnussman-akamai , resolved

**Review by cpathipa — APPROVED** [review]
Functionality and code changes look good to me. Confirming the verification steps.

**Review by bnussman-akamai — APPROVED** [review]

**Comment by cpathipa** [comment]
Confirming failed clone-linode.spec.ts passed in local and I think service-transfer is not relevant to this PR.

**Pull request merged**
