### PR TITLE
M3-603 - Storybook Visual Regression

### PR DESCRIPTION
**Pull request by patthiel**
* Adds storyshots integration for visual regression comparison
* Sets screenshot difference threshold to 2 % difference
* Integrated visual regression into travis builds
* Added custom jest config to run only the storyshots tests
* Added `yarn storyshots` script
* Added `yarn storyshots:update` script

## To Run Storyshots tests:

1. Be running docker
2. No need to have storybook running, docker will run it.. but even if you are running it, it won't conflict with the containers (since it listens on the container network)

```bash
yarn storyshots
```

## To Update Storyshots Snapshots

1. Same as 1&2 above

```bash
yarn storyshots:update
```

### CODE REVIEW

**Comment by patthiel** [comment]
Adding back the WIP label, as we figure out ways to either speed this up or move into baker.

**Comment by asauber** [comment]
Take two minutes to run on my machine with no failures. 

Looks like we can use "Conditional Stages" to run these only on PRs against master if that's the plan.

https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#conditional-stages
https://github.com/travis-ci/travis-ci/issues/8846

LGTM

**Comment by patthiel** [comment]
@asauber awesome! I didn't know about those conditional stages.

@asauber @rjstires as champions of the build of this project, would you feel comfortable with us adding a conditional to build on PR's against master? or shall we table this until we introduce more build improvements in the future?

**Comment by asauber** [comment]
I say go for it

**Comment by patthiel** [comment]
It looks like we would have to refactor the current jenkins file to use build stages to take advantage of the conditional stages feature. per https://blog.travis-ci.com/2017-09-12-build-stages-order-and-conditions

I think we should create a separate ticket for that and address integrating storyshots into the build at that point in time.

**Comment by patthiel** [comment]
thanks for reviewing!

**Pull request merged**
