### PR TITLE
Improve the DRYness of tests

### PR DESCRIPTION
**Pull request by SirCmpwn**
This is a bit of a big PR.

* [x] Restructure test/data/
* [x] Implement expectRequest utility function
* [x] Use expectRequest in all places it's appropriate
* [x] Make use of sinon sandboxes consistent across the project
* [x] Clean up lingering uses of data that doesn't origniate from test/data/
* [ ] ~~Sort out the warnings raised in our test runs~~

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Take particular note of ae605dc when reviewing this PR.

**Comment by na3d** [comment]
👍

**Comment by SirCmpwn** [comment]
Ran deepFreeze on all of our state. Found a few places where the global test state was being mutated. Please do not mutate the global test state.

**Comment by eatonphil** [comment]
:+1:

**Comment by eatonphil** [comment]
can you point out those global test state mutations?

**Comment by SirCmpwn** [comment]
https://github.com/linode/manager/pull/363/commits/84d8c928968ef9f8f13be76f04aa12df86927a53#diff-743dad63e15ddf4ba548e5dc6670deffL32

**Comment by SirCmpwn** [comment]
Hold on, do not merge

**Comment by eatonphil** [comment]
Gotcha, reminder that it's easy enough to accomplish that line by create a new object with only that attribute altered:

    customTestBackup = { ...testBackup, state: 'pending' };

**Comment by SirCmpwn** [comment]
False alarm, merge at the ready.

**Pull request merged**
