### PR TITLE
M3-5300 Update several dependencies

### PR DESCRIPTION
**Pull request by johnwcallahan**
## Description

This PR upgrades several dependencies to pick up security updates:

**prismjs**
- forced resolution to 1.24.1
- minor version jump

**glob-parent**
- forced resolution to 5.1.2
- ⚠️ major version jump (not a direct dependency)

**browserslist**
- forced resolution to 14.16.5
- minor version jump

**lodash**
- forced resolution to 4.17.19
- minor version jump

**immer**
- forced resolution to 8.0.4
- ⚠️ major version jump, code changes made accordingly

**trim**
- forced resolution to 0.0.3
- patch version jump

**ws**
- forced resolution to 7.5.3
- ⚠️ major version jump (not a direct dependency)

**merge**
- upgraded to 2.1.0 via npm-dts-webpack-plug upgrade
- ⚠️  major version jump (not a direct dependency)

**property-expr**
- upgrade to 2.0.4 via yup upgrade
- code changes made to fix breaking changes in yup

## How to test

Build, run, test the app. Try using the sdk/validation library separately. Run e2e tests and unit tests.

### CODE REVIEW

**Review by DevDW — APPROVED** [review]
- [X] App compiles & works
- [X] Tests passed
- [X] Validation library is working as well

**Review by tiffwong — APPROVED** [review]
Looks good to me as well

**Review by bnussman — APPROVED** [review]
Everything checked out for me!

**Review by HanaXu — APPROVED** [review]
LGTM!

**Review by codyfinn — APPROVED** [review]

**Pull request merged**
