### PR TITLE
M3-6007: Make Help Banner text more readable

### PR DESCRIPTION
**Pull request by cpathipa**
## Description  📝

Added line-height 1 to 1.25rem

## Preview 📷

Before
image

After
image

## How to test 🧪

Click help & support > banner message appears

**How do I run relevant unit or e2e tests?**

### CODE REVIEW

**Review by mjac0bs — APPROVED** [review]
I was following the thread you tagged me in with Andrew -- agreed that `1.25rem` looks good for line height. The text on the notice seems easier to read and not as cluttered.

Agreed with Dajahi on the steps of updating the title of this PR with a ticket # and description. Other than that, this looks good and congrats on the PR!

**Comment by cpathipa** [comment]
Thank you @dwiley-akamai and @mjac0bs Created ticket for reference [M3-6007](https://jira.linode.com/browse/M3-6007) and update title accordingly.

**Comment by mjac0bs** [comment]
@cpathipa Thanks for making the ticket! We usually include a short description of the ticket in the title of the PR, as well. I just updated this PR's title accordingly.

**Comment by cpathipa** [comment]
Thanks @mjac0bs Will follow the same.

**Pull request merged**
