### PR TITLE
feat: [OCA-1381] - Adds August 2024 Marketplace apps

### PR DESCRIPTION
**Pull request by tbaka**
## Description 📝
Adds new Marketplace apps for July 2024
Apache Cassandra Cluster
~Apache Spark Cluster~ (delayed)
Openbao
Valkey
InfluxDB

## Changes  🔄
List any change relevant to the reviewer.
- updates oneClickAppsv2.ts
- adds SVG public assets

## Target release date 🗓️
July 22 2024

> [!IMPORTANT]  
> Delayed until August 5, 2024.

### CODE REVIEW

**Comment by mjac0bs** [comment]
@tbaka Is this ready to be reviewed? It's still in draft, but the target release date says July 22nd. We're cutting the release branch for 7/22 tomorrow, so this will need some eyes to make it in.

**Comment by tbaka** [comment]
The only thing we're missing is the svgs, they should be added today

**Review by mjac0bs — COMMENTED** [review]
I added a new variation to our `one-click-app` Launch Darkly flag for July 2024 and turned on that variation in dev. This variation will need to be served in prod after our next release in order to the July 2024 apps to display as New Apps, @carrillo-erik.

I also confirmed that the apps display and the website links and copy looks good minus one typo. I am not seeing Cassandra tagged with the cluster chip, though. Do any naming changes need to be made on the backend?

image

**Comment by tbaka** [comment]
good catch @mjac0bs, the live Stackscript for Cassandra had not been added to the backend. I've taken care of that and it should display the cluster chip.

**Review by mjac0bs — APPROVED** [review]
Thanks for addressing feedback @tbaka - this looks good pending the remaining svgs are added, so I'm approving.

Verified cluster chip is now displaying as expected. 
image

**Review by dwiley-akamai — APPROVED** [review]
Apache Cassandra Cluster, Openbao, Valkey, and InfluxDB displayed ✅
Linked website and descriptions for each look good ✅

Approved pending the addition of the remaining SVG files

**Comment by mjac0bs** [comment]
We're delaying this until the August 5 release in order to have the remaining svgs ready. (cc: upcoming fire chief @jdamore-linode)

**Comment by tbaka** [comment]
@jdamore-linode I have added the remaining SVGs. Do you want to merge this PR, or should I resubmit it?

**Comment by mjac0bs** [comment]
@tbaka Thanks for adding. I just confirmed all the svgs are looking good and kicked off the tests. I'll merge this once they're finished and it will go out on the 08/05 release.

image

**Pull request merged**
