### PR TITLE
Python library docs

### LINKED ISSUE #1731: Add python api wrapper reference pages

### PR DESCRIPTION
**Pull request by abemassry**
closes #1731

### CODE REVIEW

**Comment by abemassry** [comment]
@eatonphil we'll add the pythonConvert script to prebuild.js

**Comment by abemassry** [comment]
@eatonphil we've added the pythonConvert script to the prebuild

**Comment by eatonphil** [comment]
I like the direction but this page needs to be fixed up. The title should probably just be 'Python' and there should be no guides here.

screen shot 2017-06-13 at 8 23 35 am

**Comment by abemassry** [comment]
I'll fix the Python Guide and change it to Python Library

There are no guides here and everything is within the context of the Library

**Pull request merged**
